app/assets/stylesheets/govuk_elements.scss
app/assets/stylesheets/investigations.scss
app/controllers/investigations_controller.rb
app/models/investigation.rb
app/views/investigations/_form.html.erb
app/views/investigations/show.html.erb
db/migrate/20180723103012_update_investigation_from_design_sprint.rb
db/schema.rb
lib/tasks/rapex_import.rake
test/controllers/investigations_controller_test.rb
test/fixtures/investigations.yml
test/fixtures/sources.yml

Improve the case details page. Still would require some work to get it to exactly match the wireframes

Mspsds 181 case details

---

app/assets/javascripts/businesses.js
app/clients/companies_house_client.rb
app/controllers/businesses_controller.rb
app/helpers/businesses_helper.rb
app/models/business.rb
app/views/businesses/_form.html.erb
app/views/businesses/_search_results.erb
app/views/businesses/index.html.erb
app/views/businesses/new.html.erb
config/initializers/companies_house.rb
config/routes.rb
db/migrate/20180727134613_make_businesses_company_number_unique.rb
db/schema.rb
test/fixtures/businesses.yml

Mostly finished, still need to look into postcode APIs

Mspsds 193 extra business features

---

app/views/application/_history.html.erb
app/views/businesses/show.html.erb
app/views/investigations/show.html.erb

We should eventually merge it with the investigation activity timeline

MSPSDS-275: Update styling for history section

---

app/controllers/businesses_controller.rb
app/controllers/investigations_controller.rb
app/controllers/products_controller.rb
app/helpers/application_helper.rb
app/helpers/businesses_helper.rb
app/helpers/elasticsearch_query.rb
app/helpers/investigations_helper.rb
app/helpers/products_helper.rb
app/helpers/search_helper.rb
app/helpers/search_params.rb
app/models/concerns/searchable.rb
app/models/investigation.rb
app/views/businesses/index.html.erb
app/views/investigations/index.html.erb
app/views/products/index.html.erb

This just adds open/closed status filtering for cases, but the basic functionality should be fairly easy to extend to allow more filter options in the future.

MSPSDS-212: Add case filtering by status

---

.dockerignore
worker/Dockerfile

@raamSoftwire and @jasiekmiko FYI.
I think it's something to do with `chmod` not working on Docker for Windows? https://docs.docker.com/docker-for-windows/troubleshoot/#volumes

MSPSDS-378: Fix issue with ClamAV running in Docker for Windows

---

web/app/views/application/_investigation_heading.html.slim
web/app/views/investigations/show.html.slim

This fixes the error seen at https://mspsds-int.cloudapps.digital/investigations/21009/images.

MSPSDS-604: Fix broken link on case page

---

web/app/views/investigations/businesses/index.html.slim
web/app/views/investigations/index.html.slim
web/app/views/products/_form.html.slim
web/app/views/products/_suggestions_container.html.slim

fix fonts in businesses/index, investigations/index, products/_form and products_suggestions_container

MSPSDS-655: fix: some small font fixes

---

web/app/views/application/_report_summary.html.slim
web/app/views/investigations/tabs/_details.html.slim

Mostly cosmetic changes, plenty of stuff expected to be displayed in the 'Report' part is not really implemented yet.

MSPSDS-639: Format full details tab of case to follow designs

---

web/app/models/audit_activity.rb
web/app/models/audit_activity/base.rb
web/app/models/audit_activity/business/add.rb
web/app/models/audit_activity/business/base.rb
web/app/models/audit_activity/document.rb
web/app/models/audit_activity/document/add.rb
web/app/models/audit_activity/document/base.rb
web/app/models/audit_activity/document/destroy.rb
web/app/models/audit_activity/document/update.rb
web/app/models/audit_activity/image.rb
web/app/models/audit_activity/image/add.rb
web/app/models/audit_activity/image/base.rb
web/app/models/audit_activity/image/destroy.rb
web/app/models/audit_activity/image/update.rb
web/app/models/audit_activity/investigation.rb
web/app/models/audit_activity/investigation/add.rb
web/app/models/audit_activity/investigation/base.rb
web/app/models/audit_activity/product.rb
web/app/models/audit_activity/product/add.rb
web/app/models/audit_activity/product/base.rb
web/app/models/investigation.rb

If the ideas shown in #225 are OK, then this is the part of them that fixes master

Master activites fix

---

keycloak/README.md
web/app/assets/stylesheets/autocomplete.scss
web/app/assets/stylesheets/main.scss
web/app/controllers/concerns/file_concern.rb
web/app/controllers/investigations/activities_controller.rb
web/app/controllers/investigations_controller.rb
web/app/helpers/application_helper.rb
web/app/models/audit_activity/investigation/add.rb
web/app/models/audit_activity/investigation/base.rb
web/app/models/investigation.rb
web/app/views/activities/_activity.json.jbuilder
web/app/views/activities/_form.html.slim
web/app/views/activities/index.html.slim
web/app/views/activities/index.json.jbuilder
web/app/views/activities/new.html.slim
web/app/views/investigations/assign.html.slim
web/app/views/investigations/index.xlsx.axlsx
web/app/views/investigations/priority.html.slim
web/app/views/investigations/tabs/_activity.html.slim
web/app/views/investigations/tabs/_details.html.slim
web/config/routes.rb
web/test/controllers/activities_controller_test.rb
web/test/controllers/investigations_controller_test.rb

I'd probably review this commit-by-commit.

MSPSDS-472: Pen test fixes

---

web/app/views/application/_file_upload_display.html.slim

MSPSDS-521: Fix button spacing for uploading a document or image

---

web/db/migrate/20181115164628_enable_pg_stat_statements.rb
web/db/schema.rb

The migration was missing despite being reflected in the schema, which
is why there's superficially no changes to the schema.rb

MSPSDS-472 Add missing migration to enable pgHero

---

web/app/models/business.rb
web/app/models/investigation.rb
web/app/models/product.rb
web/config/environments/production.rb
web/test/controllers/businesses_controller_test.rb
web/test/controllers/investigations/businesses_controller_test.rb
web/test/controllers/investigations/products_controller_test.rb
web/test/controllers/investigations_controller_test.rb
web/test/controllers/products_controller_test.rb
web/test/fixtures/investigations.yml
web/test/helpers/business_helper_test.rb
web/test/helpers/product_helper_test.rb
web/test/models/investigation_test.rb
web/test/system/investigation_assignee_test.rb

MSPSDS-538: Search cases by keyword

---

web/app/analyzers/anti_virus_analyzer.rb
web/app/models/concerns/activity_attachable.rb

After chatting with Ed we decided to not add an explicit information if a file gets deleted by antivirus. At least not for now since it's an edge case with little use.

MSPSDS: nil image bugfix

---

web/app/assets/stylesheets/shared.scss
web/app/controllers/investigations/corrective_actions_controller.rb
web/app/controllers/investigations/tests_controller.rb
web/app/helpers/legislation_helper.rb
web/app/models/corrective_action.rb
web/app/models/test.rb
web/app/views/application/_date_input.html.slim
web/app/views/application/_form_validation_display.html.slim
web/app/views/application/_related_attachment_fields.html.slim
web/app/views/investigations/corrective_actions/details.html.slim
web/app/views/investigations/emails/context.html.slim
web/app/views/investigations/incidents/details.html.slim
web/app/views/investigations/tests/details.html.slim
web/test/models/corrective_action_test.rb
web/test/models/test_test.rb
web/test/system/add_correspondence_from_flow_test.rb
web/test/system/corrective_actions_test.rb
web/test/system/document_test.rb
web/test/system/image_test.rb
web/test/system/investigation_incident_test.rb
web/test/system/investigation_test_request_test.rb
web/test/system/investigation_test_result_test.rb
web/test/system/question_flow_test.rb
web/test/system/record_email_correspondence_test.rb
web/test/system/reporter_flow_test.rb

This addresses a number of issues that came up during testing of the functionality for recording corrective actions and test requests/results on a case.

MSPSDS-551: Fixes to record corrective action flow

---

web/app/views/investigations/index.html.slim

I don't know why it wasn't on master, definitely remember fixing it a while back.

MSPSDS-538: Fix the xlsx bug(again?)

---

web/app/helpers/elasticsearch_query.rb
web/app/views/investigations/_case_card.html.slim
web/app/views/investigations/_highlight_card.html.slim
web/app/views/investigations/index.html.slim

MSPSDS-644: Address test issues

---

web/app/views/products/show.html.slim

Tiny change after clarification on a ticket

MSPSDS-764: Remove business tab and partial from products

---

web/app/models/correspondence/email.rb
web/app/models/correspondence/meeting.rb
web/app/models/correspondence/phone_call.rb
web/app/views/investigations/emails/context.html.slim
web/test/system/record_email_correspondence_test.rb
web/test/system/record_meeting_correspondence_test.rb
web/test/system/record_phonecall_correspondence_test.rb

Fixes addressing [these test results](https://regulatorydelivery.atlassian.net/browse/MSPSDS-550?focusedCommentId=13191&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13191) (with some points resolved in subsequent comments)

MSPSDS-550: Fixes for record email flow

---

web/app/assets/javascripts/investigations/businesses.js
web/app/assets/javascripts/investigations/products.js
web/app/controllers/businesses_controller.rb
web/app/controllers/locations_controller.rb
web/app/controllers/products_controller.rb
web/app/views/application/_tabs.html.slim
web/app/views/businesses/show.html.slim
web/app/views/businesses/tabs/_locations.html.slim
web/test/controllers/locations_controller_test.rb

Address test issues and fix a bug from previous 'cleanup' ticket

MSPSDS-777: Edit business locations

---

web/app/views/investigations/show.html.slim

Removed "asked by" and "description" field as these are now in activity tab

MSPSDS-761: Update question page

---

keycloak/configuration/initial-setup.json
web/app/controllers/investigations/businesses_controller.rb
web/app/controllers/investigations/products_controller.rb
web/app/controllers/investigations_controller.rb
web/app/mailers/notify_mailer.rb

1. Replace 'investigation' with 'case'
2. Change email template via notify website

MSPSDS-760: Service tidy up

---

web/app/assets/stylesheets/main.scss
web/app/views/application/_business_heading.html.slim

Fixes a bug where content moves horizontally when switching from a page with a sidebar to one without and vice versa.

MSPSDS-805: Styling fixes for office private beta

---

cosmetics-web/Gemfile.lock
shared-web/lib/shared/web.rb
shared-web/shared-web.gemspec

Hoping this will fix all these weird issues when dependencies get moved to shared-web

COS-NONE Fix dependencies from shared-web

---

.dependabot/config.yml
ci/get-changed-components.sh
cosmetics-web/Gemfile.lock
cosmetics-web/app/assets/javascripts/helloworld.js
mspsds-web/app/views/application/_documents_list_summary.html.slim
mspsds-web/app/views/investigations/activities/new.html.slim

And other various fixes.
Going commit-by-commit might be easiest.
The dependabot config has been added recently and is defined [here](https://dependabot.com/blog/introducing-config-files/).

COS-41: Remove ES6 from cosmetics

---

mspsds-web/app/views/application/_investigations_summary.html.slim
mspsds-web/app/views/investigations/_case_card.html.slim
mspsds-web/app/views/investigations/_table.html.slim
mspsds-web/app/views/investigations/index.html.slim

Also doing MSPSDS-898 in the same pull requests as they are tightly linked and tiny changes.

MSPSDS-889: Date display match sorting

---

mspsds-web/app/helpers/investigations/visibility_helper.rb
mspsds-web/app/views/investigations/visibility.html.slim

MSPSDS-NONE: Update text for show and tell

---

mspsds-web/app/views/layouts/application.html.slim

This is currently pointing to unmerged changes in `govuk-theme` submodule, for the sake of speeding up the review process. Will update to point back to a commit on master before merging.

MSPSDS-865 improve journeys between app and keycloak

---

mspsds-web/app/views/products/_product_card.html.slim

Making product_card origin same as details tab on product show page

MSPSDS-929 Change country_of_origin to country_of_origin_for_display

---

mspsds-web/app/views/investigations/emails/context.html.slim

Fixes 2 bug tickets at once. MSPSDS-911 is about it, and so is 975.

MSPSDS-975: Fix slim indentation for text styling

---

mspsds-web/app/assets/application/stylesheets/buttons.scss
mspsds-web/app/assets/application/stylesheets/main.scss
mspsds-web/app/views/contacts/remove.html.slim
mspsds-web/app/views/documents/remove.html.slim
mspsds-web/app/views/investigations/businesses/remove.html.slim
mspsds-web/app/views/investigations/products/remove.html.slim
mspsds-web/app/views/locations/remove.html.slim

Possibly waiting on Ed H's confirmation of my comment [here](https://regulatorydelivery.atlassian.net/browse/MSPSDS-894?focusedCommentId=13662&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13662) but any change he requests will be small.

MSPSDS-894 style: change remove buttons to use govuk-error-color

---

shared-web/app/analyzers/shared/web/anti_virus_analyzer.rb

There are a couple of things going on here:
- The first is that the default Clamby config value for `error_clamscan_client_error` is `false`. That means if `clamd` has crashed (which I think is what's causing the issues on PaaS), `Clamby.safe?` returns `false`, we identify the file as a virus and delete it. It should now throw an error, which causes the job to be retried later (giving us time to restart the worker or something like that).
- When we detected (or incorrectly detected, due to the above) that a file was a virus, we'd delete it. We deleted it synchronously using `.purge`, which I think meant that the currently running analyser would fail when it tried to set the metadata (on the now deleted blob). This was the `Can't modify frozen hash` error which we've been seeing a lot on …

MSPSDS-6: Correctly throw error on ClamAV problem

---

cosmetics-web/README.md
cosmetics-web/app/controllers/application_controller.rb
cosmetics-web/app/controllers/concerns/http_auth_concern.rb

Credentials are specified as environment variables.

COSBETA-85: Add HTTP Basic authentication

---

cosmetics-worker/Dockerfile
cosmetics-worker/docker-entrypoint.sh
cosmetics-worker/manifest.yml

The country list from the GOV.UK country and territory autocomplete package is used in helper methods that are called by the file analyzers on Cosmetics Worker.
For now, the `package.json` file is shared with Cosmetics Web to ensure the same dependency versions are used on both.

COSBETA-86: Install required node packages when building Cosmetics Worker

---

cosmetics-web/app/analyzers/read_data_analyzer.rb

This ensures log messages are sent to STDOUT and can be passed to external logging services.

COSBETA-125: Use Sidekiq logger in analyzers

---

cosmetics-web/app/analyzers/read_data_analyzer.rb

Quick change to add more logging to help investigate a bug around file upload

COSBETA-125: Add logging for Standard Error

---

cosmetics-web/app/mailers/notify_mailer.rb

This managed to slip though in the last PR. I've added a test that would have picked this up as part of COSBETA-39, so I won't add another here.

COSBETA-37: Fix typo in Notify mailer logic

---

cosmetics-web/app/views/layouts/_navbar.html.slim
cosmetics-web/app/views/responsible_persons/show.html.slim

COSBETA-171: fix UI typos

---

cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb
cosmetics-web/app/models/notification.rb
cosmetics-web/spec/controllers/responsible_persons/notifications_controller_spec.rb

COSBETA-173: Fix bug where uploading formulation file didn't update notification state

---

cosmetics-web/config/webpacker.yml

Adds polling for Webpacker so you shouldn't need to restart web before seeing JS changes anymore

Add JS polling to Cosmetics

---

mspsds-web/test/system/keycloak_test.rb
shared-web/app/controllers/shared/web/sessions_controller.rb

MSPSDS-932 remove sign in banner

---

mspsds-web/app/views/homepage/non_opss.html.slim

MSPSDS-1090 update ts homepage

---

cosmetics-web/app/views/responsible_persons/verification/index.html.slim

Removing this link as part of resolving this bug, I've raised COSBETA-198 as a separate ticket to implement it properly

COSBETA-163: Remove link to change contact person details

---

mspsds-web/app/views/investigations/index.html.slim

Moving the case button to be on the same row as the title.

MSPSDS-1096: Move create new case button

---

mspsds-web/app/views/help/about.html.slim

MSPSDS-1095 feat: add content to help/about.html.slim

---

cosmetics-web/app/views/landing_page/index.html.slim

COSBETA-190: Update copy on landing page

---

mspsds-web/app/controllers/investigations/ts_investigations_controller.rb
mspsds-web/app/controllers/investigations_controller.rb
mspsds-web/app/policies/investigation_policy.rb
mspsds-web/app/views/investigations/created.html.slim
mspsds-web/app/views/investigations/ts_investigations/reference_number.html.slim
mspsds-web/config/routes.rb
mspsds-web/test/system/create_ts_investigation_test.rb

MSPSDS-1091 ts flow confirmation page

---

cosmetics-web/app/controllers/responsible_persons/add_notification_wizard_controller.rb
cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb
cosmetics-web/app/views/notification_build/add_product_name.html.slim
cosmetics-web/app/views/responsible_persons/add_notification_wizard/do_you_have_files_from_eu_notification.html.slim
cosmetics-web/app/views/responsible_persons/add_notification_wizard/have_products_been_notified_in_eu.html.slim
cosmetics-web/app/views/responsible_persons/add_notification_wizard/register_on_eu_system.html.slim
cosmetics-web/app/views/responsible_persons/add_notification_wizard/was_product_on_sale_before_eu_exit.html.slim
cosmetics-web/app/views/responsible_persons/add_notification_wizard/will_products_be_notified_in_eu.html.slim
cosmetics-web/app/views/responsible_persons/notification_files/new.html.slim
cosmetics-web/app/views/responsible_persons/notifications/index.html.slim
cosmetics-web/config/routes.rb
cosmetics-web/db/migrate/20190320143555_add_was_notified_before_eu_exit_to_notifications.rb
cosmetics-web/db/schema.rb
cosmetics-web/spec/controllers/responsible_persons/add_notification_wizard_controller_spec.rb

COSBETA-184 Add pages to route users to bulk or manual journey

---

cosmetics-web/app/models/cpnp_export.rb
cosmetics-web/spec/analyzers/read_data_analyzer_spec.rb

COSBETA-161 Update component state when importing files from CPNP

---

shared-web/config/initializers/keycloak.rb

MSPSDS-1116: Don't run keycloak code on sidekiq

---

psd-web/app/assets/application/stylesheets/footer.scss
psd-web/app/assets/application/stylesheets/main.scss
psd-web/app/views/layouts/application.html.slim

Fix the links so that invisible text is visible to screen readers, remove OGL logo and mentions, order links alphabetically.

MSPSDS-1103: Footer bugfixes and design updates

---

shared-web/config/initializers/keycloak.rb

MSPSDS-1116: Capture additional errors on keycloak error

---

CHANGELOG.md
keycloak/configuration/initial-setup.json

MSPSDS-356 enable processing team members to manage users

---

psd-web/app/mailers/notify_mailer.rb
psd-web/app/models/audit_activity/base.rb
psd-web/app/models/audit_activity/corrective_action/base.rb
psd-web/app/models/audit_activity/correspondence/add_meeting.rb
psd-web/app/models/audit_activity/document/base.rb
psd-web/app/models/audit_activity/investigation/add.rb
psd-web/app/models/audit_activity/test/base.rb
psd-web/app/models/investigation.rb
psd-web/db/migrate/20190321122934_populate_assignee_and_description.rb
shared-web/app/clients/shared/web/keycloak_client.rb

Combination of #838, #839, #840 and #841 to save us doing 4 separate staging releases.

Staging fixes

---

shared-web/app/assets/application/stylesheets/banner.scss

MSPSDS-1137 fix: fix banner colour in ie11

---

cosmetics-web/deploy.sh
cosmetics-web/manifest.yml
psd-web/deploy.sh
psd-web/manifest.yml

This seems to have a ~5x increase in deployment speed from my machine - hopefully it'll have the same effect on Travis deployments!

MSPSDS-6: Bump app memory whilst compiling webpack assets

---

cosmetics-web/app/analyzers/read_data_analyzer.rb

Add a Sidekiq log for success file uploads

COSBETA-235: Add logging for successful file upload

---

cosmetics-web/app/controllers/component_build_controller.rb
cosmetics-web/app/controllers/notification_build_controller.rb
cosmetics-web/app/helpers/category_helper.rb
cosmetics-web/app/helpers/formulation_helper.rb
cosmetics-web/app/helpers/nano_materials_helper.rb
cosmetics-web/app/models/component.rb
cosmetics-web/app/models/notification.rb
cosmetics-web/app/views/component_build/add_cmrs.html.slim
cosmetics-web/app/views/component_build/add_component_name.html.slim
cosmetics-web/app/views/component_build/add_nanomaterial.html.slim
cosmetics-web/app/views/component_build/contains_nanomaterials.html.slim
cosmetics-web/app/views/component_build/number_of_shades.html.slim
cosmetics-web/app/views/component_build/select_category.html.slim
cosmetics-web/app/views/component_build/select_formulation_type.html.slim
cosmetics-web/app/views/component_build/select_frame_formulation.html.slim
cosmetics-web/app/views/component_build/upload_formulation.html.slim
cosmetics-web/app/views/notification_build/add_new_component.html.slim
cosmetics-web/app/views/notification_build/add_product_image.html.slim
cosmetics-web/app/views/notification_build/single_or_multi_component.html.slim
cosmetics-web/config/webpacker.yml
cosmetics-web/spec/controllers/component_build_controller_spec.rb
cosmetics-web/spec/controllers/notification_build_controller_spec.rb
cosmetics-web/spec/system/manual_notification_entry_spec.rb

Added nano-materials page (only the pre-defined nano-elements and the expose route and condition)
Added sub-sub-category page for the component
Added CMRs page
Added page for formulation type, frame formulation, and upload a formulation file
Added multi-component page (where it's possible to add new components and remove old ones)
It wasn't added system tests

COSBETA-194 first run through manual journey

---

cosmetics-web/app/views/notifications/_component_details.html.slim

Showing relevant info about nanomaterial exposure condition and route.

COSBETA-264: Fix display of application instruction info on check your answers page

---

.travis.yml
README.md
infrastructure/README.md
infrastructure/ci/deploy-if-changed.sh
infrastructure/fluentd/fluent.conf
infrastructure/fluentd/manifest.yml
psd-web/app/controllers/investigations/ts_investigations_controller.rb
psd-web/app/models/investigation.rb
psd-web/app/views/application/_business_summary.html.slim
psd-web/app/views/businesses/_business_card.html.slim
psd-web/app/views/documents/remove.html.slim
psd-web/app/views/products/_form.html.slim
psd-web/app/views/teams/invite_to.html.slim
psd-web/test/system/create_ts_investigation_test.rb

PSD-6: Rename accounts

---

cosmetics-web/app/controllers/notification_build_controller.rb
cosmetics-web/app/views/notification_build/add_internal_reference.html.slim
cosmetics-web/app/views/notifications/_product_details.html.slim
cosmetics-web/spec/controllers/notification_build_controller_spec.rb
cosmetics-web/spec/system/manual_notification_entry_spec.rb

COSBETA-302 Add page to manual journey for adding industry reference

---

cosmetics-web/spec/login_helpers.rb
psd-web/app/models/organisation.rb
psd-web/app/models/team.rb
psd-web/app/models/team_user.rb
psd-web/app/models/user.rb
psd-web/config/initializers/keycloak.rb
psd-web/test/controllers/teams_controller_test.rb
psd-web/test/models/user_test.rb
psd-web/test/test_helper.rb
shared-web/app/clients/shared/web/keycloak_client.rb
shared-web/app/controllers/shared/web/concerns/authentication_concern.rb
shared-web/app/controllers/shared/web/sessions_controller.rb
shared-web/app/models/shared/web/organisation.rb
shared-web/app/models/shared/web/user.rb
shared-web/config/initializers/keycloak.rb

Fixes for concurrent cookie access and new teams

---

psd-web/app/views/layouts/application.html.slim

The footer was missing the link to the support email
Ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1130

PSD-1130: Footer missing email link

---

cosmetics-web/app/controllers/component_build_controller.rb
cosmetics-web/app/models/component.rb
cosmetics-web/app/views/component_build/add_cmrs.html.slim
cosmetics-web/app/views/component_build/add_component_name.html.slim
cosmetics-web/app/views/component_build/add_physical_form.html.slim
cosmetics-web/app/views/component_build/number_of_shades.html.slim
cosmetics-web/app/views/component_build/select_category.html.slim
cosmetics-web/app/views/component_build/upload_formulation.html.slim
cosmetics-web/spec/controllers/component_build_controller_spec.rb
cosmetics-web/spec/system/manual_notification_entry_spec.rb

Add question for the product's physical form

COSBETA-205: Add question for the product's physical form

---

cosmetics-web/app/assets/packs/shared.js
cosmetics-web/app/controllers/component_build_controller.rb
cosmetics-web/app/helpers/category_helper.rb
cosmetics-web/app/models/component.rb
cosmetics-web/app/views/component_build/select_category.html.slim
cosmetics-web/app/views/component_build/select_frame_formulation.html.slim
cosmetics-web/spec/system/manual_notification_entry_spec.rb

* Import js file on comestics shared file in order to include autocomplete function
* Add validation to select frame formulation page
* Show per category level on select category page
* Add error summaries to select_category page and select_frame_formulation

COSBETA-245 Improvements for large drop down select questions

---

cosmetics-web/app/views/nanomaterial_build/confirm_restrictions.html.slim

This covers the journey where all nanomaterials are used in accordance with the relevant annex for their intended use
(Open Annex link in a new tab)

COSBETA-11: Open link to nanomaterial regulations in a new window

---

cosmetics-web/app/controllers/trigger_questions_controller.rb
cosmetics-web/app/views/trigger_questions/ph_mixed_hair_dye.html.slim
cosmetics-web/spec/system/manual_notification_entry_spec.rb

This question is already asked in a similar form near the start of the manual journey (after "Does the kit need to be mixed?"), and is only relevant at the product level, whereas trigger rule questions are asked per component.

 COSBETA-439: Remove mixed hair dye trigger rule question

---

cosmetics-web/app/controllers/trigger_questions_controller.rb
cosmetics-web/app/views/trigger_questions/ph_mixed_hair_dye.html.slim
cosmetics-web/spec/system/manual_notification_entry_spec.rb

This question is already asked in a similar form near the start of the manual journey (after "Does the kit need to be mixed?"), and is only relevant at the product level, whereas trigger rule questions are asked per component.

COSBETA-439: Remove mixed hair dye trigger rule question

---

cosmetics-web/app/helpers/date_helper.rb
cosmetics-web/app/views/application/_warning_text.html.slim
cosmetics-web/app/views/landing_page/submit_landing_page.html.slim

Changes to simplify the guidance on the landing page.

COSBETA-436: Update landing page content

---

cosmetics-web/app/views/landing_page/submit_landing_page.html.slim

I think this fixes the whitespace on this change

Maybe fixing where the '(Brexit)' clarification

---

cosmetics-web/app/views/landing_page/submit_landing_page.html.slim
cosmetics-web/app/views/notification_build/add_internal_reference.html.slim
cosmetics-web/app/views/notification_build/add_product_name.html.slim
cosmetics-web/app/views/notification_build/is_mixed.html.slim
cosmetics-web/app/views/poison_centres/notifications/show_poison_centre.html.slim
cosmetics-web/app/views/responsible_persons/add_notification_wizard/have_products_been_notified_in_eu.html.slim
cosmetics-web/app/views/responsible_persons/add_notification_wizard/will_products_be_notified_in_eu.html.slim
cosmetics-web/app/views/responsible_persons/contact_persons/_form.slim

Updated content per user feedback, for clarity and consistency.

Wave 1 content: COSBETA 517

---

cosmetics-web/app/controllers/nanomaterial_build_controller.rb
cosmetics-web/app/views/nanomaterial_build/non_standard_nanomaterial_notified.html.slim
cosmetics-web/spec/controllers/nanomaterial_build_controller_spec.rb

Create the Non-Standard Nanomaterial page.
Replace placeholder page with the new page.
https://regulatorydelivery.atlassian.net/browse/COSBETA-535

COSBETA-535: Check whether user has uploaded non-standard nanomaterial information

---

cosmetics-web/app/controllers/guidance_controller.rb
cosmetics-web/app/views/guidance/how_to_notify_nanomaterials.html.slim
cosmetics-web/config/routes.rb

Add guidance page for Nanomaterial

COSBETA-219 - Create page to host nanomaterials guidance

---

keycloak/manifest.yml
psd-web/deploy.sh
psd-web/manifest.yml

Increase instance memory

---

.gitignore
psd-web/app/views/businesses/tabs/_details.html.slim

Componentise summary list (add it for business full details)

---

cosmetics-web/app/controllers/additional_information_controller.rb
cosmetics-web/app/models/component.rb
cosmetics-web/app/models/nano_element.rb
cosmetics-web/app/models/nano_material.rb
cosmetics-web/app/models/notification.rb

Add functionality to allow user to update their nano-material information.

COSBETA-555 

---

cosmetics-web/app/models/nano_element.rb

No need to check for an empty purpose

---

cosmetics-web/config/routes.rb

Resolves issue where search endpoint returns a 500 static page.

Update routes so that search does not get lost

---

psd-web/app/views/introduction/overview.html.slim
psd-web/app/views/introduction/report_products.html.slim
psd-web/app/views/introduction/share_data.html.slim
psd-web/app/views/introduction/track_investigations.html.slim

Ticket: https://trello.com/c/Mtjj5vTm

Change intro slides content

---

cosmetics-web/app/controllers/nanomaterial_build_controller.rb
cosmetics-web/app/models/nano_element.rb
cosmetics-web/db/migrate/20190911114416_add_confirm_restrictions_to_nano_elements.rb
cosmetics-web/db/schema.rb
cosmetics-web/spec/controllers/nanomaterial_build_controller_spec.rb
cosmetics-web/spec/models/nano_element_spec.rb

Store whether a user has confirmed notification of toxicology
https://regulatorydelivery.atlassian.net/browse/COSBETA-615

COSBETA-615 - Storing non-standard nanomaterial data

---

cosmetics-web/app/views/layouts/_footer.html.slim

https://regulatorydelivery.atlassian.net/browse/COSBETA-558
(originally merged as https://github.com/UKGovernmentBEIS/beis-opss/pull/1328)

Add guidance links to footer

---

cosmetics-web/config/routes.rb

Fixes a bug accidentally introduced by #1375.

Bugfix: this contraint should match the SUBMIT_HOST

---

cosmetics-web/spec/controllers/additional_information_controller_spec.rb

Using `let!` makes our tests flakey. So remove it to keep things consistent.

Resolve flakey tests

---

.travis.yml

Production will be deployed only when staging will be deployed.
https://docs.travis-ci.com/user/build-stages/#how-do-build-stages-work
```
Stages group jobs that run in parallel and different stages run sequentially.
```

Deploy directly to production

---

.travis.yml

Revert "Dont need to build on prod deploy"

---

cosmetics-web/config/initializers/sidekiq.rb

This daily scheduled task fails as the Sidekiq job is no longer needed.

Remove old Sidekiq job

---

cosmetics-web/app/controllers/sessions_controller.rb

Bugfix for https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-705

Bugfix: no need to authorize user when logging out

---

cosmetics-web/app/views/application/_govuk_details.html.slim
cosmetics-web/app/views/application/_mandatory_field_error.slim
cosmetics-web/app/views/application/_radio_select_error.slim

This removes some view partials which aren’t being used at all.

Delete unused partials

---

infrastructure/ci/build-docker-images.sh

(Short-term fix whilst we work on removing the docker hub push / pull step)

Fix deploys by restoring docker builds of the app

---

.github/workflows/review-apps.yml
cosmetics-web/deploy-review.sh
cosmetics-web/manifest.review.yml

See [documentation](https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html) – this avoids downtime when deploying updates to review apps.

Use rolling deployment strategy

---

cosmetics-web/manifest.review.yml
cosmetics-web/manifest.yml

This injects the antivirus environment variables.

bind app to antivirus env

---

.github/workflows/rubocop.yml
cosmetics-web/.rubocop.yml
cosmetics-web/Rakefile
cosmetics-web/lib/tasks/cloudfoundry.rake
cosmetics-web/lib/tasks/coverage.rake
cosmetics-web/lib/tasks/cpnp_import.rake
cosmetics-web/spec/db/migrate/20190923133032_add_minimum_and_maximum_ph_to_components_spec.rb
cosmetics-web/spec/file_helpers.rb
cosmetics-web/spec/support/feature_helpers.rb

Thanks to @StupidCodeFactory for suggesting a better way to do this [over on the PSD project](https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/207).

Updates github workflow rubocop job to cache gems from Gemfile

---

cosmetics-web/app/controllers/registration/account_security_controller.rb
cosmetics-web/app/controllers/responsible_persons/team_members_controller.rb
cosmetics-web/app/mailers/notify_mailer.rb
cosmetics-web/app/models/pending_responsible_person_user.rb
cosmetics-web/app/models/submit_user.rb
cosmetics-web/app/views/responsible_persons/team_members/signed_as_another_user.html.erb
cosmetics-web/config/routes.rb
cosmetics-web/db/migrate/20200924084810_add_invitation_token_and_invitation_token_expires_at_to_pending_responsible_person_users.rb
cosmetics-web/db/schema.rb

Register invited user

---

cosmetics-web/app/mailers/notify_mailer.rb
cosmetics-web/spec/features/inviting_a_colleague_spec.rb

Different email when inviting existing user

---

cosmetics-web/.rubocop.yml
cosmetics-web/app/controllers/responsible_persons/team_members_controller.rb
cosmetics-web/app/helpers/form_helper.rb
cosmetics-web/app/models/pending_responsible_person_user.rb
cosmetics-web/app/views/layouts/application.html.erb
cosmetics-web/app/views/responsible_persons/team_members/index.html.erb
cosmetics-web/config/routes.rb
cosmetics-web/db/migrate/20201006082502_remove_expires_at_from_pending_responsible_person_users.rb
cosmetics-web/db/schema.rb
cosmetics-web/spec/factories/pending_responsible_person_users.rb
cosmetics-web/spec/features/inviting_a_colleague_spec.rb
cosmetics-web/spec/requests/responsible_persons/team_members_spec.rb
cosmetics-web/spec/support/render_errors.rb

Resends invitation email and extends token.

Resend invitation

---

.github/workflows/deploy.yml
.github/workflows/review-apps-delete-dangling.yml
.github/workflows/review-apps-delete.yml
.github/workflows/review-apps.yml
cosmetics-web/deploy-github-functions.sh

- Replace[ deprecated workflow commands](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) for set environment.
- Fix deletion of review apps when closing a PR instead of merging it.
- Small refactors in workflow code.

Update Github workflows

---

cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb
cosmetics-web/app/models/image_upload.rb
cosmetics-web/app/policies/responsible_person_notification_policy.rb
cosmetics-web/app/views/responsible_persons/contact_persons/_form.html.erb
cosmetics-web/app/views/responsible_persons/notifications/delete.html.erb
cosmetics-web/app/views/responsible_persons/notifications/edit.html.erb
cosmetics-web/app/views/responsible_persons/notifications/index.html.erb
cosmetics-web/config/routes.rb
cosmetics-web/spec/features/multiple_responsible_person_spec.rb
cosmetics-web/spec/features/notifications_deleting_spec.rb
cosmetics-web/spec/policies/responsible_person_notification_policy_spec.rb
cosmetics-web/spec/requests/responsible_persons/notifications_spec.rb
cosmetics-web/spec/support/feature_helpers.rb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-911
As additional work, we display all notifications now in `Incomplete` tab.

Possibility to delete incomplete notification

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
cosmetics-web/app/controllers/responsible_persons/wizard/notification_build_controller.rb
cosmetics-web/app/controllers/responsible_persons/wizard/trigger_questions_controller.rb
cosmetics-web/app/models/notification.rb
cosmetics-web/config/storage.yml
cosmetics-web/spec/controllers/notification_build_controller_spec.rb
cosmetics-web/spec/features/manual_post_brexit_notifications_spec.rb
cosmetics-web/spec/requests/trigger_questions_requests_spec.rb

Move image upload step after single_or_multi_step

---

cosmetics-web/app/views/responsible_persons/formulation_upload/new.html.erb
cosmetics-web/app/views/responsible_persons/wizard/component_build/upload_formulation.html.erb
cosmetics-web/spec/features/zip_file_upload_notifications_spec.rb
cosmetics-web/spec/support/feature_helpers.rb

Proper template when adding ingredients files for components from zip file.

948 upload ingredients from zip

---

cosmetics-web/config/locales/en.yml
cosmetics-web/spec/features/inviting_a_colleague_spec.rb
cosmetics-web/spec/models/pending_responsible_person_user_spec.rb

[JIRA COSBETA-966](https://regulatorydelivery.atlassian.net/browse/COSBETA-966)
Just slightly changing the wording for the validation error.

Update error message when inviting a team member

---

cosmetics-web/app/controllers/responsible_persons/account_wizard_controller.rb
cosmetics-web/app/forms/responsible_person_details_form.rb
cosmetics-web/app/models/responsible_person.rb
cosmetics-web/app/views/responsible_persons/account_wizard/enter_details.html.erb
cosmetics-web/config/locales/en.yml
cosmetics-web/spec/features/creating_a_responsible_person_spec.rb
cosmetics-web/spec/features/creating_multiple_responsible_persons_from_the_same_user_spec.rb
cosmetics-web/spec/features/multiple_responsible_person_spec.rb
cosmetics-web/spec/forms/responsible_person_details_form_spec.rb
cosmetics-web/spec/models/responsible_person_spec.rb
cosmetics-web/spec/support/feature_helpers.rb

[Jira ticket COSBETA-945](https://regulatorydelivery.atlassian.net/browse/COSBETA-945)
Allow duplicated RP names unless when attempting to create a responsible person with the same name as another RP either:
- we're member of.
- we have been invited to.

Allow duplicated RP names

---

cosmetics-web/app/views/layouts/_head.html.erb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1002)
We needed two scripts:
- One for loading the code from Google Tag manager.
- Second one for executing the gtag js code.

Fix Google Analytics

---

cosmetics-web/manifest.yml

Bumps the memory allocation for the web instances to resolve out of memory errors seen in production.

Bump web instance memory

---

cosmetics-web/app/controllers/help_controller.rb
cosmetics-web/app/views/help/accessibility_statement.html.erb
cosmetics-web/app/views/layouts/_footer.html.erb
cosmetics-web/config/routes.rb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1019
Add a link to accessibility statement within the footer.

Accessibility statement

---

cosmetics-web/app/views/guidance/how_to_notify_nanomaterials.html.erb
cosmetics-web/app/views/layouts/_footer.html.erb
cosmetics-web/spec/requests/guidance_pages_spec.rb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-999
Include updated nanomaterials guidance content in hyperlinked page

Add copy to the nanomaterials page

---

cosmetics-web/app/views/search/landing_page/index.html.erb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1000
Changes to the text on the home page of search to reflect the changes in the jira ticket

Update copy on search home page

---

cosmetics-web/app/views/responsible_persons/wizard/component_build/_exact_concentration.html.erb
cosmetics-web/app/views/responsible_persons/wizard/component_build/_ranges_concentration.html.erb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1041
Amend formulation upload pages to make it clearer what users must provide us

Formula page copy

---

cosmetics-web/app/views/responsible_persons/wizard/notification_build/add_product_image.html.erb
cosmetics-web/app/views/shared/_multiple_images_upload_description.html.erb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1040
Changes to the copy on the upload images page as per the ticket. Note: No changes were specified for the multiple images upload description, but I made similar changes for consistency between the two, Bruce will need to approve.

Changes to copy on upload images pages

---

cosmetics-web/Gemfile.lock
cosmetics-web/app/jobs/log_db_metrics_job.rb
cosmetics-web/config/initializers/sidekiq.rb

Data statistics

---

cosmetics-web/app/views/notifications/_contact_person_details.html.erb
cosmetics-web/app/views/responsible_persons/account_wizard/enter_details.html.erb
cosmetics-web/spec/support/feature_helpers.rb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1044
Small copy change in responsible persons form

Update business name copy

---

cosmetics-web/app/views/submit/landing_page/index.html.erb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1058
Change warning text on homepage as per the above ticket

Warning text change

---

cosmetics-web/app/services/one_off/search_user_bulk_inviter.rb

Ignore already invited users

---

cosmetics-web/app/views/responsible_persons/wizard/component_build/add_physical_form.html.erb
cosmetics-web/app/views/responsible_persons/wizard/component_build/contains_special_applicator.html.erb
cosmetics-web/app/views/responsible_persons/wizard/component_build/number_of_shades.html.erb
cosmetics-web/spec/support/feature_helpers.rb

Fix 'the the' typo

---

cosmetics-web/app/views/responsible_persons/product_image_upload/new.html.erb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1055

Proper upload copy

---

cosmetics-web/app/static/data/01-skin-care.json
cosmetics-web/app/static/data/02-skin-cleansing.json
cosmetics-web/app/static/data/03-hair-removal.json
cosmetics-web/app/static/data/04-bleach-for-body-hair.json
cosmetics-web/app/static/data/06-shaving-products.json
cosmetics-web/app/static/data/07-make-up.json
cosmetics-web/app/static/data/08-perfumes.json
cosmetics-web/app/static/data/09-sun-products-and-self-tanning-products.json
cosmetics-web/app/static/data/10-hair-and-scalp-care-products.json
cosmetics-web/app/static/data/12-hair-styling-products.json
cosmetics-web/app/static/data/14-Nail-conditioner.json
cosmetics-web/app/static/data/16-toothpaste.json
cosmetics-web/app/static/data/17-mouthwash.json

fixed typo in 2.3 and updated oils example

---

cosmetics-web/app/views/notifications/_component_details.html.erb
cosmetics-web/spec/controllers/poison_centres/notifications_controller_spec.rb
cosmetics-web/spec/features/manual_post_brexit_notifications_spec.rb
cosmetics-web/spec/features/manual_pre_brexit_notifications_spec.rb
cosmetics-web/spec/features/zip_file_upload_notifications_spec.rb
cosmetics-web/spec/requests/check_your_answers_page_spec.rb
cosmetics-web/spec/support/feature_helpers.rb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1109

Dont display CMRs if not added

---

cosmetics-web/Gemfile
cosmetics-web/Gemfile.lock

**Not to be merged**, just triggering the Review APP to tests changes in GovUK design rails.

Upgrade "GovUK Design System Rails" to v0.7.2

---

cosmetics-web/app/views/responsible_persons/show.html.erb
cosmetics-web/spec/features/multiple_responsible_person_spec.rb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1143)
Move from "Change" to "Switch" as "Change is used on the same page for editing.

Change the wording for link to RP switch

---

cosmetics-web/app/views/pagination/kaminari/_paginator.html.erb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1206)

Add current page to pagination display

---

cosmetics-web/app/assets/application/stylesheets/main.scss
cosmetics-web/app/assets/application/stylesheets/responsible_person_notification_page.scss
cosmetics-web/app/views/responsible_persons/notifications/edit.html.erb
cosmetics-web/app/views/responsible_persons/notifications/show.html.erb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1198)

Fix notification name wrap on notification title

---

cosmetics-web/Gemfile
cosmetics-web/Gemfile.lock
cosmetics-web/app/helpers/application_helper.rb
cosmetics-web/app/views/notifications/_contact_person_details.html.erb
cosmetics-web/app/views/responsible_persons/show.html.erb
cosmetics-web/spec/features/creating_a_responsible_person_spec.rb
cosmetics-web/spec/features/multiple_responsible_person_spec.rb

As per ticket: https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1179

Improvements to Responsible Person page

---

cosmetics-web/app/views/devise/sessions/new.html.erb
cosmetics-web/spec/features/account/sign_in_spec.rb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-327

Add back button to sign in page

---

cosmetics-web/app/views/notifications/_contact_person_details.html.erb
cosmetics-web/app/views/responsible_persons/show.html.erb
cosmetics-web/spec/features/creating_a_responsible_person_spec.rb
cosmetics-web/spec/support/feature_helpers.rb

- [Prefix RP page title and header with "UK"](https://regulatorydelivery.atlassian.net/browse/COSBETA-1221)
- [Add Business type to RP page (after the address)](https://regulatorydelivery.atlassian.net/browse/COSBETA-1225).

Responsible Person page changes

---

cosmetics-web/app/assets/application/stylesheets/opss/_opss-msa.scss
cosmetics-web/app/assets/application/stylesheets/opss/_opss-shared.scss
cosmetics-web/app/views/poison_centres/notifications/_results.html.erb

Tickets [1123](https://regulatorydelivery.atlassian.net/browse/COSBETA-1223) and [1224](https://regulatorydelivery.atlassian.net/browse/COSBETA-1224)
Bring the latest CSS updates from the prototype project in order to resolve some aligning and wrapping issues.
Replace a CSS class in the Search sort form display.

Update right aligning

---

cosmetics-web/app/forms/registration/new_account_form.rb
cosmetics-web/app/views/registration/new_accounts/new.html.erb
cosmetics-web/config/locales/en.yml
cosmetics-web/spec/features/account/submit_sign_up_spec.rb
cosmetics-web/spec/forms/registration/new_account_form_spec.rb

Follow ups on the anti-spam validation on registration user names.

Improve anti-spam validation on registration user names

---

cosmetics-web/app/views/submit/landing_page/index.html.erb

Remove zip ref in home page as we removed zip file upload feature
https://cosmetics-pr-2269-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2269-search-web.london.cloudapps.digital/

remove zip ref in home page

---

cosmetics-web/app/views/pagination/kaminari/_prev_page.html.erb

[Jira 1267](https://regulatorydelivery.atlassian.net/browse/COSBETA-1267)
- https://cosmetics-pr-2271-submit-web.london.cloudapps.digital/
- https://cosmetics-pr-2271-search-web.london.cloudapps.digital/

Replace "Prev" with "Previous" on pagination

---

cosmetics-web/app/views/responsible_persons/select.html.erb
cosmetics-web/spec/features/multiple_responsible_person_spec.rb

[Jira ticket 1282](https://regulatorydelivery.atlassian.net/browse/COSBETA-1282)
`Change the Responsible Person` instead of `Change Responsible Person`
https://cosmetics-pr-2279-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2279-search-web.london.cloudapps.digital/

Fix Change RP page title

---

cosmetics-web/app/helpers/responsible_persons/notifications_helper.rb

Individual row is a hash, not a hash inside an array.
This caused rendering breaking.

Fix trigger question rendering

---

cosmetics-web/app/assets/application/stylesheets/opss/_opss-msa.scss
cosmetics-web/app/assets/application/stylesheets/opss/_opss-shared.scss
cosmetics-web/app/views/poison_centres/notifications/_filters.html.erb
cosmetics-web/app/views/poison_centres/notifications/_registered_product.html.erb
cosmetics-web/app/views/poison_centres/notifications/_results.html.erb
cosmetics-web/spec/features/notification_search_spec.rb

[Jira ticket 1306](https://regulatorydelivery.atlassian.net/browse/COSBETA-1306)
- Change column layouts on results and filter columns.
- Move from a list of results to a table of results.
- CSS Classes being added/updated.
https://cosmetics-pr-2308-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2308-search-web.london.cloudapps.digital/

Search results page design/styling updates

---

cosmetics-web/app/views/responsible_persons/drafts/_components.html.erb
cosmetics-web/app/views/responsible_persons/drafts/_nanomaterials.html.erb
cosmetics-web/config/routes.rb
cosmetics-web/spec/features/notification_wizard/correct_status.rb

Solves https://regulatorydelivery.atlassian.net/browse/COSBETA-1343 and https://regulatorydelivery.atlassian.net/browse/COSBETA-1344

1343 add links

---

cosmetics-web/app/views/responsible_persons/drafts/_components.html.erb
cosmetics-web/spec/features/notification_wizard/correct_status.rb
cosmetics-web/spec/support/helpers/item_wizard.rb

https://regulatorydelivery.atlassian.net/browse/COSBETA-1364

Dont show add links when its not ready yet

---

cosmetics-web/app/models/component.rb
cosmetics-web/app/views/responsible_persons/wizard/notification_component/contains_poisonous_ingredients.html.erb
cosmetics-web/spec/models/component_spec.rb

https://regulatorydelivery.atlassian.net/browse/COSBETA-1368

1368 avoid preselect of poisonous ingredients when encouneterd for first time

---

cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb
cosmetics-web/app/models/nano_material.rb
cosmetics-web/app/models/notification.rb
cosmetics-web/app/validators/accept_and_submit_validator.rb
cosmetics-web/app/validators/confirm_and_accept_validator.rb
cosmetics-web/app/views/responsible_persons/drafts/show.html.erb
cosmetics-web/app/views/responsible_persons/notifications/edit.html.erb
cosmetics-web/spec/factories/component.rb
cosmetics-web/spec/factories/nano_material.rb
cosmetics-web/spec/features/notification_wizard/correct_status.rb
cosmetics-web/spec/models/notification_spec.rb

https://regulatorydelivery.atlassian.net/browse/COSBETA-1338

1338 assure all nano are included in product

---

cosmetics-web/app/assets/application/stylesheets/opss/_opss-msa.scss
cosmetics-web/app/views/responsible_persons/contact_persons/_edit_field.html.erb
cosmetics-web/app/views/responsible_persons/contact_persons/edit_phone_number.html.erb
cosmetics-web/app/views/responsible_persons/contact_persons/new.html.erb
cosmetics-web/app/views/responsible_persons/edit.html.erb
cosmetics-web/config/locales/en.yml
cosmetics-web/spec/features/account/forgotten_password_spec.rb
cosmetics-web/spec/features/account/sign_in_spec.rb
cosmetics-web/spec/features/account/submit_sign_up_spec.rb
cosmetics-web/spec/features/editing_contact_person_details_spec.rb
cosmetics-web/spec/features/editing_responsible_person_address_spec.rb
cosmetics-web/spec/forms/responsible_persons/invite_member_form_spec.rb
cosmetics-web/spec/forms/sign_in_form_spec.rb
cosmetics-web/spec/models/contact_person_spec.rb
cosmetics-web/spec/support/feature_helpers.rb
cosmetics-web/spec/support/shared_examples/common_user_tests.rb
cosmetics-web/spec/validators/email_validator_spec.rb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1340)
This work adds content changes to the Responsible Person page:
- Edit titles of edit RP pages.
- Replace "phone number" label with "telephone number"
- Change wording for exceptions.
- Modify title, add details toggle and extend warning paragraph for the Edit RP address page.
https://cosmetics-pr-2394-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2394-search-web.london.cloudapps.digital/

UK Responsible Person page: content updates

---

cosmetics-web/app/views/responsible_persons/notifications/edit.html.erb

https://regulatorydelivery.atlassian.net/browse/COSBETA-1414

Dont display Accept and submit button if notification is not submitable

---

cosmetics-web/app/views/responsible_persons/edit.html.erb
cosmetics-web/spec/features/editing_responsible_person_details_spec.rb

- Revert "Change Edit RP details page title
- Tweak form input address line 1 margin
https://cosmetics-pr-2418-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2418-search-web.london.cloudapps.digital/

Edit rp page tweaks

---

cosmetics-web/app/helpers/notification_helper.rb
cosmetics-web/app/helpers/responsible_persons/notifications_helper.rb
cosmetics-web/app/views/notifications/_substances_details.html.erb

https://regulatorydelivery.atlassian.net/browse/COSBETA-1431

Fix bug with displaying nanomaterials

---

cosmetics-web/app/assets/application/stylesheets/opss/_opss-shared.scss
cosmetics-web/app/views/responsible_persons/delete_nano_materials/show.html.erb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1401)
Tiny html/css changes over the delete nanomaterial page.
https://cosmetics-pr-2455-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2455-search-web.london.cloudapps.digital/

Html css changes over nanomaterial to remove page

---

cosmetics-web/app/views/responsible_persons/notifications/components/build/select_nanomaterials.html.erb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1402)
Fixes on the Nanomaterial selection page when building the item task:
- Fixes HTML/CSS through GovUK helpers.
- Fix the broken "Cancel" link not pointing anywhere.
https://cosmetics-pr-2470-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2470-search-web.london.cloudapps.digital/

Fix which nanom in item page

---

cosmetics-web/app/assets/application/stylesheets/opss/_opss-shared.scss
cosmetics-web/app/views/responsible_persons/notifications/nanomaterials/build/add_nanomaterial_name.html.erb
cosmetics-web/app/views/responsible_persons/notifications/nanomaterials/new.html.erb
cosmetics-web/spec/features/notification_wizard/blocked_nano_spec.rb
cosmetics-web/spec/support/helpers/nano_material_wizard.rb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1400)
Use the Gov UK library helpers instead of duplicating the html.
Add appropriate CSS classes to the HTML elements.
Add novalidate to forms.
Add top margin to input fields.
Lowercase button wording.
https://cosmetics-pr-2457-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2457-search-web.london.cloudapps.digital/

Nanomaterial name page html/css changes

---

cosmetics-web/app/helpers/responsible_persons/notifications_helper.rb
cosmetics-web/spec/helpers/responsible_persons/notifications_helper_spec.rb

Some unused code that was causing errors.

Remove unused code

---

cosmetics-web/app/controllers/responsible_persons/delete_items_controller.rb
cosmetics-web/app/views/responsible_persons/drafts/_product_info.html.erb
cosmetics-web/app/views/responsible_persons/drafts/_product_kit.html.erb
cosmetics-web/app/views/responsible_persons/drafts/accept.html.erb
cosmetics-web/app/views/responsible_persons/notifications/components/build/add_component_name.html.erb
cosmetics-web/app/views/responsible_persons/notifications/components/new.html.erb
cosmetics-web/app/views/responsible_persons/notifications/product/single_or_multi_component.html.erb
cosmetics-web/app/views/responsible_persons/notifications/task_completed.html.erb
cosmetics-web/config/locales/en.yml
cosmetics-web/spec/features/notification_wizard/removing_items_spec.rb
cosmetics-web/spec/models/component_spec.rb
cosmetics-web/spec/support/feature_helpers.rb
cosmetics-web/spec/support/helpers/item_wizard.rb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1421)
Multiple frontend changes:
- [Tweak Draft page title sub-text](https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/commit/0398d6e6555b60147af44bcc47f58e0999d6cfee) 
- [Wording changes on items removal](https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/commit/0db286cee895cac86c2655e1e5fa873645d69d2c) 
- [Add dash to Multi-item task title in draft page](https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/commit/bb5e1ac183e5dc1fdcf5c2383ea5a9d238be79a3)
- [Iten name page changes](https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/commit/88a3c4975bdf1f00d0296d711e2f209b7f5a0348) 
- [Change CSS class in Task Completed page.](https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/commit/7fdad5403b4632 …

Front end tweaks and snags

---

cosmetics-web/app/models/nano_element.rb
cosmetics-web/config/locales/en.yml
cosmetics-web/spec/models/nano_element_spec.rb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1436

Add nanomaterial name uniquenes per notification validation

---

cosmetics-web/app/assets/application/stylesheets/opss/_opss-msa.scss
cosmetics-web/app/views/layouts/_cookie_banner.html.erb
cosmetics-web/app/views/responsible_persons/notifications/_incomplete_notifications.html.erb
cosmetics-web/app/views/responsible_persons/notifications/product/single_or_multi_component.html.erb
cosmetics-web/config/environments/development.rb
cosmetics-web/spec/features/notifications_deleting_spec.rb

https://regulatorydelivery.atlassian.net/browse/COSBETA-1489
https://regulatorydelivery.atlassian.net/browse/COSBETA-1491

Frontend fixes

---

cosmetics-web/app/controllers/responsible_persons/notifications/components/build_controller.rb
cosmetics-web/app/views/responsible_persons/notifications/components/build/_exact_concentration.html.erb
cosmetics-web/app/views/responsible_persons/notifications/components/build/_frame_formulation_poisonous_ingredients.html.erb
cosmetics-web/app/views/responsible_persons/notifications/components/build/_ingredients_npis_needs_to_know.html.erb
cosmetics-web/app/views/responsible_persons/notifications/components/build/_poisonous_ingredients.html.erb
cosmetics-web/app/views/responsible_persons/notifications/components/build/_ranges_concentration.html.erb
cosmetics-web/app/views/responsible_persons/notifications/components/build/contains_poisonous_ingredients.html.erb
cosmetics-web/config/locales/en.yml
cosmetics-web/spec/controllers/responsible_persons/notifications/components/build_controller_spec.rb

https://regulatorydelivery.atlassian.net/browse/COSBETA-1502
https://opss-html.herokuapp.com/cosmetics-general/ingredient-NICS-page-redesign

Change wording and appearance

---

cosmetics-web/app/assets/application/stylesheets/opss/_opss-msa.scss
cosmetics-web/app/assets/application/stylesheets/opss/_opss-shared.scss
cosmetics-web/app/views/poison_centres/notifications/_filters.html.erb
cosmetics-web/app/views/poison_centres/notifications/_results.html.erb
cosmetics-web/app/views/poison_centres/notifications/_search_box.html.erb
cosmetics-web/app/views/poison_centres/notifications/index.html.erb
cosmetics-web/app/views/search/landing_page/index.html.erb
cosmetics-web/spec/features/account/creating_a_search_account_from_an_invitation_spec.rb
cosmetics-web/spec/features/account/forgotten_password_spec.rb
cosmetics-web/spec/features/account/locked_account_spec.rb
cosmetics-web/spec/features/account/sign_in_spec.rb
cosmetics-web/spec/features/notification_search_spec.rb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1522

Implement new design of search section

---

cosmetics-web/spec/features/notification_wizard/adding_ingredients_to_components_spec.rb
cosmetics-web/spec/support/feature_helpers.rb
cosmetics-web/spec/support/helpers/item_wizard.rb

Specific feature specs for manually adding:
- Exact concentration ingredients.
- Range concentration ingredients.
- Poisonous ingredients to a predefined formulation product.

Add feature specs to new ingredients flow

---

cosmetics-web/app/controllers/poison_centres/ingredients_search_controller.rb
cosmetics-web/app/forms/ingredient_search_form.rb
cosmetics-web/app/forms/notification_search_form.rb
cosmetics-web/app/helpers/poison_centres_notifications_helper.rb
cosmetics-web/app/models/open_search_query/ingredient.rb
cosmetics-web/app/views/poison_centres/ingredients_search/_filters.html.erb
cosmetics-web/app/views/poison_centres/ingredients_search/_search_box.html.erb
cosmetics-web/spec/features/ingredient_search_spec.rb

https://regulatorydelivery.atlassian.net/browse/COSBETA-1516
Good phrase to test is `sodium metasilicate`, using current seed data.

Exact search

---

.github/workflows/deploy.yml
cosmetics-web/deploy.sh
cosmetics-web/manifest.review.yml
cosmetics-web/manifest.yml

https://trello.com/c/ZnlYY5CO/1376-rate-limit-apps-environments-on-sentry
Prior to this change I have created some additional services, one in the staging space called `cosmetics-staging-sentry-env` and one in the int space called `cosmetics-review-apps-sentry-env` they have the following credentials:
cosmetics-review-apps-sentry-env:
> {
>         "SENTRY_DSN": "https://d938faa7dd4f4fe9b1b87b5cdcd4a48d@o97159.ingest.sentry.io/1398436",
>         "SENTRY_SECURITY_HEADER_ENDPOINT": "https://o97159.ingest.sentry.io/api/1398436/security/?sentry_key=d938faa7dd4f4fe9b1b87b5cdcd4a48d"
> }
> 
cosmetics-staging-sentry-env
> {
>         "SENTRY_CURRENT_ENV": "staging",
>         "SENTRY_DSN": "https://d938faa7dd4f4fe9b1b87b5cdcd4a48d@o97159.ingest.sentry.io/1398436",
> …

Sentry config changes

---

cosmetics-web/app/views/responsible_persons/drafts/guides/_ready_for_components.html.erb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1529)
Now that we have removed the user's ability to upload PDF’s we want to
remove any reference to this in the hint text on the task list page.
https://cosmetics-pr-2537-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2537-search-web.london.cloudapps.digital/

Update task lisk hint text

---

cosmetics-web/app/views/submit/landing_page/index.html.erb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1513

Improve Your cosmetic products button

---

cosmetics-web/app/controllers/responsible_persons_controller.rb
cosmetics-web/spec/features/responsible_person_spec.rb

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1532

Add banner for responsible person change

---

cosmetics-web/app/controllers/responsible_persons/notifications/components/build_controller.rb
cosmetics-web/app/forms/responsible_persons/notifications/ingredient_concentration_form.rb
cosmetics-web/app/helpers/formula_helper.rb
cosmetics-web/app/helpers/ingredient_helper.rb
cosmetics-web/app/helpers/responsible_persons/notifications_helper.rb
cosmetics-web/app/models/component.rb
cosmetics-web/app/models/ingredient.rb
cosmetics-web/app/views/application/_formulation_table.html.erb
cosmetics-web/app/views/notifications/_component_details_formulation_ingredients.html.erb
cosmetics-web/app/views/notifications/_ingredient_details.html.erb
cosmetics-web/app/views/notifications/_trigger_question_details.html.erb
cosmetics-web/app/views/responsible_persons/notifications/_ingredients.html.erb
cosmetics-web/app/views/responsible_persons/notifications/_product_details.html.erb
cosmetics-web/config/locales/en.yml
cosmetics-web/db/migrate/20220714124143_create_ingredient.rb
cosmetics-web/db/schema.rb
cosmetics-web/lib/tasks/ingredients.rake
cosmetics-web/spec/factories/component.rb
cosmetics-web/spec/factories/component_nano_materials.rb
cosmetics-web/spec/factories/ingredient.rb
cosmetics-web/spec/features/notification_wizard/ingredients/editing_ingredients_on_components_spec.rb
cosmetics-web/spec/features/notification_wizard/ingredients/removing_ingredients_from_components_spec.rb
cosmetics-web/spec/forms/responsible_persons/notifications/ingredient_concentration_form_spec.rb
cosmetics-web/spec/helpers/responsible_persons/notifications_helper_spec.rb
cosmetics-web/spec/models/component_spec.rb
cosmetics-web/spec/models/ingredient_spec.rb
cosmetics-web/spec/requests/poison_centre_page_spec.rb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1509)
We're replacing the `ExactFormula` and `RangeFormula` models/DB tables with a single `Ingredient` model.
There is a rake task that will migrate all the valid data from both tables into the new `Ingredient` one. 
**This ticket shouldn't modify the service interface/behaviour.**
The `Ingredient`s are associated with `Component`, and enforces data integrity through validations:
- An ingredient must contain `exact_concentration` or `range_concentration` but cannot have a value in both fields.
- `poisonous` flag only can be set with ingredients that have an `exact_concentration` value.
- An ingredient with `range_concentration` cannot belong to an `exact` or `predefined` component.
- Repeated ingredient names are not …

Unify ingredient model & migrate data

---

cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1507)
When revisiting the notification builder for an already completed task,
prefill the correct data in the Single or Multi component form.

Fix the Single or Multi component prefilling

---

.github/workflows/deploy.yml
.github/workflows/review-apps-delete-dangling.yml
.github/workflows/review-apps-delete.yml
.github/workflows/review-apps.yml
.github/workflows/rubocop.yml
.github/workflows/smoke_test.yml
.github/workflows/tests.yml
cosmetics-web/app/models/concerns/searchable.rb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1557)
- Upgrade Postgres to v13.6 in Github workflows to match with the Postgres version running in review apps and
production environments.
- Migrate away from deprecated action to set up Ruby.
- Upgrade actions to their latest versions.
- Split Rspec in two parallel running jobs (one for feature specs and one for the rest), moving from 8-11 minutes test runs to 4-5 minutes.
- Fix bug in workflow for deleting dangling review apps.
- Do not attempt to create/delete PR for PRs initiated by Dependabot. Since they will fail, better to skip them.

Github workflows upgrades

---

cosmetics-web/app/views/responsible_persons/notifications/new.html.erb
cosmetics-web/app/views/responsible_persons/notifications/product/_add_product_name_form.html.erb
cosmetics-web/app/views/responsible_persons/notifications/product/add_product_name.html.erb
cosmetics-web/app/views/submit/landing_page/index.html.erb
cosmetics-web/spec/support/feature_helpers.rb

Tickets: [1536](https://regulatorydelivery.atlassian.net/browse/COSBETA-1536) and [1537](https://regulatorydelivery.atlassian.net/browse/COSBETA-1537)
- Replace the "Add Product" page title wording
- Fix typo on "trademark" wording.
- Add HTML mark-up on the landing page warning text.
https://cosmetics-pr-2576-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2576-search-web.london.cloudapps.digital/

Html wording tweaks

---

cosmetics-web/Gemfile
cosmetics-web/Gemfile.lock
cosmetics-web/package.json
cosmetics-web/yarn.lock

It brings us the latest changes in GovUK Frontend v4.3.1
Big thanks to @stdstaff for his work on this :clap:

Upgrade GovUK Design System Rails gem to v0.9.3

---

cosmetics-web/app/views/nanomaterial_notifications/confirmation_page.html.erb
cosmetics-web/spec/features/nanomaterial_notifications_spec.rb
cosmetics-web/spec/requests/nanomaterial_notifications_spec.rb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1543)
Small tweaks on confirmation page text display: 
https://cosmetics-pr-2579-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2579-search-web.london.cloudapps.digital/

Nanomaterial notification confirmation page changes

---

cosmetics-web/app/controllers/poison_centres/ingredients_search_controller.rb
cosmetics-web/app/forms/ingredient_search_form.rb
cosmetics-web/app/helpers/poison_centres_notifications_helper.rb
cosmetics-web/app/models/notification.rb
cosmetics-web/app/models/open_search_query/ingredient.rb
cosmetics-web/app/views/poison_centres/ingredients/index.html.erb
cosmetics-web/app/views/poison_centres/ingredients_search/_filters.html.erb
cosmetics-web/app/views/poison_centres/ingredients_search/_result_row.html.erb
cosmetics-web/app/views/poison_centres/ingredients_search/_results.html.erb
cosmetics-web/app/views/poison_centres/notifications_search/_result_row.html.erb
cosmetics-web/app/views/poison_centres/notifications_search/_results.html.erb
cosmetics-web/db/seeds.rb
cosmetics-web/spec/models/open_search_query/ingredients_spec.rb

Add filter to order by Responsible Person

---

cosmetics-web/app/views/poison_centres/shared/_secondary_navigation.html.erb
cosmetics-web/spec/features/ingredients_list_spec.rb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1603)
Disable it temporally for October 3 launch.

Disable the ingredients list link

---

cosmetics-web/app/views/layouts/application.html.erb
cosmetics-web/app/views/search/landing_page/index.html.erb
cosmetics-web/app/views/submit/landing_page/index.html.erb

As the banners alert about the incoming new feature and we are bringing the feature, it is the right time to remove the alert.

Remove ingredients incoming feature banners

---

cosmetics-web/spec/smoke/search_smoke_test_spec.rb

Forgot to replace text on previous PR :facepalm: https://github.com/OfficeForProductSafetyAndStandards/cosmetic-product-notifications/pull/2615

Fix smoke test wording left out from previous fix

---

cosmetics-web/app/assets/application/javascripts/notification_search.js
cosmetics-web/app/assets/application/stylesheets/opss/_opss-shared.scss
cosmetics-web/app/helpers/poison_centres_notifications_helper.rb
cosmetics-web/app/views/poison_centres/ingredients_search/_filters.html.erb
cosmetics-web/app/views/poison_centres/notifications_search/_filters.html.erb
cosmetics-web/app/views/poison_centres/notifications_search/_results.html.erb
cosmetics-web/app/views/poison_centres/notifications_search/_search_box.html.erb
cosmetics-web/app/views/poison_centres/notifications_search/show.html.erb
cosmetics-web/db/schema.rb
cosmetics-web/spec/features/account/creating_a_search_account_from_an_invitation_spec.rb
cosmetics-web/spec/features/account/forgotten_password_spec.rb
cosmetics-web/spec/features/account/locked_account_spec.rb
cosmetics-web/spec/features/account/sign_in_spec.rb
cosmetics-web/spec/features/ingredient_search_spec.rb
cosmetics-web/spec/features/ingredients_list_spec.rb
cosmetics-web/spec/features/notification_search_spec.rb

Fixes reset filter and rearrange advanced search options
https://regulatorydelivery.atlassian.net/browse/COSBETA-1604

Search frontend improvements

---

.gitignore
cosmetics-web/.gitignore
cosmetics-web/app/assets/application/stylesheets/navbar.scss
cosmetics-web/app/controllers/responsible_persons_controller.rb
cosmetics-web/app/views/layouts/_header.html.erb
cosmetics-web/app/views/layouts/_navbar.html.erb
cosmetics-web/config/routes.rb
cosmetics-web/db/schema.rb

https://regulatorydelivery.atlassian.net/browse/COSBETA-1588
Updates to the main header. Added in a products-redirect on the responsible persons controller to use the concern to get a current responsible person. This ensures the nav works correctly when visiting a shared controller (My Account) without exposing the responsible person to search.

Updates to navigation and URLs within the main header

---

cosmetics-web/app/views/poison_centres/ingredients/index.html.erb
cosmetics-web/app/views/poison_centres/ingredients_search/_results.html.erb
cosmetics-web/app/views/poison_centres/shared/_secondary_navigation.html.erb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1570)
Disable  the ingredients list before merging this PR. (done)
https://cosmetics-pr-2671-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2671-search-web.london.cloudapps.digital/

Change hardcoded date info on ingredients search list

---

cosmetics-web/app/views/search/landing_page/index.html.erb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1710)
Add 'ingredient'  to the list of attributes users can use to search for products.
https://cosmetics-pr-2714-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2714-search-web.london.cloudapps.digital/

Add 'ingredient' to search landing page wording

---

cosmetics-web/app/views/responsible_persons/notifications/components/build/_ingredient_exact_concentration_fields.html.erb
cosmetics-web/app/views/responsible_persons/notifications/components/build/add_cmrs.html.erb
cosmetics-web/app/views/responsible_persons/notifications/components/build/add_ingredient_range_concentration.html.erb

Small change to use HTML option for gove input label rather than text.

Added (optional) to CAS number label

---

cosmetics-web/app/models/concerns/searchable.rb

This displays proper number of results.

Add track_total_hits parameter to reveal total number of notifications

---

cosmetics-web/app/views/responsible_persons/notifications/components/build/_add_ingredient_concentration.html.erb
cosmetics-web/app/views/responsible_persons/notifications/components/build/select_frame_formulation.html.erb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1677)
Small changes on the ingredient pages:
- Add warning text to the "select frame formulation" page.
- Add a sentence to the secondary ingredient concentration text.
https://cosmetics-pr-2731-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2731-search-web.london.cloudapps.digital/

Changes to ingredients pages

---

cosmetics-web/app/models/open_search_query/ingredient.rb
cosmetics-web/spec/models/open_search_query/ingredients_spec.rb

[Jira ticket 1667](https://regulatorydelivery.atlassian.net/browse/COSBETA-1667)
When searching by ingredients in the Cosmetics Search and Submit portals, the results will be limited to notifications submitted after the introduction of manual ingredients for the notifications (2022-10-03).
https://cosmetics-pr-2737-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2737-search-web.london.cloudapps.digital/

Set minimum date for Search ingredients results

---

cosmetics-web/app/assets/application/stylesheets/opss/_opss-shared.scss
cosmetics-web/app/jobs/postgres_csv_upload_job.rb
cosmetics-web/app/jobs/upload_cosmetic_products_containing_nanomaterials_job.rb
cosmetics-web/app/jobs/upload_cosmetic_products_in_last_three_months_containing_nanomaterials_job.rb
cosmetics-web/app/jobs/upload_nanomaterial_notifications_in_last_three_months_job.rb
cosmetics-web/app/jobs/upload_nanomaterial_notifications_job.rb
cosmetics-web/app/jobs/upload_nanomaterials_pdfs_abstract_job.rb
cosmetics-web/app/jobs/upload_nanomaterials_pdfs_in_last_three_months_job.rb
cosmetics-web/app/jobs/upload_nanomaterials_pdfs_job.rb
cosmetics-web/app/views/my_account/_opss_science_downloads.html.erb
cosmetics-web/app/views/my_account/show.html.erb
cosmetics-web/config/initializers/sidekiq.rb
cosmetics-web/spec/jobs/upload_cosmetic_products_in_last_three_months_containing_nanomaterials_job_spec.rb
cosmetics-web/spec/jobs/upload_nanomaterial_notifications_in_last_three_months_job_spec.rb
cosmetics-web/spec/jobs/upload_nanomaterials_pdfs_in_last_three_months_job_spec.rb

[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1659)
We currently provide 3 reports to the OPSS science team:
- Cosmetics products containing nanomaterials.
- All nanomaterial notifications.
- All PDFs for nanomaterial notifications.
We are creating a version on each of these files that will contain a subset from 3 months before the start of the current month up to the date when the job is executed.
These documents will be provided just below the "all results" versions.
https://cosmetics-pr-2740-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2740-search-web.london.cloudapps.digital/

Add "last 3 months" version of the science reports

---

cosmetics-web/app/views/poison_centres/notifications/show_poison_centre.html.erb

JIRA ticket: https://regulatorydelivery.atlassian.net/browse/COSBETA-989
Add alt text, title attribute and “open in new tab” to product images.
https://cosmetics-pr-2749-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2749-search-web.london.cloudapps.digital/

Improve product images

---

cosmetics-web/app/controllers/poison_centres/ingredients_controller.rb
cosmetics-web/app/helpers/privileges_helper.rb
cosmetics-web/app/models/concerns/privileges/abstract_concern.rb
cosmetics-web/app/models/concerns/privileges/search_concern.rb
cosmetics-web/app/models/concerns/privileges/submit_concern.rb
cosmetics-web/app/views/poison_centres/shared/_secondary_navigation.html.erb
cosmetics-web/spec/models/search_user_spec.rb

JIRA link: https://regulatorydelivery.atlassian.net/browse/COSBETA-1736
Enables a link to the ingredients list page.
https://cosmetics-pr-2756-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2756-search-web.london.cloudapps.digital/

Enable ingredients list

---

cosmetics-web/app/views/layouts/_navbar.html.erb

JIRA link: https://regulatorydelivery.atlassian.net/browse/COSBETA-1788
Fixes the top level navigation on the submit domain to show “cosmetic products” as the current page when visiting “draft notifications”, “product - search” or “ingredient - search”.

Fix top-level navigation on submit

---

cosmetics-web/app/models/concerns/new_email_concern.rb
cosmetics-web/app/models/search_user.rb
cosmetics-web/app/models/submit_user.rb
cosmetics-web/app/models/user.rb

This PR refactors the Devise definitions/overridden methods in our user's models by:
- Commenting each of the Devise's overridden methods pointing to its original definitions for easier identification.
- Moving all the shared code to the parent `User` model, keeping in `Submit/SearchUser` only the code that diverges.
- Adjust Devise overridden methods privacy to match, when possible, the one from their original Devise definitions.
https://cosmetics-pr-2791-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2791-search-web.london.cloudapps.digital/

Refactor Devise User's code

---

cosmetics-web/Gemfile
cosmetics-web/Gemfile.lock

So we always have the latest version on development.

Unpin Solargraph gem version

---

cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
cosmetics-web/app/models/notification.rb
cosmetics-web/app/views/shared/_multiple_images_upload_description.html.erb
cosmetics-web/spec/models/notification_spec.rb

JIRA ticket: https://regulatorydelivery.atlassian.net/browse/COSBETA-1809
* For multi-item products, show more information on what images are required
* Enforce a maximum of 10 attached images and show an error message if it is exceeded
https://cosmetics-pr-2795-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2795-search-web.london.cloudapps.digital/

Update image upload help text

---

cosmetics-web/app/models/notification.rb
cosmetics-web/app/models/open_search_query/notification.rb
cosmetics-web/app/views/responsible_persons/search_notifications/_search_form.html.erb
cosmetics-web/spec/features/submit/responsible_person/search_notifications_spec.rb

JIRA ticket: https://regulatorydelivery.atlassian.net/browse/COSBETA-1806
Adds the ability to search product notifications by internal reference.
https://cosmetics-pr-2809-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2809-search-web.london.cloudapps.digital/

Enable search by internal reference

---

cosmetics-web/app/assets/javascripts/autocomplete.js
cosmetics-web/app/assets/javascripts/bulk_file_upload_error_handling.js
cosmetics-web/app/assets/javascripts/form_reset.js
cosmetics-web/app/assets/javascripts/image_size_validation.js
cosmetics-web/app/assets/javascripts/location_picker.js
cosmetics-web/app/assets/javascripts/notification_search.js
cosmetics-web/app/assets/javascripts/upload_handlers.js
cosmetics-web/package.json
cosmetics-web/yarn.lock

JIRA ticket: https://regulatorydelivery.atlassian.net/browse/COSBETA-1846
Removes the dependency on jQuery and tweaks some syntax.
Also removes code that hides form validation errors on reset to match search domain.
https://cosmetics-pr-2824-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2824-search-web.london.cloudapps.digital/

Remove jQuery

---

docker-compose.yml

Removes the Kibana instance installed locally since it is not used.
https://regulatorydelivery.atlassian.net/browse/COSBETA-1937
N/A
https://cosmetics-pr-2908-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2908-search-web.london.cloudapps.digital/
No

Remove local Kibana instance

---

cosmetics-web/Gemfile.lock

Keeps local Gemfile.lock up to date with local development platform.

Update Gemfile.lock with local development platform

---

cosmetics-web/app/views/responsible_persons/notifications/nanomaterials/build/when_products_containing_nanomaterial_can_be_placed_on_market.html.erb

Update nanomaterial help text:
"When can you place products containing nanomaterials on the market"
https://regulatorydelivery.atlassian.net/browse/COSBETA-1767
https://cosmetics-pr-2952-submit-web.london.cloudapps.digital/

Update nanomaterial help text

---

cosmetics-web/app/views/guidance/how_to_notify_nanomaterials.html.erb

COSBETA-1768
Update link to UK Annex
https://regulatorydelivery.atlassian.net/browse/COSBETA-1768
https://cosmetics-pr-2953-submit-web.london.cloudapps.digital/

Nanomaterials - replace with UK annexes

---

cosmetics-web/app/models/gov_uk/date_from_form.rb
cosmetics-web/app/views/my_account/_opss_science_downloads.html.erb
cosmetics-web/spec/factories/pending_responsible_person_users.rb
cosmetics-web/spec/jobs/upload_nanomaterial_notifications_job_spec.rb
cosmetics-web/spec/requests/responsible_persons/edit_details_spec.rb
cosmetics-web/spec/requests/user_account_page_spec.rb
cosmetics-web/spec/services/notification_delete_service_spec.rb
cosmetics-web/spec/services/update_responsible_person_details_spec.rb
cosmetics-web/spec/support/analyzers.rb

Here we remove some rubocop exceptions. It covers all the production code but not:
- migration files 
- some of the gnarlier specs
https://regulatorydelivery.atlassian.net/browse/COSBETA-1945

Resolve rubocop exceptions

---

cosmetics-web/app/controllers/responsible_persons/notifications/components/build_controller.rb
cosmetics-web/spec/features/submit/notification_wizard/ingredients/adding_ingredients_to_components_spec.rb
cosmetics-web/spec/features/submit/notification_wizard/shades_spec.rb
cosmetics-web/spec/support/feature_helpers.rb

Change the back button target page for the Ingredients and Shades sections of the journey
https://regulatorydelivery.atlassian.net/browse/COSBETA-2016
https://cosmetics-pr-2971-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2971-search-web.london.cloudapps.digital/

Screen navigation using back button

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/deploy.yml
.github/workflows/erd.yml
.github/workflows/smoke_test.yml
.github/workflows/tests.yml
README.md
cosmetics-web/.env.development.example
cosmetics-web/.env.test.example
cosmetics-web/app/controllers/concerns/domain_concern.rb
cosmetics-web/app/helpers/domain_helper.rb
cosmetics-web/app/mailers/notify_mailer.rb
cosmetics-web/bin/production-maintenance-mode
cosmetics-web/config/application.rb
cosmetics-web/config/constants/domains_allowing_otp_whitelisting.yml
cosmetics-web/config/environments/development.rb
cosmetics-web/config/initializers/notify_mailer.rb
cosmetics-web/deploy-review.sh
cosmetics-web/deploy.sh
cosmetics-web/docs/getting_started.md
cosmetics-web/docs/review_apps.md
cosmetics-web/docs/secondary_authentication.md
cosmetics-web/docs/users_and_roles.md
cosmetics-web/lib/cookie_domain_cleaner.rb
cosmetics-web/manifest.review.yml
cosmetics-web/manifest.yml
cosmetics-web/spec/domain_helpers.rb
cosmetics-web/spec/features/account/forgotten_password_spec.rb
cosmetics-web/spec/features/account/locked_account_spec.rb
docker-compose.yml

Adds the new support host to all GitHub Actions and the app.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2079
N/A
https://cosmetics-pr-2978-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2978-search-web.london.cloudapps.digital/
https://cosmetics-pr-2978-support-web.london.cloudapps.digital/

OSU Support Portal: add to GitHub Actions and app

---

cosmetics-web/support_portal/app/assets/stylesheets/support_portal/application.scss
cosmetics-web/support_portal/app/views/layouts/support_portal/application.html.erb
cosmetics-web/support_portal/app/views/support_portal/dashboard/index.html.erb

Adds a non-functioning dashboard page which will be populated as each section is created.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2040
https://cosmetics-pr-2981-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2981-search-web.london.cloudapps.digital/
https://cosmetics-pr-2981-support-web.london.cloudapps.digital/
No

OSU Support Portal: add dashboard page

---

cosmetics-web/app/validators/user_name_format_validator.rb
cosmetics-web/spec/validators/user_name_format_validator_spec.rb

Adds the following prohibited characters:
!, “, £, $, %, ^, &, *, (, ), _, +,¬
https://regulatorydelivery.atlassian.net/browse/COSBETA-2057
https://cosmetics-pr-2984-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2984-search-web.london.cloudapps.digital/

Extend user#name validations

---

cosmetics-web/config/locales/en.yml

- ingredient_concentration_form has been removed from the app
- with_range_concentration is no longer referenced
https://regulatorydelivery.atlassian.net/browse/COSBETA-2102

Remove deprecated translations

---

cosmetics-web/app/views/nanomaterial_notifications/index.html.erb

Updates the information text for nanomaterials and provides a link to the checklist.
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2103
https://cosmetics-pr-3004-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3004-search-web.london.cloudapps.digital/
https://cosmetics-pr-3004-support-web.london.cloudapps.digital/

update advice text for nanomaterials page

---

cosmetics-web/app/forms/responsible_persons/notifications/components/bulk_ingredient_upload_form.rb
cosmetics-web/spec/fixtures/files/exact_ingredients_long_name.csv
cosmetics-web/spec/forms/responsible_persons/notifications/components/bulk_ingredient_upload_form_spec.rb

To allow users to successfully upload their CSV files, we have agreed to remove certain consistent issues they were experiencing in the upload process:
- Fields do not start or end with extra spaces
- Ignore blank rows
https://regulatorydelivery.atlassian.net/browse/COSBETA-2113
https://cosmetics-pr-3006-submit-web.london.cloudapps.digital/

CSV Uploads - Remove validations on file upload

---

cosmetics-web/db/seeds.rb

Expands the user seeding to also create search and support seed users for each person.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2152
N/A
https://cosmetics-pr-3020-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3020-search-web.london.cloudapps.digital/
https://cosmetics-pr-3020-support-web.london.cloudapps.digital/
No

Create search and support seed users

---

cosmetics-web/app/views/responsible_persons/notifications/product/_instructions.html.erb

Minor change to first paragraph on image upload page
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2119
https://cosmetics-pr-3029-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3029-search-web.london.cloudapps.digital/
https://cosmetics-pr-3029-support-web.london.cloudapps.digital/

update image upload page content

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
cosmetics-web/config/scout_apm.yml
cosmetics-web/docs/deployment.md

[Ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1916)
This separates out the deployment pipelines as follows:
- On push to `develop` triggers a deployment to `staging`
- On push to `main` it triggers a deployment to `pre-prod` and `production`

Added deployments for staging, pre-prod and production

---

cosmetics-web/app/views/responsible_persons/notifications/components/build/select_formulation_type.html.erb
cosmetics-web/config/locales/en.yml
cosmetics-web/spec/controllers/responsible_persons/notifications/components/build_controller_spec.rb
cosmetics-web/spec/features/account/change_name_spec.rb
cosmetics-web/spec/features/submit/responsible_person/contact_person_details_edition_spec.rb
cosmetics-web/spec/features/support/account_administration_spec.rb
cosmetics-web/spec/features/support/responsible_persons_spec.rb
cosmetics-web/spec/forms/secondary_authentication/app/setup_form_spec.rb
cosmetics-web/spec/forms/secondary_authentication/sms/setup_form_spec.rb
cosmetics-web/spec/models/component_spec.rb
cosmetics-web/spec/models/contact_person_spec.rb
cosmetics-web/spec/models/responsible_person_address_log_spec.rb
cosmetics-web/spec/models/responsible_person_spec.rb
cosmetics-web/spec/support/shared_examples/common_user_tests.rb
cosmetics-web/support_portal/app/controllers/support_portal/responsible_persons_controller.rb
cosmetics-web/support_portal/app/helpers/support_portal/responsible_persons_helper.rb
cosmetics-web/support_portal/app/views/support_portal/dashboard/index.html.erb
cosmetics-web/support_portal/app/views/support_portal/responsible_persons/_search_box.html.erb
cosmetics-web/support_portal/app/views/support_portal/responsible_persons/_search_results.html.erb
cosmetics-web/support_portal/app/views/support_portal/responsible_persons/edit_address.html.erb
cosmetics-web/support_portal/app/views/support_portal/responsible_persons/edit_assigned_contact_email.html.erb
cosmetics-web/support_portal/app/views/support_portal/responsible_persons/edit_assigned_contact_name.html.erb
cosmetics-web/support_portal/app/views/support_portal/responsible_persons/edit_assigned_contact_phone_number.html.erb
cosmetics-web/support_portal/app/views/support_portal/responsible_persons/edit_business_type.html.erb
cosmetics-web/support_portal/app/views/support_portal/responsible_persons/edit_name.html.erb
cosmetics-web/support_portal/app/views/support_portal/responsible_persons/index.html.erb
cosmetics-web/support_portal/app/views/support_portal/responsible_persons/show.html.erb
cosmetics-web/support_portal/config/routes.rb

Adds functionality to search for and manage Responsible Persons and assigned contacts.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2074, https://regulatorydelivery.atlassian.net/browse/COSBETA-2075, https://regulatorydelivery.atlassian.net/browse/COSBETA-2078, https://regulatorydelivery.atlassian.net/browse/COSBETA-2080, https://regulatorydelivery.atlassian.net/browse/COSBETA-2084, https://regulatorydelivery.atlassian.net/browse/COSBETA-2085, https://regulatorydelivery.atlassian.net/browse/COSBETA-2086, https://regulatorydelivery.atlassian.net/browse/COSBETA-2087, https://regulatorydelivery.atlassian.net/browse/COSBETA-2088
https://cosmetics-pr-3011-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3011-search-web.london.cloudapps.digital/ …

OSU Support Portal: manage Responsible Persons

---

cosmetics-web/app/models/secondary_authentication/otp_whitelisting.rb
cosmetics-web/manifest.yml

Adds cosmetics-devise-env to the manifest and removes the maximum of two allowed uris for whitelisting

add whitelisting service for staging

---

cosmetics-web/app/forms/responsible_persons/notifications/components/bulk_ingredient_upload_form.rb
cosmetics-web/spec/forms/responsible_persons/notifications/components/bulk_ingredient_upload_form_spec.rb

Skip blank rows on bulk upload CSV and strip out extraneous whitespace.
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2113
https://cosmetics-pr-3069-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3069-search-web.london.cloudapps.digital/
https://cosmetics-pr-3069-support-web.london.cloudapps.digital/

strip leading and lagging white space and skip blanks

---

cosmetics-web/app/controllers/my_account/email_controller.rb
cosmetics-web/app/views/my_account/show.html.erb
cosmetics-web/spec/features/account/change_email_spec.rb

Adds ability for user to change email address
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2136
https://cosmetics-pr-3072-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3072-search-web.london.cloudapps.digital/
https://cosmetics-pr-3072-support-web.london.cloudapps.digital/

allow support users to change email address

---

cosmetics-web/app/views/errors/internal_server_error.html.erb

Updates the wording of the internal server error page to provide a contact email address.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2175
https://cosmetics-pr-3085-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3085-search-web.london.cloudapps.digital/
https://cosmetics-pr-3085-support-web.london.cloudapps.digital/
No

Update internal server error page

---

cosmetics-web/app/views/help/accessibility_statement.html.erb

Updates the accessibility statement with new information.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2207
N/A
https://cosmetics-pr-3092-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3092-search-web.london.cloudapps.digital/
https://cosmetics-pr-3092-support-web.london.cloudapps.digital/
No

Update accessibility statement

---

cosmetics-web/app/views/my_account/show.html.erb
cosmetics-web/spec/features/support/invite_support_user_spec.rb

Change the capitalisation on User management on the support user dashboard
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2110
https://cosmetics-pr-3102-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3102-search-web.london.cloudapps.digital/
https://cosmetics-pr-3102-support-web.london.cloudapps.digital/

change capitalisation on User management

---

cosmetics-web/support_portal/app/assets/stylesheets/support_portal/_sortable_table.scss
cosmetics-web/support_portal/app/assets/stylesheets/support_portal/application.scss
cosmetics-web/support_portal/app/controllers/support_portal/history_controller.rb
cosmetics-web/support_portal/app/helpers/support_portal/history_helper.rb
cosmetics-web/support_portal/app/models/support_portal/history_search.rb
cosmetics-web/support_portal/app/services/support_portal/find_support_user_changes.rb
cosmetics-web/support_portal/app/views/support_portal/history/index.html.erb

Add sortable component to history table
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2150
https://cosmetics-pr-3094-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3094-search-web.london.cloudapps.digital/
https://cosmetics-pr-3094-support-web.london.cloudapps.digital/

add sorting component to support

---

cosmetics-web/support_portal/app/views/support_portal/invite_support_users/new.html.erb

Updates the bullet points on the “invite a team member” page.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2219
https://cosmetics-pr-3116-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3116-search-web.london.cloudapps.digital/
https://cosmetics-pr-3116-support-web.london.cloudapps.digital/
No

OSU Support Portal: update text on invite a team member page

---

cosmetics-web/spec/features/support/history_spec.rb

Fix OSU Support Portal history tests
N/A
N/A
https://cosmetics-pr-3136-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3136-search-web.london.cloudapps.digital/
https://cosmetics-pr-3136-support-web.london.cloudapps.digital/
No

Fix OSU Support Portal history tests

---

cosmetics-web/app/controllers/my_account_controller.rb
cosmetics-web/app/views/my_account/show.html.erb
cosmetics-web/spec/features/account/change_email_spec.rb
cosmetics-web/spec/features/account/change_name_spec.rb
cosmetics-web/spec/features/account/change_password_spec.rb

Adds a back link to account page for users
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2165
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2166
https://cosmetics-pr-3132-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3132-search-web.london.cloudapps.digital/
https://cosmetics-pr-3132-support-web.london.cloudapps.digital/

add back link to my account page

---

cosmetics-web/Gemfile.lock

This reverts commit 81659f2c5bd06392be0da67a77b405908d912413.

Revert "Bump puma from 6.3.0 to 6.3.1 in /cosmetics-web (#3120)"

---

.github/workflows/deploy-staging.yml

Remotely triggers the automated test framework after new code is deployed to staging,
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2276

add remote workflow run to post staging deploy

---

.github/workflows/deploy-staging.yml

fix YAML linting

---

cosmetics-web/app/views/responsible_persons/show.html.erb

Adds a new sentence of copy to Responsible Person page
https://regulatorydelivery.atlassian.net/browse/COSBETA-2275
before
after
https://cosmetics-pr-3157-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3157-search-web.london.cloudapps.digital/
https://cosmetics-pr-3157-support-web.london.cloudapps.digital/

Responsible person copy change - COSBETA-2275

---

cosmetics-web/support_portal/app/views/support_portal/account_administration/reset_account.html.erb

Adds a fullstop in copy on the support portal
COSBETA-2249

add fullstop at the end of the sentence - COSBETA-2249

---

cosmetics-web/app/forms/responsible_persons/notifications/components/bulk_ingredient_upload_form.rb
cosmetics-web/spec/fixtures/files/exact_ingredients.csv
cosmetics-web/spec/fixtures/files/exact_ingredients_duplicate_row.csv
cosmetics-web/spec/fixtures/files/exact_ingredients_long_name.csv
cosmetics-web/spec/fixtures/files/exact_ingredients_with_shades.csv
cosmetics-web/spec/fixtures/files/range_ingredients.csv
cosmetics-web/spec/forms/responsible_persons/notifications/components/bulk_ingredient_upload_form_spec.rb

Change headers on template CSVs to match what. bulk uploader is expecting.
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2286
https://cosmetics-pr-3192-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3192-search-web.london.cloudapps.digital/
https://cosmetics-pr-3192-support-web.london.cloudapps.digital/

fix headers on template CSVs

---

cosmetics-web/app/views/submit/landing_page/index.html.erb

Add sentence to landing page to indicate that it's for the submit service.
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2269
https://cosmetics-pr-3188-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3188-search-web.london.cloudapps.digital/
https://cosmetics-pr-3188-support-web.london.cloudapps.digital/

add sentence to landing  page

---

cosmetics-web/app/views/help/csv.html.erb
cosmetics-web/app/views/responsible_persons/notifications/components/build/add_ingredients/_instructions.html.erb

Adds to the ingredient guidance regarding CAS numbers.
https://regulatorydelivery.atlassian.net/browse/PSD-2108
N/A
https://cosmetics-pr-3202-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3202-search-web.london.cloudapps.digital/
https://cosmetics-pr-3202-support-web.london.cloudapps.digital/

Update ingredient guidance

---

cosmetics-web/app/controllers/responsible_persons/delete_notification_controller.rb
cosmetics-web/app/models/notification.rb
cosmetics-web/app/views/poison_centres/notifications/_notification_history.html.erb
cosmetics-web/app/views/responsible_persons/notifications/_show.html.erb

Fixes notification deletion history to correctly record deletions by submit users and also display their names correctly.
https://regulatorydelivery.atlassian.net/browse/PSD-2111

Fix notification deletion history

---

cosmetics-web/config/initializers/devise.rb
cosmetics-web/spec/features/account/forgotten_password_spec.rb

Updated password reset time to 72 hours
https://regulatorydelivery.atlassian.net/browse/PSD-2413
n/a

Updated password reset time to 72 hours

---

cosmetics-web/spec/smoke/search_smoke_test_spec.rb

Fix smoke test
https://regulatorydelivery.atlassian.net/browse/PSD-2424
N/A
https://cosmetics-pr-3265-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3265-search-web.london.cloudapps.digital/
https://cosmetics-pr-3265-support-web.london.cloudapps.digital/

Fix smoke test

---

cosmetics-web/db/seeds.rb

We were getting errors with trying to reset the DB to test code. So I have refactored the seeds file.

fix/PSD-2648 Update to the seeds file

---

cosmetics-web/app/helpers/draft_helper.rb
cosmetics-web/spec/helpers/draft_helper_spec.rb

fixed the Sentry issue on the component being nil, which was eventually throwing Nil class error

[PSD-2554] - handled the sentry issue -  Nil class error

---

cosmetics-web/app/graphql/types/component_nano_material_queries.rb
cosmetics-web/app/graphql/types/component_nano_material_type.rb
cosmetics-web/app/graphql/types/nano_material_queries.rb
cosmetics-web/app/graphql/types/nano_material_type.rb
cosmetics-web/app/graphql/types/nanomaterial_notification_queries.rb
cosmetics-web/app/graphql/types/nanomaterial_notification_type.rb
cosmetics-web/app/graphql/types/query_type.rb
cosmetics-web/spec/graphql/types/component_nano_material_queries_spec.rb
cosmetics-web/spec/graphql/types/nano_material_queries_spec.rb
cosmetics-web/spec/graphql/types/nanomaterial_notification_queries_spec.rb

Adding in GraphQL to the SCPN project. This PR sets up GraphQL in the project, adds in the API Key functionality and hides it behind a flipper flag.
- component_nano_material
- nano_material
- nanomaterial_notification_queries

feature/PSD-3137-add_graphql - Nano material queries

---

.github/workflows/rubocop.yml
.github/workflows/smoke_test.yml
.github/workflows/tests.yml
cosmetics-web/Gemfile.lock

Part of the updates to the code base I have updated bundler to a newer version.

chore/update_manifest_file - bundler update

---

.github/workflows/deploy-staging.yml

More updates to the deployment file.

chore/staging_issues - staging deployment updates.

---

.github/workflows/deploy-staging.yml

Trying some other deployment tasks.

chore/staging_issues - More updates to the staging deployment

---

.github/workflows/deploy-production.yml

Update to the production deployment workflow

chore/staging_issues - Update to production deployment

---

cosmetics-web/app/graphql/cosmetics_schema.rb
cosmetics-web/app/graphql/types/component_queries.rb
cosmetics-web/app/graphql/types/custom_date_time_type.rb
cosmetics-web/app/graphql/types/search_history_type.rb
cosmetics-web/config/initializers/devise.rb

- Updates to `component_queries` and `search_history_type.rb`. 
- Adding in max depth. 
Also updated the devise initialiser removing the comments for easier updating.

feature/PSD-3137-add_graphql - Update to queries

---

cosmetics-web/docs/deployment.md
cosmetics-web/manifest.review.yml
cosmetics-web/manifest.yml

Removing basic Auth from deployments as it keeps being added when its not needed.

remove basic auth

---

.github/workflows/deploy-staging.yml

Update to the staging deployment to see if this fixes the deployment issues.

Update to the GH actions for deployment - Staging

---

.github/workflows/deploy-production.yml

Update to the prod deployment to fix the deployment issues.

fix/PSD-4245-deployment_issues - production

---

cosmetics-web/lib/tasks/map_legacy_roles_to_rolify.rake

Noticed some other issues when migrating the users previous roles and types over to rolify. This was something we couldn't foresee due to the data in production.

PSD-4554 - Update to the task, and add new migration

---

cosmetics-web/lib/tasks/map_legacy_roles_to_rolify.rake

Further updates for the issues noticed when migrating the users previous roles and types over to rolify. This was something we couldn't foresee due to the data in production.

PSD-4522 - Update to the role migration task

---

cosmetics-web/app/controllers/concerns/active_storage_access_protection_concern.rb
cosmetics-web/db/seeds.rb

Updated the seeds file to work with the new setup, and applied some fixes to an issue QA found.

PSD-4591 - Update to the seeds file, and QA fixes

---

cosmetics-web/app/controllers/concerns/active_storage_access_protection_concern.rb
cosmetics-web/app/controllers/errors_controller.rb

Update code for rouge role leftover from the role updates.

PSD-4617 - Update code for rouge role leftover

---

cosmetics-web/app/forms/registration/new_account_form.rb
cosmetics-web/app/services/invite_search_user.rb

Fix for roles not being assigned to SeachUsers when they are created.

PSD-4621 - Fix for roles not being assigned to SeachUsers

---

cosmetics-web/app/controllers/pingdom/check_controller.rb
cosmetics-web/config/routes.rb
cosmetics-web/spec/controllers/pingdom/check_controller_spec.rb

PSD-4102 - pingdom implementation

---

cosmetics-web/app/controllers/pingdom/check_controller.rb
cosmetics-web/config/database.yml
cosmetics-web/config/environments/production.rb
cosmetics-web/config/opensearch.yml
cosmetics-web/config/redis.yml
cosmetics-web/config/storage.yml
cosmetics-web/spec/controllers/pingdom/check_controller_spec.rb

Changes for DBT Platform compatibility.
N/A
N/A
~- [ ] Documentation has been added or updated~
~- [ ] Database seeds have been updated~
~- [ ] Database migrations have been tested (both up and down) and are safe (e.g. stop using a column before removing it)~
~- [ ] A feature flag has been added (if required in the ticket; a ticket has also been added to remove the feature flag once deployment is completed)~
~- [ ] Comms have been sent to users (if required in the ticket)~
~- [ ] OSU Support service has been updated (if required in the ticket)~
Test this by deploying to staging before merging the change in.

chore: dbt platform compatibility

---

.github/workflows/deploy-production.yml

add antivirus back into manifest.yml in production
