OfficeForProductSafetyAndStandards/cosmetic-product-notifications

app/controllers/investigations_controller.rb, app/controllers/users_controller.rb, app/helpers/businesses_helper.rb, app/helpers/products_helper.rb, app/models/concerns/searchable.rb, docker-compose.yml
This just uses the default fuzziness parameters for now, but should yield better search results when entering text phrases. We should look at adding n-gram or stemming indices if we want to further improve search results.
User email addresses are still searched using prefix matching.
=> MSPSDS-289: Fix prefix search and use fuzzy search for cases, businesses and products

.gitignore, keycloak/configuration/standalone-ha.xml, keycloak/configuration/standalone.xml, keycloak/manifest.yml, keycloak/modules/postgresql-module.xml, keycloak/scripts/deploy-keycloak.sh, keycloak/scripts/package-keycloak.sh
The package script downloads the Keycloak standalone distribution and configures it to use a PostgreSQL database and the Home Office's [GOV.UK theme](https://github.com/UKHomeOffice/keycloak-theme-govuk). The deploy script pushes this package to Cloud Foundry using the associated manifest file.
=> MSPSDS-302: Create Keycloak package and deploy scripts for Cloud Foundry

docker-compose.yml, elasticsearch/Dockerfile
This version does not come bundled with the commercial X-Pack plugin or trial licence.
=> MSPSDS-289: Use open source version of Elasticsearch Docker image

app/helpers/elasticsearch_query.rb
This fixes an issue where sorting returns an error if a sort column is specified but no records are present in the Elasticsearch index (details [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_ignoring_unmapped_fields)).
=> MSPSDS-210: Specify fallback sort type when Elasticsearch index is empty

.gitmodules
GitHub doesn't deal well with submodule names that start with a period. In particular, it causes all calls to its [create tree API](https://developer.github.com/v3/git/trees/#create-a-tree) endpoint to 422 with a `GitRPC::BadGitmodules` error.
The name of a submodule is simply for convenience, so there shouldn't be any reason to prefer starting it with a period to not.
=> Rename submodule to not start with a period

web/config/application.rb
Should not change how timestamps are stored in database according to documentation, but will change the way Rails treats them. In particular it fixes the annoying bug with history being 1 hour early.
=> MSPSDS-654: Set timezone in configuration to fix bugged times

web/app/models/activity.rb
As I wrote on the ticket, case is not ‘updated’ when we update something that can be associated with many cases, like a product or a business. ￼￼
Case is ’updated’ when we change a field, associate/disassociate anything with a case. That probably also includes changing anything that can only be associated to a single case, like hazard details, description of an image linked to a case, adding case correspondence, etc.
Ed and Nick agree this is a reasonable approach, and that if for some reason it is not, then we can add a ticket for it later. 
Thing is, this parallels our conditions for creating an activity. And in general I think we do want to update a case whenever it has a new activity in its timeline, and I can't think of any reason to change 'updated date' without adding a point to a …
=> MSPSDS-723: Make sure each activity causes an update of its investigation

web/app/helpers/investigations_helper.rb, web/app/views/investigations/index.xlsx.axlsx
Probably not really related to status, but it's the ticket this bug report showed up.
Pagination was broken when exporting to xlsx. This makes sure that 'the exported list is exactly as visible list', which might not be the perfectly intuitive approach, but is what is written on several tickets.
=> MSPSDS-537: Filter by status

web/app/assets/stylesheets/application.css, web/app/assets/stylesheets/autocomplete.scss
Ensure that our styling overrides take precedence over the module stylesheet by switching the order in which they are imported.
=> MSPSDS-744: Fix accessible autocomplete styling

web/app/models/investigation.rb, web/app/models/investigation_business.rb, web/app/models/investigation_product.rb
The was an error on startup with the `.order("investigation_products.created_at")`:
```
2018-11-26T08:06:18.26+0000 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:603:in `async_exec': PG::UndefinedColumn: ERROR:  column investigation_businesses.created_at does not exist (ActiveRecord::StatementInvalid)
```
which was coming from the elasticsearch import at the bottom of `web/config/environments/production.rb`.
Seems related to https://stackoverflow.com/questions/40247388/rails-5-has-many-through-order-on-through-table. I don't actually know if this still produces the required functionality but it at least fixes the deployment!
=> MSPSDS-551: Investigation business and product sort fix

cosmetics-web/deploy.sh, web/deploy.sh
It looks like the shared-web files we're getting copied to vendor/shared-web/shared-web/* (on my machine at least).
=> COS-31 Fix issue with the deploy script

web/test/controllers/businesses_controller_test.rb, web/test/controllers/investigations/businesses_controller_test.rb, web/test/controllers/investigations/products_controller_test.rb, web/test/controllers/investigations_controller_test.rb, web/test/controllers/products_controller_test.rb, web/test/helpers/product_helper_test.rb, web/test/models/investigation_test.rb, web/test/system/investigation_assignee_test.rb, web/test/system/investigation_highlight_test.rb, web/test/test_helper.rb
To resolve some of the more common Elasticsearch-related errors we've been seeing in recent test runs, this PR makes the following changes:
* Import all test fixtures into Elasticsearch at the start of each test class
* Remove redundant Elasticsearch imports in tests
* Where imports are still required, refresh the index instead of recreating it
* Ensure all stubbed users are loaded as part of relevant test helper methods
* Minor refactoring of some test setup and assertions
=> MSPSDS-NONE: Test fixes for Elasticsearch failures

web/app/assets/stylesheets/search-box.scss, web/app/views/investigations/index.html.slim, web/config/initializers/sidekiq.rb
Tiny changes after it came back from testing. 
Although ticket suggests the code is shared between case list page and business/product lists, it's actually separate(just used to be very similar). Which is probably good, cause designs for them look differently. 
Includes a trivial change to sidekiq(moving method so it's loaded in time for ruby to know it's there).
=> MSPSDS-722: Restyle search box and case list

web/app/views/application/_business_summary.html.slim, web/app/views/businesses/show.html.slim
The business summary partial is used in a number of places and has now diverged from the properties shown at the top of the business page.
=> MSPSDS-807: Revert changes to business summary and update business page

cosmetics-web/vendor/shared-web/lib/shared/web/version.rb, cosmetics-web/vendor/shared-web/package.json, cosmetics-web/vendor/shared-web/shared-web.gemspec, web/vendor/shared-web/lib/shared/web/version.rb, web/vendor/shared-web/package.json, web/vendor/shared-web/shared-web.gemspec
It's currently complaining that it can't find `shared-web` https://app.dependabot.com/accounts/UKGovernmentBEIS/#beis-mspsds
Adding these symlinks allows me to run `bundle install` and `yarn install` on my host machine.
Might be worth checking that this doesn't totally break someone on Windows? @jasiekmiko, @raamSoftwire?
=> COS-31: Fix dependabot issues

cosmetics-web/deploy.sh, web/deploy.sh, worker/deploy.sh
PR #392 added symlink files to the shared-web subdirectories of cosmetics-web and web to allow bundler and yarn to find the relevant files from shared-web. These existing files cause the deploy scripts to fail when copying the contents of shared-web to these subdirectories, so remove them first.
=> MSPSDS-NONE: Fix Cloud Foundry deployment by removing existing files

keycloak/Dockerfile, keycloak/README.md, keycloak/configuration/initial-setup.json, keycloak/providers/email/pom.xml
Reverts UKGovernmentBEIS/beis-mspsds#393
An issue with the latest release of Keycloak breaks our ability to fetch users from MSPSDS (the exact cause is still TBD, but seems related to a permissions issue for calls to the Keycloak API when using client credentials authentication).
A (possibly related) issue in Keycloak 4.7.0 also prevents us from being able to restrict access to the Keycloak admin console, but still allow user management (see [KEYCLOAK-9066](https://issues.jboss.org/browse/KEYCLOAK-9066)).
=> Revert Keycloak upgrade

mspsds-web/Gemfile.lock
Reverts UKGovernmentBEIS/beis-mspsds#402.
This change https://github.com/kobaltz/clamby/commit/b83768ff903cd452e89508c9d2bbf8aa218b1b7c#diff-ac582526c3f41813a4599030130cf41eR54 means that we try to run `clamdscan --version`.
Because CloudFoundry installs clamav in a weird place, running just `clamdscan --version` gives `ERROR: Can't parse clamd configuration file /etc/clamav/clamd.conf`.
We'll actually want to run `clamdscan --config-file clamav/clamd.conf --version` (similar to https://github.com/kobaltz/clamby/blob/master/lib/clamby/command.rb#L24).
=> Revert "Bump clamby from 1.5.0 to 1.6.0 in /web"

.dependabot/config.yml
Previously there were zero width characters at the start of these directory strings.
=> Remove zero width characters in config.yml

shared-web/config/initializers/assets.rb
I think the reason that we sometimes get timeouts on our tests and when we first load the app locally is because of the [poor docker volume performance on not-linux](https://docs.docker.com/docker-for-mac/osxfs-caching/) (i.e. mac or windows) which affects our asset compilation (which does lots of IO operations).
https://docs.docker.com/v17.09/engine/admin/volumes/tmpfs/ for the `tmp/` folder seems like it would be the best solution but it's linux only
Putting the asset cache in memory reduces the number of IO operations.
I also tried using the `delegated` flag mentioned in the first link but the in-memory cache performance was better.
=> MSPSDS-686: Potentially speed up asset compilation on first run

.travis.yml
@broder when we've discussed this in a couple weeks back, I recall our conclusion was to disable tests on PR builds coming from master.
I'm no longer sure about that logic and have opted for disabling tests on non-pr builds, with the following logic.
1. We want to avoid an untested version of the code to be released. Such a commit on say staging could come from
A) a PR from master, 
B) a PR from feature/hotfix branch, 
C) an admin updating the master branch with staging/prod merge to enable PR from master to staging/prod (when doing staging/prod release).
2. In cases A + B, the PR will have run the same version of the code and tested it. We've got checks that ensure this.
3. In case C, 99% of the time the commit will be empty, since master is practically ahead of the staging/prod branch …
=> MSPSDS-821 speed up time to staging

mspsds-web/db/migrate/20190129155220_add_team_assignee_to_investigation.rb
Turns out using `investigation.update!` will trigger callbacks on investigation, and in this particular case one hook checks for a change in assignee, and tries to create audit activity for it :( 
However, `Investigation.update_all` will not trigger callbacks. I pushed this fix to int and it seems to work as expected.
=> MSPSDS-547: fix migration

mspsds-web/app/mailers/notify_mailer.rb, mspsds-web/app/models/investigation.rb
This solution sends a copy of confirmation to each team member separately. Ideally we would send all these emails in bulk, which seems to be in the feature list on [https://www.notifications.service.gov.uk/features](url). The problem is that there is no documentation for it, and more obvious ways of making it work failed. 
I asked them about it and hopefully they respond soon.
=> MSPSDS-525: Notify team when assigned

cosmetics-web/manifest.yml, mspsds-web/manifest.yml
As we're now sometimes doing `cf push` without `--hostname`, Cloud Foundry assigns a hostname by default (e.g. `mspsds-web.london.cloudapps.digital`) which then breaks the auth flow with Keycloak.
This change should stop that from happening.
=> MSPSDS-907: Fix maintenance routing

cosmetics-web/app/controllers/notification_build_controller.rb, cosmetics-web/app/controllers/notifications_controller.rb, cosmetics-web/app/models/notification.rb, cosmetics-web/app/views/notifications/confirmation.html.slim, cosmetics-web/app/views/notifications/edit.html.slim, cosmetics-web/config/routes.rb, cosmetics-web/db/migrate/20190211144539_add_reference_number_to_notifications.rb, cosmetics-web/db/schema.rb, cosmetics-web/spec/controllers/notification_build_controller_spec.rb, cosmetics-web/spec/controllers/notifications_controller_spec.rb, cosmetics-web/spec/system/manual_notification_entry_spec.rb
- add `reference_number` column to notifications
- randomly generate reference number on creation of a notification
- display the reference number with a `UKCP-` prefix on check your answers and confirmation pages
- use the reference number in the URLs for the notification
=> COSBETA-18 Add unique UK cosmetics product reference number to submitted notifications

mspsds-web/app/controllers/concerns/corrective_actions_concern.rb, mspsds-web/app/controllers/investigations/activities_controller.rb, mspsds-web/app/controllers/investigations/businesses_controller.rb, mspsds-web/app/controllers/investigations/correspondence_controller.rb, mspsds-web/app/controllers/investigations/products_controller.rb, mspsds-web/app/controllers/investigations_controller.rb, mspsds-web/app/helpers/documents_helper.rb, mspsds-web/app/helpers/tests_helper.rb, mspsds-web/app/helpers/url_helper.rb, mspsds-web/app/models/investigation.rb, mspsds-web/db/migrate/20190215121322_fix_incorrect_pretty_ids.rb, mspsds-web/db/schema.rb
Old way is bugged and results in the same ids for many cases. This should re-generate pretty_ids and since the computation is ordered by created_at they should be different.
=> MSPSDS-877: Use new way to compute pretty ids

mspsds-web/app/controllers/concerns/corrective_actions_concern.rb, mspsds-web/app/controllers/investigations/activities_controller.rb, mspsds-web/app/controllers/investigations/businesses_controller.rb, mspsds-web/app/controllers/investigations/correspondence_controller.rb, mspsds-web/app/controllers/investigations/products_controller.rb, mspsds-web/app/controllers/investigations_controller.rb, mspsds-web/app/helpers/documents_helper.rb, mspsds-web/app/helpers/tests_helper.rb, mspsds-web/app/helpers/url_helper.rb, mspsds-web/app/models/investigation.rb, mspsds-web/app/views/investigations/index.xlsx.axlsx, mspsds-web/app/views/investigations/show.pdf.slim, mspsds-web/db/migrate/20190215121322_fix_incorrect_pretty_ids.rb, mspsds-web/db/migrate/20190218110830_make_pretty_id_work_with_old_cases.rb, mspsds-web/db/schema.rb
Last version worked great with cases from current month, but not so great with cases from before current month. 
I can't really understand the results I got by running the old migration on int, the current month ids don't seem to be in the right order(when sorting by created_at), the older ones all use the count of 5(count of cases from current month), except for one that uses 4. 
Maybe having 2 conditions on the same field in different wheres with different types doesn't generate the query the way I thought it does :( 
In any case, this should make case ids unique for older months, migration works for the limited dataset I have locally.
=> MSPSDS-877: Use pretty id in urls

mspsds-web/app/controllers/investigations/ts_investigations_controller.rb, mspsds-web/app/models/investigation.rb, mspsds-web/app/views/businesses/_form.html.slim
Fixes both issues described on Jira ticket: 
> Two remaining issues:
> 
> The summary text is showing “unsafe and non-compliant” regardless of which checkboxes are selected
> 
> - Validation not working correctly when adding a business: 
> - Choose to add a business
> - Leave trading name blank and click continue
> 
> Validation is triggered but contact details sections of the page are hidden
=> MSPSDS-566 testing fixes

mspsds-web/config/webpacker.yml
Without this option enabled watching does not seem to work, at least
not on Windows machines.
https://webpack.js.org/configuration/watch/#watchoptionspoll gives
some examples of systems where that is the found behaviour - presumably
our windows-docker set up falls into the same bucket.
=> MSPSDS-6 Turn on polling in file watch for webpack

.travis.yml
Travis builds timeout if commands do not produce any output for 10 minutes, which can be the case when assets are being compiled during web deployments. Using the travis_wait function extends that limit to 20 minutes. For details, see:
https://docs.travis-ci.com/user/common-build-problems#build-times-out-because-no-output-was-received
=> COSBETA-NONE: Extend Travis timeout to allow web deployments to finish

mspsds-web/app/controllers/investigations/businesses_controller.rb, mspsds-web/app/views/investigations/businesses/type.html.slim
- Bug fixes raised by Nasir, in the comments of ticket [MSPSDS-938](https://regulatorydelivery.atlassian.net/browse/MSPSDS-938)
- Removing the second "manufacturers" radio
- Changing :base to :type when adding errors to business in controller, so that it matches the radio component.
=> MSPSDS-938 Fixing errors showing on radios, duplicate manufacturer radio

cosmetics-web/db/schema.rb, mspsds-web/app/models/concerns/searchable.rb, shared-web/app/models/shared/web/concerns/searchable.rb
Shared web searchable.rb included a piece that made sure 'updated_at' was updated correctly, in a after_update hook. This in conjunction with us not indexing incomplete notifications caused crashes whenever a draft or incomplete notification was updated. 
Since we actually don't want to index records by updated_at(yet), the simplest solution is to just move the hook into mspsds-web.
=> COSBETA-33: Hopefully fix ES crashes when updating a notification on int

shared-web/app/clients/shared/web/keycloak_client.rb, shared-web/app/helpers/shared/web/login_helper.rb
This should ensure that the user is correctly signed in and directed back to the service after clicking the link in the verification email.
=> COSBETA-174: Include redirect URI in Keycloak registration URL

keycloak/providers/registration-form/src/main/java/uk/gov/beis/mspsds/keycloak/providers/RegistrationMobileNumber.java
Fixes a bug where users could provide invalid phone number.
Changes a returned value of `isPhoneNumberValid` to false when it cannot be interpreted as an international or possible UK phone number. It used to be true, which allowed pretty much any badly invalid number to go through.
=> COSBETA-57: Validate phone registration

cosmetics-web/app/models/notification.rb
Add elasticsearch indexing when a notification is updated from non-complete to complete.
=> COSBETA-176: Index document in the after_save hook

cosmetics-web/app/views/layouts/_footer.html.slim, mspsds-web/app/views/layouts/application.html.slim
If the JS doesn't load for some reason (e.g. an IE specific issue...), we should remove the `.js-enabled` class so that the design system's progressive enhancement stuff can still function (e.g. with tabs).
This is based on https://github.com/alphagov/govuk_template/blob/master/source/views/layouts/govuk_template.html.erb#L113. More discussion at https://github.com/alphagov/govuk-frontend/issues/999
=> MSPSDS-6: Remove .js-enabled if JavaScript isn't successfully loaded

.gitmodules, infrastructure/README.md, infrastructure/fluentd/plugins/out_logit.rb, infrastructure/logstash-filters.conf
`metric-exporter` captures all metrics from spaces that it has the "Space auditor" role for (which is currently int, staging, prod and research) which are then sent to fluentd and onto Logit and S3. I'll add some dashboards soon!
=> MSPSDS-786: Add server metric exporting

cosmetics-web/app/controllers/responsible_persons/account_wizard_controller.rb, cosmetics-web/app/models/responsible_person.rb, cosmetics-web/app/views/responsible_persons/account_wizard/enter_details.slim, cosmetics-web/config/locales/en.yml, cosmetics-web/db/migrate/20190318114749_remove_business_number_from_responsible_person.rb, cosmetics-web/db/schema.rb, cosmetics-web/spec/factories/responsible_person.rb, cosmetics-web/spec/models/responsible_person_spec.rb, cosmetics-web/spec/system/create_responsible_person_spec.rb
Removes the companies house number from the RP model, and removes all tests/text that references it
=> COSBETA-199 Remove companies house number from Responsible Person model

mspsds-web/app/views/documents/edit.html.slim, mspsds-web/app/views/documents/remove.html.slim
The route for `associated_documents_path` didn't exist, so I've updated it to take them to `/products` or `/cases` instead.
=> MSPSDS-1107: Update document back links to go to case page

mspsds-web/app/controllers/teams_controller.rb, mspsds-web/app/models/team.rb, mspsds-web/app/models/user.rb, mspsds-web/test/controllers/contacts_controller_test.rb, mspsds-web/test/controllers/homepage_controller_test.rb, mspsds-web/test/controllers/investigations_controller_test.rb, mspsds-web/test/controllers/team_test.rb, mspsds-web/test/controllers/teams_controller_test.rb, mspsds-web/test/models/corrective_action_test.rb, mspsds-web/test/models/investigation_test.rb, mspsds-web/test/models/user_test.rb, mspsds-web/test/system/create_ts_investigation_test.rb, mspsds-web/test/system/introduction_test.rb, mspsds-web/test/test_helper.rb, shared-web/app/clients/shared/web/keycloak_client.rb
This required some changes to the tests set up, which was still quite
circular: the tests set up some KC mocking, then loaded the collections,
the performed further set-up. Now, I've removed all collection
references from the mocking layer, making the responsibilities much
clearer.
=> MSPSDS-1116 Filter out users without mspsds access from users collection

cosmetics-worker/manifest.yml, mspsds-worker/manifest.yml
The cosmetics-worker manifest was missing the antivirus details
=> MSPSDS-6: Fix missing credentials on cosmetics-worker

cosmetics-web/app/controllers/formulation_upload_controller.rb, cosmetics-web/app/views/formulation_upload/new.html.slim
Show an error, highlighting the form when occurs an error while uploading a formulation file (e.g.: no file, wrong file type)
=> COSBETA-169: Add error highlight when uploading formulation fails

cosmetics-web/app/models/notification.rb, cosmetics-web/app/views/notifications/_component_details.html.slim
"As decided in the kick-off session (COSBETA‌-120), the CMR and nanomaterial properties should not be shown on the edit/show pages if the product was first notified on CPNP **prior** to Brexit date.
Product images are required before a product can be registered if it was first notified on CPNP **after** Brexit date."
=> COSBETA-165 Fix requirements for pre and post brexit notifications

.dependabot/config.yml, psd-web/vendor/shared-web/dev/shared-web-dev.gemspec
The `psd-web` symlink to `shared-web-dev.gemspec` was broken during the rename. We should also be checking the shared dev dependencies using dependabot.
=> MSPSDS-615: shared-web-dev updates

psd-web/app/controllers/investigations/ts_investigations_controller.rb, psd-web/app/views/investigations/edit_summary.html.slim
Make sure we don't store any hazard or non-compliance details if box isn't ticked
If a box is ticked, details filled, and then un-ticked, we still store those 'un-ticked' details on investigation. Which is surfaced in case description.
=> MSPSDS-997: Fix ts case summary bug

psd-web/app/helpers/investigations/display_text_helper.rb
This was breaking search if an investigation had multiple correspondence types. As we could be calling `include?` on `nil` (e,g, when trying to get `email_subject` on a phone call)
=> PSD-1150: Fix crash when investigation has multiple correspondence types

cosmetics-web/deploy.sh, psd-web/deploy.sh
Update the deploy script for `cosmetics-web` to map both the "submit" and "search" subdomains to the app (prefixed by the space name, e.g. `int-submit.cosmetic-...` and `int-search.cosmetic-...`).
=> COSBETA-239: Map submit and search hostnames to app in deploy script

cosmetics-web/app/views/notifications/_component_details.html.slim, cosmetics-web/app/views/notifications/_substances_details.html.slim, cosmetics-web/app/views/poison_centres/notifications/show_poison_centre.html.slim
=> COSBETA-248: Display nanomaterials for both pre- and post-EU Exit notifications

cosmetics-web/app/models/cpnp_export.rb
Nano materials exposure info was not being capture on bulk upload journey because of not casting to int.
=> COSBETA-259: fix the bug of reading exposure info

cosmetics-web/app/controllers/additional_information_controller.rb, cosmetics-web/app/controllers/component_build_controller.rb, cosmetics-web/app/controllers/formulation_upload_controller.rb, cosmetics-web/app/controllers/notification_build_controller.rb, cosmetics-web/app/controllers/product_image_upload_controller.rb, cosmetics-web/app/policies/responsible_person_notification_policy.rb, cosmetics-web/spec/controllers/additional_information_controller_spec.rb, cosmetics-web/spec/controllers/component_build_controller_spec.rb, cosmetics-web/spec/controllers/notification_build_controller_spec.rb, cosmetics-web/spec/controllers/product_image_upload_controller_spec.rb
Prevents users from updating notifications once they've been submitted, either via replacing IDs in manual journey routes or the product for formulation upload pages.
=> COSBETA-158 Prevent users from editing submitted notifications

CHANGELOG.md, cosmetics-web/app/controllers/responsible_persons/account_wizard_controller.rb, cosmetics-web/app/controllers/responsible_persons/team_members_controller.rb, cosmetics-web/app/controllers/responsible_persons/verification_controller.rb, cosmetics-web/app/models/responsible_person_user.rb, cosmetics-web/app/views/responsible_persons/team_members/index.html.slim, cosmetics-web/spec/factories/user.rb, cosmetics-web/spec/login_helpers.rb, keycloak/configuration/initial-setup.json, psd-web/app/controllers/teams_controller.rb, psd-web/app/models/activity.rb, psd-web/app/models/investigation.rb, psd-web/app/models/user.rb, psd-web/app/views/investigations/_current_status.html.slim, psd-web/app/views/teams/show.html.slim, psd-web/test/controllers/activities_controller_test.rb, psd-web/test/controllers/investigations_controller_test.rb, psd-web/test/controllers/team_test.rb, psd-web/test/models/investigation_test.rb, psd-web/test/models/notification_test.rb, psd-web/test/models/user_test.rb, psd-web/test/system/investigation_assignee_test.rb, psd-web/test/system/record_email_correspondence_test.rb, psd-web/test/system/record_phonecall_correspondence_test.rb, psd-web/test/test_helper.rb, shared-web/app/clients/shared/web/keycloak_client.rb, shared-web/app/models/shared/web/user.rb
The user's full name is stored on Keycloak as the "firstName" field. The "lastName" field is no longer used.
=> PSD-1125: Use single name field on User model

cosmetics-web/app/views/poison_centres/notifications/_poison_centre_trigger_rule_formulation.html.slim
As notify user, I can see below product in notified tab and I can see product details with no issues however same product as poison centre user it returns 500 error. Also I added this product just today through bulk upload and successfully added- However I think it spitted error in error tab.
Show humanized answer of a trigger rule element to a poison centre user
=> COSBETA-265: 500 error on product page as poison centre user

psd-web/app/models/team.rb
This fixes the problem of trying to operate on a `nil` `data` object at
times when the fetching was not successful.
Notably, the initialization happens not just when the server is booting,
but also for any rake task being run
(see https://guides.rubyonrails.org/v3.2/configuring.html#rails-general-configuration)
. In those cases the fetching has been observed to fail with
`Failed to open TCP connection to keycloak:8080 (Connection refused - connect(2) for \"keycloak\" port 8080)`
=> PSD-1176 Only check correct teams are present if fetch succeeds

infrastructure/elastalert/cosmetics_web_5xx_frequency.yml, infrastructure/elastalert/keycloak_5xx_frequency.yml
This PR adds ElastAlert files for 5xx errors on Keycloak and Cosmetics-web. These alerts have already been added to Logit.
(NB. @broder did add 5xx errors to the original server metrics dashboard, but they sometimes aren't shown if there were no 5xx errors in the currently selected interval. This meant that I missed them in my previous PR)
=> COSBETA-NONE: Add logging for 5xx errors

psd-web/app/views/teams/show.html.slim
Also [PSD-1154](https://regulatorydelivery.atlassian.net/browse/PSD-1154) as minor content change.
Only showing a span if username is present, to prevent misalignment on team members page
Changing 'Team Members' to 'Team members'.
=> PSD-1153 Alignment and content bugs

infrastructure/logstash-filters.conf
This is a small fix to the logstash filters. It updates the syntax within the dissect function. 
With the comma present the data type conversion wasn't running. This in turn means that the fields were labelled as strings rather than numbers, which meant that the fields couldn't be used for visualizations on dashboards.
=> Cosbeta none fix logstash filters

cosmetics-web/app/views/landing_page/index.html.slim
Moving PR #900 to a new branch on the main repo...
- changes the masthead introduction paragraph to make it less duplicative of the new service name
- adds a broader introduction to the service in the body of the page
- simplifies the instruction for pre-Brexit products by telling the user what they don't need to provide instead of repeating what they do need to include
- changes the masthead intro paragraph from `h2` to `p`, removing the only `h2` so bumps all `h3`and `h4` headings up
=> COSBETA-190: Updates to content on home page

cosmetics-web/app/controllers/component_build_controller.rb, cosmetics-web/app/controllers/trigger_questions_controller.rb, cosmetics-web/app/views/component_build/add_cmrs.html.slim, cosmetics-web/app/views/component_build/add_nanomaterial.html.slim, cosmetics-web/app/views/component_build/add_physical_form.html.slim, cosmetics-web/app/views/component_build/add_shades.html.slim, cosmetics-web/app/views/component_build/contains_nanomaterials.html.slim, cosmetics-web/app/views/component_build/number_of_shades.html.slim, cosmetics-web/app/views/component_build/select_category.html.slim, cosmetics-web/app/views/component_build/select_formulation_type.html.slim, cosmetics-web/app/views/component_build/select_frame_formulation.html.slim, cosmetics-web/app/views/component_build/upload_formulation.html.slim, cosmetics-web/app/views/notification_build/single_or_multi_component.html.slim, cosmetics-web/app/views/trigger_questions/_substance_check.html.slim, cosmetics-web/app/views/trigger_questions/_substance_check_with_condition.html.slim, cosmetics-web/app/views/trigger_questions/contains_cationic_surfactants.html.slim, cosmetics-web/app/views/trigger_questions/contains_vitamin_a.html.slim, cosmetics-web/app/views/trigger_questions/contains_xanthine_derivatives.html.slim, cosmetics-web/app/views/trigger_questions/exact_ph.html.slim, cosmetics-web/app/views/trigger_questions/ph_mixed_hair_dye.html.slim, cosmetics-web/app/views/trigger_questions/ph_mixed_product.html.slim, cosmetics-web/app/views/trigger_questions/select_ph_range.html.slim
COSBETA243: Display component name when it's a multi-component
=> COSBETA243: Display component name for multi-component products

cosmetics-web/app/controllers/trigger_questions_controller.rb
COSBETA-410: Stop creating empty trigger question rules
when starting the trigger questions rules on the manual journey
=> COSBETA-410: Stop creating empty trigger question rules

.travis.yml, infrastructure/ci/run-regression-tests.sh
For now, the script just runs the smoke tests to check that the Travis [cron job](https://docs.travis-ci.com/user/cron-jobs/) is working as expected. I'll switch to scenarios tagged as "regression" once those tests have been finalised and the [opss-functional-tests](https://github.com/UKGovernmentBEIS/opss-functional-tests) Docker image has been updated.
=> OPSS-3: Run nightly regression tests as a Travis cron job

cosmetics-web/app/controllers/trigger_questions_controller.rb, cosmetics-web/app/views/trigger_questions/ph_mixed_product.html.slim, cosmetics-web/spec/system/manual_notification_entry_spec.rb
This question is already asked in a similar form near the start of the manual journey (after "Is the cosmetic product available as a single item or as a kit?"), and only applies at the product level, whereas trigger rule questions are asked per component.
=> COSBETA-438: Remove mixed components trigger rule question

cosmetics-web/app/controllers/component_build_controller.rb, cosmetics-web/app/controllers/concerns/manual_notification_concern.rb, cosmetics-web/app/controllers/notification_build_controller.rb, cosmetics-web/app/models/notification.rb, cosmetics-web/app/views/notification_build/for_children_under_three.html.slim, cosmetics-web/app/views/notifications/_product_details.html.slim, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/controllers/notification_build_controller_spec.rb, cosmetics-web/spec/factories/notification.rb, cosmetics-web/spec/models/notification_spec.rb, cosmetics-web/spec/system/manual_notification_entry_spec.rb
As part of the manual journey, add a page to capture whether the product is intended for children under 3 years of age.
=> COSBETA-408: Under three years old question

psd-web/Dockerfile
libgconf can't be found by apt-install and isn't needed
Other apt-install like xvfb don't need to be there as they're automatically installed
=> Updating psd dockerfile to match cosmetics

cosmetics-web/app/views/layouts/_navbar.html.slim
https://regulatorydelivery.atlassian.net/browse/COSBETA-534
Remove the Nanomaterial navigational link in preparation for the public beta.
=> Remove Nanomaterial navigational link

cosmetics-web/app/controllers/nanomaterial_build_controller.rb, cosmetics-web/app/views/nanomaterial_build/committee_on_toxicology_not_notified.html.slim, cosmetics-web/app/views/nanomaterial_build/committee_on_toxicology_notified.html.slim, cosmetics-web/app/views/nanomaterial_build/non_standard_nanomaterial_notified.html.slim
Add content for non_standard_nanomaterial_notified and create dummy pages for the next steps in the journey
=> COSBETA-538 - Check if RP has notified non-standard nanomaterial

cosmetics-web/app/controllers/component_build_controller.rb
Make sure that we validation formula files when the user uploads them and display the validation error on the correct page.
=> COSBETA-493 [BUGFIX] Resolve validation issue with uploading frame formula.

psd-web/app/models/concerns/active_hash_safe_loadable.rb, psd-web/app/models/organisation.rb, psd-web/app/models/team.rb, psd-web/app/models/team_user.rb, psd-web/app/models/user.rb
Ticket: https://trello.com/c/tzbTEwby
In various models based on ActiveHash, data from Keycloak was assigned in bulk by means of `self.data =` - under heavy loads this has randomly lead to `Duplicate key` errors from ActiveHash.
Here we add a re-try mechanism if this occurs.
In local stress tests using JMeter, this approach prevented all status 500 errors that were happening before the changes. The logs revealed that only one retry was every necessary to successfully assign the Keycloak data.
=> Re-try bulk assignment of self.data on failure

shared-web/config/initializers/lograge.rb
This alters the 'lograge' configuration to enable it to be turned off by setting a `LOGRAGE_ENABLED` environment variable to `false`. It remains enabled by default if no environment variable is present.
[Lograge](https://github.com/roidrage/lograge) is a Ruby gem which changes the default Rails logging format to make it less verbose, instead having a single line of information. Whilst this may be useful for production environments, I've found it to be frustrating in development, as the default Rails logging contains useful information such as the parameters, and each view and partial being rendered.
With lograge:
Without lograge (Rails default):
=> Allow 'lograge' to be disabled from an env variable

cosmetics-web/config/redis.yml
The existing configuration assumes that Redis is running on a host called `redis` in development and test environments.  This change allows this default to be overriden by setting a  `REDIS_URL` environment variable.
This is useful, I think, as running Redis locally on the `redis` host means altering your `/etc/hosts` file, which is a minor inconvenience and not necessarily obvious.
=> Allow Redis URL to be configured via environment variable

psd-web/app/views/homepage/non_opss.html.slim
Adding a banner to raise our awareness of the bugs on the service. To be present until we've fixed them.
=> Add banner to non-opss page

.gitignore
When running the [Redis](https://redis.io) server locally, by default it saves periodic [snapshots](https://redis.io/topics/persistence#snapshotting) to a file named `dump.rdb`.
This tells Git to ignore this file, so that it doesn’t accidentally get committed.
=> Ignore Redis snapshots

cosmetics-web/app/views/component_build/contains_poisonous_ingredients.html.slim
Values for the radio button fields should be strings, otherwise our template doesn't include them... 🤦‍♂
=> Bugfix: radio boolean values should be specified as strings

cosmetics-web/app/controllers/component_build_controller.rb, cosmetics-web/spec/controllers/component_build_controller_spec.rb
This updates the follow of the component questions so that _only_ post-Brexit products get asked whether the product contains harmful ingredients when using a frame formulation.  Pre-Brexit products skip straight to the PH question instead.
Fixes a bug introduced by https://github.com/UKGovernmentBEIS/beis-opss/pull/1331
=> Skip poisonous ingredients question for pre-Brexit products

psd-web/app/views/layouts/application.html.slim
While looking at the application.html for psd I notieced the google analytics tracking code was put in a content_for that wasn't used anywhere. This is why are GA isn't tracking. I think it was going to be used for a general header for multiple services, but I've reverted it to how it used to be as I'm not sure where :start_of_head was supposed to be called.
=> PSD: Re-add google analytics after being put in a lost content_for

cosmetics-web/app/models/component.rb, cosmetics-web/spec/models/component_spec.rb
The difference between minimum pH and maximum pH cannot be greater than 1.
Part of https://regulatorydelivery.atlassian.net/browse/COSBETA-600
=> Add extra validation rule for component pH

cosmetics-web/app/controllers/trigger_questions_controller.rb, cosmetics-web/spec/controllers/trigger_questions_controller_spec.rb
This fixes a bug whereby when the alkaline agent question is asked, an error message is displayed saying "Select an option" due to the `applicable` column not being set to `true`.
=> Set applicable=true on alkaline agent questions

cosmetics-web/config/routes.rb, cosmetics-web/lib/constraints/domain_constraint.rb
If you try to start the application without providing the `SUBMIT_HOST` and `SEARCH_HOST` env vars, the application exists with an unhelpful error message. This fixes that.
=> Provide meaningful error message when domains aren't set

cosmetics-web/db/migrate/20190214145420_add_cpnp_basic_info_to_notification.rb, cosmetics-web/db/migrate/20190220140100_add_formulation_to_components.rb, cosmetics-web/db/migrate/20190330192439_add_user_attributes.rb
For some reason, these called `safety_assured` or `create_table` outside of a `change` block, which doesn't work.
=> Fix some legacy migrations

cosmetics-web/env.example, cosmetics-web/spec/system_helper.rb
This allows developers to tell Selenium where they have installed the [Chromedriver](https://chromedriver.chromium.org) binary.
=> Allow chromedriver path to be explicitly set

cosmetics-web/config/redis.yml, cosmetics-web/deploy-review.sh, cosmetics-web/manifest.review.yml, cosmetics-worker/manifest.review.worker.yml
This allows developers to create a new redis service, rather than re-using a shared one, when deploying review apps.
=> Ability to create a separate instance of redis

cosmetics-web/app/controllers/application_controller.rb, cosmetics-web/app/controllers/concerns/authentication_concern.rb, cosmetics-web/app/controllers/poison_centres/notifications_controller.rb, cosmetics-web/app/models/user.rb, cosmetics-web/app/views/notifications/_component_details.html.slim, cosmetics-web/app/views/notifications/_product_details.html.slim, cosmetics-web/app/views/notifications/_trigger_question_details.html.slim, cosmetics-web/app/views/poison_centres/notifications/show_msa.html.slim, cosmetics-web/spec/controllers/poison_centres/notifications_controller_spec.rb, cosmetics-web/spec/factories/component.rb, cosmetics-web/spec/factories/notification.rb, cosmetics-web/spec/models/user_spec.rb
https://regulatorydelivery.atlassian.net/browse/COSBETA-631
This ensures that market surveillance authority users can't view product ingredients.
As demonstrated by the video, the user who created the notification can still see them.
Poison centre users view the product on a different set of templates which haven't been altered here.
The diff on the view templates is a bit over the top; I mostly just added indentation beneath the new conditionals. Slim 🤷‍♂
=> Don't show product ingredients to MSA users

cosmetics-web/Gemfile, cosmetics-web/Gemfile.lock
This avoids the warning:
> The git source `git://github.com/UKGovernmentBEIS/govuk-design-system-rails.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
...appearing in the build logs, to reduce the noise (and improve security).
=> Fetch github gem repo via https

infrastructure/ci/deploy-review-app.sh
This will avoid errors when the branch name contains characters not allowed for the service instance name or the Redis database name.
=> Use Pull Request ID instead of branch name

cosmetics-web/app/controllers/notification_build_controller.rb, cosmetics-web/app/controllers/trigger_questions_controller.rb, cosmetics-web/app/models/notification.rb, cosmetics-web/spec/controllers/notification_build_controller_spec.rb, cosmetics-web/spec/factories/component.rb, cosmetics-web/spec/requests/trigger_questions_requests_spec.rb, maintenance/yarn.lock
Products notified before Brexit don’t need to upload a product image.
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-700
Review app: https://cosmetics-pr-1426-submit-web.london.cloudapps.digital
=> Skip product image upload page for pre-Brexit notifications

cosmetics-web/app/controllers/component_build_controller.rb, cosmetics-web/spec/controllers/component_build_controller_spec.rb
Regardless of whether a user is notifying on a product pre or post brexit they should be asked whether their product contains CMRs.
This PR changes the pre-brexit journey to make sure that this now happens.
=> Ask users CMR questions regardless of pre or post brexit

cosmetics-web/app/models/component.rb, cosmetics-web/spec/models/component_spec.rb
This fixes the following bug:
If you select "The minimum pH is lower than 3" for a component, and then give an explicit range (eg 2.3 to 3.0), but then go back and change the answer to the first question to be "It does not have a pH", the 2.3–3.0 pH range was not removed from the component.
This wasn't really visible unless you changed your answer _again_ to require a pH range, in which case your previous answer was still there.
Spotted by @nasirkhanbeis as part of #1471. 👍
=> Bugfix: remove pH range if answer changed to not require it

cosmetics-web/app/models/nano_element.rb, cosmetics-web/spec/models/nano_element_spec.rb
This PR addresses making sure that nano-matieral, which are not notified within the UK, are classed as "incomplete".
This means that the only way that a user can complete a notification is when they have confirmed that toxicology has been notified within the UK, for all nano-material present.
As the main change here is to update the definition of "incomplete", for a nano-material, we enhance the
=> Make sure bulk upload caters for nano-material that is not notified the UK

cosmetics-web/app/models/notification.rb, cosmetics-web/spec/factories/image_upload.rb, cosmetics-web/spec/models/notification_spec.rb, cosmetics-web/spec/rails_helper.rb
Resolves issue where users were allowed to notify a product whilst there was still missing information.
Review app: https://cosmetics-pr-1485-submit-web.london.cloudapps.digital/
=> Make sure users can only submit a notification when there is no more information to add.

cosmetics-web/app/views/responsible_persons/notifications/index.html.erb
=> Add missing whitespace

cosmetics-web/app/models/notification.rb, cosmetics-web/spec/models/notification_spec.rb
When we check whether a notification has missing information didn't address pre EU exit images checks.
This PR adds a check to the image check requirements, to make sure that a pre EU exit notification doesn't have any images uploaded. Addressing a point made [here](https://github.com/UKGovernmentBEIS/beis-opss/pull/1485/files#r353805729)
=> Refactor how we check for images before we submit a notification

cosmetics-web/app/views/layouts/_header.html.erb
Since upgrading to `govuk-frontend` 3.x these now need a `govuk-` prefix.
=> Bugfix: Header navigation on mobile

cosmetics-web/app/controllers/additional_information_controller.rb, cosmetics-web/app/controllers/nanomaterial_build_controller.rb
When uploading a zip file, the application needs to loop you through any components and/or nanomaterials which need additional information.
This change makes sure that these are looped through in the database’s `id` order.  When this isn't specified, the order can be unpredictable (based upon Postgres internals), which was causing issues when writing tests.
=> Specify sort order when looping through components and nano elements

.github/workflows/review-apps.yml
This PR introduce the usage of Github Deploy API to display review apps deploy information.
When the review app deployment gets initiated will show the progress:
Through the **"Deployed"** link we will be able to jump to the Pull request checks and track the progress of the deployment:
Once deployed, a "**View Deployment**" link will be displayed so the review app can be directly accessed:
=> Show Review Apps deployment information in PR

cosmetics-web/manifest.review.yml, cosmetics-web/manifest.yml, cosmetics-worker/manifest.yml, infrastructure/fluentd/manifest.yml
The new Ruby buildpack is [currently broken](https://github.com/UKGovernmentBEIS/beis-opss/pull/1644) so this change pins to the last known working version. It's a short term fix while we investigate fixing the issue, but it also means we can be sure it can continue to deploy should the project be halted.
=> Pin Ruby buildpack to v1.8.4 to maintain compatibility

.github/workflows/deploy.yml, .github/workflows/review-apps.yml, cosmetics-web/deploy-github-functions.sh
Github deployments API will track the deployment of both Staging and
Production environments when new commits are pushed into master branch.
When the deployments succeed, Github deploy information will show a
link for each of the deployed environments.
The process is the same in each environment deployed:
1. Create a Github deployment for the environment.
2. Set deployment status as initiated.
3. Deploy the environment.
4. Set deploy status as success or failure depending on the deploy result.
5. When successful, a link to the deployment environment will be displayed.
Related to https://github.com/UKGovernmentBEIS/beis-opss/pull/1637
I don't recall a way to test this workflow without actually merging it into master and :crossed_fingers:. So if it doesn't work on the first attempt this can …
=> Show deploy information for Staging and Production

.github/workflows/deploy.yml, .github/workflows/review-apps.yml, cosmetics-web/deploy-github-functions.sh
All the reviewapps are being deployed under "int" environment on Github deployments, matching the BEIS PaaS "int" Space that hosts all the review apps.
This approach has a critical downside though: 
**New PRs deploys are considered as the latest version of the same "int" environment**, and Github Deployment tags
the previously deployed PRs as "innactive", removing he deployment information and environment URL.
As a consequence of this, we cannot have multiple PRs opened in parallel showing Deployment & Environment information.
In order to avoid this, we are creating individual environments for each Pull Request number. So multiple review app environments will be cohabiting in Github Deployment domain without stepping over each other.
This approach was suggested by @frankieroberto [over …
=> Set individual Github environments for reviewapp deploys

.github/workflows/deploy.yml
When [URLs where extracted from the Bash deploy functions](https://github.com/UKGovernmentBEIS/beis-opss/pull/1657/commits/f9388518836168b083e22e5c52f75267ddc965f2) to the workflows, I forgot to pass them as parameter to the functions when calling them from Staging/Production deploy workflow.
As a result, the environment URL is showing up as the log URL instead of showing a button near the Deployment info, while the log URL to track the deploy process is not being displayed at all.
This change adds the missing argument.
=> Fix missing urls in staging and production deploys

cosmetics-web/config/routes.rb, cosmetics-web/lib/constraints/domain_exclusion_constraint.rb, cosmetics-web/lib/constraints/domain_inclusion_constraint.rb, cosmetics-web/spec/domain_helpers.rb, cosmetics-web/spec/features/zip_file_upload_pre_brexit_notifications_spec.rb, cosmetics-web/spec/lib/domain_exclusion_constraint_spec.rb, cosmetics-web/spec/lib/domain_inclusion_constraint_spec.rb, cosmetics-web/spec/requests/notifications_page_spec.rb, cosmetics-web/spec/requests/root_path_spec.rb
[COSBETA-816](https://regulatorydelivery.atlassian.net/browse/COSBETA-816)
Until now, when loading the Cosmetics application in our machines for development, we needed to set up SUBMIT_HOST and SEARCH_HOST in our environment variables, and access the Cosmetics in our machines by using either of those values as URL.
Attempting to load the service by using: "http://localhost:300x" was resulting into an error page.
For development purposes we want to default to the Submit page when requesting the service from our computers with "http://localhost:300x" or from docker with "127.0.0.1:300x". 
- Did some housekeeping with the route domain constraints, plus solved some issue with the actual routing. All the changes & reasoning behind them are described in their respective commits. 
- Changed the …
=> Default to Submit page when not specifically requesting Search pages

.github/workflows/review-apps.yml, cosmetics-web/deploy-github-functions.sh
We guessed marking them as transient would reproduce Heroku review apps
behaviour, but instead what happened is:
- Review apps environments with transient deploys don't get their own
info box as the rest of environments in the Github deployments list.
- Each time a new commit is pushed into the affected Pull Request,
triggering a new deploy, the previous deploy is still listed as
active instead of being replaced by the new one. So you get a deploy
link per push.
This is completely unnecessary as all these deploys contain a list to
the same "review-app-xxx" environment. So we just need the latest
deploy to be "active" and the previous ones being automatically
inactivated.
Given that, going back to the default non-transient approach is more
adequate for our needs.
=> Stop setting review apps as transient deploys

.github/workflows/review-apps-delete.yml, cosmetics-web/deploy-github-functions.sh
[JIRA-821](https://regulatorydelivery.atlassian.net/browse/COSBETA-821)
On top of deleting the review app itself when a Pull Request is merged or closed, we want to set the status of the corresponding GitHub deployment as "inactive", so we won't have a "View Deployment" link for an environment that does not exist anymore.
=> Set GitHub deploys as inactive when pr merged

.dependabot/config.yml
As Fluentd is no longer used in the project.
=> Remove Fluentd config from Dependabot

.github/workflows/review-apps-delete-dangling.yml, .github/workflows/review-apps-delete.yml
https://regulatorydelivery.atlassian.net/browse/COSBETA-875
This PR:
- Fixes the deletion of a review app when the pull request is merged/closed.
- Adds a new github workflow to regularly check for dangling review apps (without matching open PR) and delete them.
The one/off action triggered when closing a PR should avoid leaving dangling review apps that not belong to any active Pull Request, but sometimes it fails and the dangling review app stays permanently active unless it gets manually removed. After a while the numbers of dangling review apps turn into dozens, becoming a big waste of resources.
This is why we added a second workflow that will be executed every night to sweep for any dangling review app to be removed.
At this point we could just use the daily schedule deletion and …
=> Fix review apps deletion

.github/workflows/deploy.yml, .github/workflows/review-apps-delete-dangling.yml, .github/workflows/review-apps-delete.yml, .github/workflows/review-apps.yml, cosmetics-web/deploy-review.sh
We can use stable v7 on the client version and then use its alias to CF command.
=> Move to stable cf v7 client on Github Actions

cosmetics-web/app/controllers/concerns/secondary_authentication_concern.rb, cosmetics-web/app/controllers/my_account_email_controller.rb, cosmetics-web/app/controllers/my_account_mobile_number_controller.rb, cosmetics-web/app/controllers/my_account_name_controller.rb, cosmetics-web/app/controllers/my_account_password_controller.rb, cosmetics-web/app/controllers/secondary_authentications_controller.rb, cosmetics-web/app/models/contact_person.rb, cosmetics-web/app/views/layouts/application.html.erb, cosmetics-web/app/views/my_account/email.html.erb, cosmetics-web/app/views/my_account/mobile_number.html.erb, cosmetics-web/app/views/my_account/name.html.erb, cosmetics-web/app/views/my_account/password.html.erb, cosmetics-web/app/views/my_account/show.html.erb, cosmetics-web/app/views/responsible_persons/team_members/index.html.erb, cosmetics-web/app/views/responsible_persons/team_members/new.html.erb, cosmetics-web/config/initializers/devise.rb, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/features/account/change_email_spec.rb, cosmetics-web/spec/features/account/change_mobile_number_spec.rb, cosmetics-web/spec/features/account/change_name_spec.rb, cosmetics-web/spec/features/account/change_password_spec.rb, cosmetics-web/spec/features/account/forgotten_password_spec.rb, cosmetics-web/spec/features/inviting_a_colleague_spec.rb, cosmetics-web/spec/forms/registration/account_security_form_spec.rb, cosmetics-web/spec/models/contact_person_spec.rb, cosmetics-web/spec/support/feature_helpers.rb
COSBETA-668 — adds 'Invite team members' to the explanation of what a team member can do
COSBETA-671 — adds instructions on how to remove a team member on the team members page
COSBETA-879 — corrects password too short error message
COSBETA-878 — changes 'Invite colleague' to 'Invite a team member'
COSBETA-880 — adds to validation of email format for Contact Person
COSBETA-881 — changes 'Name' to 'Full name' on Your account and Change your name
COSBETA-846 — increases the minimum number of characters in a password to 8
=> Visual fixes

cosmetics-web/app/views/responsible_persons/team_members/new.html.erb
When clicking on the email validation error the focus wasn't switching to the email input.
Fixed if by changing the email input id to match the attribute with the validation error.
=> Fix email validation error link on team user invite

cosmetics-web/deploy.sh
The `cf7` command has been replaced with `cf`. 
I forgot to replace the command in the deploy script, breaking the deploy pipeline. Sorryyyy.
=> Replace cf7 with cf in deploy script

cosmetics-web/app/views/my_account/show.html.erb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-873)
As now users can edit their own details, there is no point on telling
them to contact the enquiries email in order to get them changed.
=> Remove info to request to change account details

cosmetics-web/app/controllers/concerns/responsible_person_concern.rb, cosmetics-web/app/controllers/nanomaterial_notifications_controller.rb, cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb, cosmetics-web/app/controllers/responsible_persons/team_members_controller.rb, cosmetics-web/app/controllers/responsible_persons_controller.rb, cosmetics-web/app/controllers/submit_application_controller.rb
The idea originally [raised on the PR](https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/pull/1787#discussion_r512671382) was to either rename the concern into something more explicit like `ValidateCorrectResponsiblePersonConcern` or either keep `ResponsiblePersonConcern` but moving into it all the logic related to Responsible Person.
This PR shows the second approach where we basically wrap all the responsible person controller methods into the `ResponsiblePersonConcern` module, include it into the `SubmitApplicationController` and from there use the module methods on `before_action` calls as needed in the `SubmitApplicationController` or any of its inheriting controllers.
=> Refactor suggestion: Extract Responsible Person related code to concern

cosmetics-web/app/controllers/concerns/responsible_person_concern.rb
Originally solving a bug, but now just turned into a method code simplification.
We do not need to check for user mobile number verification unless the 2FA is enabled in the environment, as the mobile number gets verified when passing 2FA.
=> Do not check for mobile number verification when 2FA is disabled

cosmetics-web/app/controllers/concerns/responsible_person_concern.rb, cosmetics-web/app/controllers/registration/account_security_controller.rb, cosmetics-web/app/controllers/responsible_persons/account_wizard_controller.rb, cosmetics-web/app/controllers/responsible_persons/team_members_controller.rb, cosmetics-web/app/models/pending_responsible_person_user.rb, cosmetics-web/app/models/submit_user.rb, cosmetics-web/app/presenters/pending_responsible_person_invitations_presenter.rb, cosmetics-web/app/views/responsible_persons/account_wizard/pending_invitations.html.erb, cosmetics-web/app/views/responsible_persons/account_wizard/select_type.html.erb, cosmetics-web/app/views/responsible_persons/team_members/index.html.erb, cosmetics-web/db/migrate/20201106130915_add_inviting_user_to_pending_responsible_person_users.rb, cosmetics-web/db/schema.rb, cosmetics-web/spec/controllers/responsible_persons/team_members_controller_spec.rb, cosmetics-web/spec/factories/pending_responsible_person_users.rb, cosmetics-web/spec/factories/user.rb, cosmetics-web/spec/features/creating_an_account_when_having_pending_responsible_person_invitations_spec.rb, cosmetics-web/spec/features/inviting_a_colleague_spec.rb, cosmetics-web/spec/models/pending_responsible_person_user_spec.rb, cosmetics-web/spec/policies/responsible_person_policy_spec.rb, cosmetics-web/spec/presenters/pending_responsible_person_invitations_presenter_spec.rb, cosmetics-web/spec/support/feature_helpers.rb
[Ticket COSBETA-667](https://regulatorydelivery.atlassian.net/browse/COSBETA-667)
An email address has been invited to one/multiple responsible persons by one/multiple members of the team.
The user for that email instead of following the invitation link registers to the Submit Cosmetics service like any other user.
The user will be prompted with a page that will show the list of Responsible Persons they have been invited to.
For each Responsible Person the user has been invited to:
- If there are active invitations for that responsible person, the user will be displayed the date of the latest invitation sent.
- If all the invitations for that responsible person are expired, users will be displayed the name of the RP members who invited them, so they can contact them asking for be …
=> Show user responsible person pending invitations after registration

cosmetics-web/app/controllers/responsible_persons/team_members_controller.rb, cosmetics-web/app/models/pending_responsible_person_user.rb, cosmetics-web/spec/features/inviting_a_colleague_spec.rb
[Ticket: COSBETA-939](https://regulatorydelivery.atlassian.net/browse/COSBETA-939)
Once an user joins a responsible person/team, any other pending invitations for that user need to be deleted.
Also included few tiny refactors like:
- extracting methods with meaningful name for flow readability.
- method rename.
- reorder few feature specs so similar scenarios are together.
=> Bugfix: remove any invitations when joining team

docker-compose.yml
So we can connect to Redis running on Docker on local development.
Needed for running Sidekiq locally when Redis is dockerized.
=> Expose Redis port on docker

cosmetics-web/app/controllers/application_controller.rb, cosmetics-web/app/controllers/concerns/responsible_person_concern.rb, cosmetics-web/app/controllers/registration/account_security_controller.rb, cosmetics-web/app/controllers/users_controller.rb, cosmetics-web/spec/features/account/creating_an_account_from_an_invitation_spec.rb, cosmetics-web/spec/features/account/submit_sign_up_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-961)
**Bugfixes:**
- Fix registration when 2FA is disabled, avoiding declaration being shown before account security step.
- Fix users registered through an invitation link not being marked as `account_security_completed`.
**First issue:**
Currently the registration flow is broken **when 2FA is disabled** due to the Responsible person Declaration and Creation/Join  filters being triggered in the account security step.
These filters are skipped when 2FA is enabled as, when reached at registration account security point, the user is not "signed in". But when 2FA is disabled, the user is "signed in" and the filters are applied.
In order to solve this we're extending the conditions, so the user needs to have completed its …
=> Bugfix: Registration flow broken when 2FA is disabled

README.md, cosmetics-web/app/views/layouts/_footer.html.erb, cosmetics-web/app/views/layouts/_head.html.erb, cosmetics-web/app/views/layouts/_header.html.erb, cosmetics-web/app/views/responsible_persons/notifications/index.html.erb, cosmetics-web/config/initializers/content_security_policy.rb, cosmetics-web/env.example
One of the outputs of a pentest auditory over the service was the need of setting the Content Security Policy header to decrease the chances of XSS attacks on the service users.
As starting point, we're enabling the CSP in "report only" mode. So the violations of the CSP will be reported to Sentry, but they won't be blocked.
The approach taken has been to add a "nonce" (some sort of id regenerated by each request) tagging the few inline scripts we have and the webpack js scripts. CSP will check that only the scripts with the correct nonce will be allowed to be loaded by the browsers.
So far the configuration we set up in this PR passes the check by Google CSP evaluation tool:
1. Merging it into Staging and monitor warnings there.
2. Remove the "report only mode" so the non allowed sources …
=> Setup Content Security Policy header for reporting (will not block resources)

README.md, cosmetics-web/app/forms/concerns/email_form_validation.rb, cosmetics-web/app/forms/registration/account_security_form.rb, cosmetics-web/app/forms/registration/new_account_form.rb, cosmetics-web/app/forms/resend_secondary_authentication_code_form.rb, cosmetics-web/app/forms/responsible_person_details_form.rb, cosmetics-web/app/forms/secondary_authentication_form.rb, cosmetics-web/app/forms/sign_in_form.rb, cosmetics-web/app/models/search_user.rb, cosmetics-web/app/models/submit_user.rb, cosmetics-web/app/services/invite_search_user.rb, cosmetics-web/app/validators/phone_validator.rb, cosmetics-web/config/constants/international_phone_codes.yml, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/features/account/change_mobile_number_spec.rb, cosmetics-web/spec/features/account/creating_a_search_account_from_an_invitation_spec.rb, cosmetics-web/spec/features/account/submit_sign_up_spec.rb, cosmetics-web/spec/forms/registration/account_security_form_spec.rb, cosmetics-web/spec/forms/resend_secondary_authentication_code_form_spec.rb, cosmetics-web/spec/requests/user_requests_new_secondary_authentication_code_spec.rb, cosmetics-web/spec/validators/phone_validator_spec.rb
[Jira Ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-896)
These changes include:
1. Allow international phone numbers for Submit Users.
2. Only allow UK phone numbers for Search Users.
3. Bring validations to the models, not only on the forms.
4. Align validations with GovUK API phone validations.
5. **Extra**: Refactor locales & form validation errors.
We want to allow Submit users to use international phone numbers.
As we want to avoid allowing users to set a phone number that will be rejected later by GovUK Notify API when trying to send a 2FA SMS, we decided to align our service phone number validations with GovUK Notify ones.
By duplicating the validations in both the forms and model we avoid situations where an user that got its phone number set outside one of the …
=> Change phone validations: Allow international phones. Apply validations everywhere.

README.md
After setting the auth for the service in Staging, I found myself blocked from visiting the page as the credentials weren't accepted.
@slawosz provided the solution as this happened before.
Adding it to the Readme so next person struggling with it will have a clue about what to do when this happens.
=> Add note about CF headers forwarding on Readme

cosmetics-web/app/analyzers/anti_virus_analyzer.rb, cosmetics-web/spec/analyzers/anti_virus_analyzer_spec.rb, cosmetics-web/spec/features/zip_file_upload_notifications_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1001)
While working on refactoring bits of the antivirus-related code in other ticket, noticed that:
1) We don't have specs covering neither the antivirus analyzer nor the end to end flow when detecting a virus in an user uploaded file.
2) The tagging of files with virus error was not happening even when virus are detected. So the end-to-end flow of displaying a notification as "Error" when a virus is detected during the submission was broken.
The analyzer metadata generates a hash with symbols as keys, while the check against the metadata output was using strings as keys.
Because of the non existent key being queried, the check on metadata safety was always returning null value, not false. Hence the Notification File …
=> Bugfix: Antivirus flagging not communicated to users

cosmetics-web/manifest.yml
Pending results of load testing, an initial increase of instance numbers and specs to provide a high availability configuration.
The memory and disk quota increases reflect findings on Product Safety Database which has a similar setup.
=> Increase instance sizes in preparation for live release

cosmetics-web/app/controllers/responsible_persons/additional_information_controller.rb, cosmetics-web/app/controllers/responsible_persons/product_image_upload_controller.rb, cosmetics-web/app/controllers/responsible_persons/wizard/notification_build_controller.rb, cosmetics-web/app/models/image_upload.rb, cosmetics-web/app/models/notification.rb, cosmetics-web/app/views/notifications/_product_details.html.erb, cosmetics-web/app/views/poison_centres/notifications/show_poison_centre.html.erb, cosmetics-web/app/views/responsible_persons/product_image_upload/new.html.erb, cosmetics-web/app/views/responsible_persons/wizard/notification_build/add_product_image.html.erb, cosmetics-web/app/views/shared/_multiple_images_upload_description.html.erb, cosmetics-web/spec/controllers/responsible_persons/notifications_controller_spec.rb, cosmetics-web/spec/factories/image_upload.rb, cosmetics-web/spec/models/image_upload_spec.rb, cosmetics-web/spec/models/notification_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-972)
There was a bug where the image upload page in post-brexit multi-component journey gets into an infinite loop requesting image submission and never moves to the next stage of the flow.
This was caused by:
1) Antivirus over the uploaded file running asynchronously in the background.
2) Business logic enforcing the file to have been checked as "safe from virus" in order to load the next page.
Because at submission point the file is still waiting for the AV check, the virus safety enforcement was never accomplished and the user was being redirected back to the image upload page.
Allow to load the next page when the antivirus check is pending over the image.
Even when the ZIP file contains a multi-component …
=> Fix image upload page for flow with ZIP file containing a multi-component notification

cosmetics-web/app/controllers/responsible_persons/notification_files_controller.rb, cosmetics-web/app/controllers/responsible_persons/wizard/component_build_controller.rb, cosmetics-web/app/controllers/responsible_persons/wizard/notification_build_controller.rb, cosmetics-web/spec/requests/notification_files_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1004)
We detected through our error management/notification system the presence of "blob" files that are detached from any object.
We believe this is caused by the incorrect deletion of attachments and objects with attachments where:
1. Objects with attachments are deleted via `delete` instead of `destroy` calls. Leaving their attachments non deleted.
2. Calls to attachment removal are done via `delete` instead of `purge` or `purge_later`, effectively detaching the associated object from the file blob and, again, not removing the blob.
When we delete a Notification/Component/Any object we want to wipe it, including its associated attachments.
This is achieved by calling `destroy` over the objects (so it triggers …
=> Fix orphan blobs left after file deletion

cosmetics-web/app/controllers/concerns/secondary_authentication_concern.rb, cosmetics-web/spec/features/account/submit_sign_up_spec.rb
https://sentry.io/organizations/beis/issues/2123432557/?project=1398436
https://sentry.io/organizations/beis/issues/2124293995/?project=1398436
https://sentry.io/organizations/beis/issues/2123432557/?project=1398436
When the user has clicked the email link to set up their account, they are able to click various links as shown on the screenshot below:
The main title 'Submit cosmetic product notifications' redirects back to the form, but other links throw an uncaught exception. These should also redirect back to the form.
=> Fix errors when user attempts to navigate away when on the account security setup page

cosmetics-web/app/controllers/users/passwords_controller.rb, cosmetics-web/app/models/search_user.rb, cosmetics-web/app/models/submit_user.rb, cosmetics-web/app/models/user.rb, cosmetics-web/spec/factories/user.rb, cosmetics-web/spec/features/account/forgotten_password_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1014)
[Bugtracker exception](https://sentry.io/organizations/beis/issues/2123481455)
When an user with an incomplete account (missing their mobile number, name or password) attempts a password recovery the service is throwing an error.
Sadly seems some users get confused after introducing their email in the first step of the Submit user registration and, instead
of checking their email for the confirmation link (as prompted), they directly attempt to login, and not having set their password they attempt to reset it.
The cause of the exception is the 2FA attempt prior to the password reset, while the user actually doesn't have a mobile number to send the 2FA code to.
As this bit of the code is shared between Submit and …
=> Bugfix: incomplete accounts trying to reset password

cosmetics-web/deploy.sh, cosmetics-web/manifest.yml
Fixes the worker instances always being scaled to 1, and increases memory to avoid errors such as https://sentry.io/organizations/beis/issues/2126255547/
=> Bump worker memory and apply number of instances correctly

cosmetics-web/app/jobs/notification_file_processor_job.rb, cosmetics-web/spec/factories/notification_file.rb, cosmetics-web/spec/jobs/notification_file_processor_job_spec.rb
So far we have had 24 instances since Sunday of corrupt or invalid zip files being uploaded and failing processing:
https://sentry.io/organizations/beis/issues/2127458135/?project=1398436&query=is%3Aunresolved
This change captures these errors and feeds back to the user so they may correct it.
=> Capture errors when extracting zip file

cosmetics-web/deploy-review.sh, cosmetics-web/deploy.sh
The last two merges have failed to deploy due to timeouts:
https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/runs/1644540742?check_suite_focus=true
https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/runs/1643344223?check_suite_focus=true
This increases the timeout thresholds [as per PSD](https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/deploy.sh). I have set `CF_STARTUP_TIMEOUT` higher due to the higher number of instances.
=> Increase app start timeouts on deployments

cosmetics-web/app/forms/registration/new_account_form.rb, cosmetics-web/spec/features/account/submit_sign_up_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1017)
[Error tracking](https://sentry.io/organizations/beis/issues/2128065615/?project=1398436)
Users were able to register a new account with an email already belonging to another user but with different capitalisation.
This was happening because when saving the user in the new account form we were bypassing the validations for creating a partially completed user. While the business logic to check if the user already exists is using a case sensitive call (find_by) and not detecting that there is already an user with that email.
This caused the user becoming invalid in a later stage when trying to submit their security information to complete the registration.
At that point the email does not pass the validation and the …
=> Avoid duplicated emails with different capitalisation

cosmetics-web/app/controllers/responsible_persons/formulation_upload_controller.rb, cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb, cosmetics-web/app/controllers/responsible_persons/product_image_upload_controller.rb, cosmetics-web/app/controllers/responsible_persons/wizard/component_build_controller.rb, cosmetics-web/app/controllers/responsible_persons/wizard/nanomaterial_build_controller.rb, cosmetics-web/app/controllers/responsible_persons/wizard/notification_build_controller.rb, cosmetics-web/app/controllers/responsible_persons/wizard/trigger_questions_controller.rb, cosmetics-web/spec/controllers/component_build_controller_spec.rb, cosmetics-web/spec/controllers/formulation_upload_controller_spec.rb, cosmetics-web/spec/controllers/nanomaterial_build_controller_spec.rb, cosmetics-web/spec/controllers/notification_build_controller_spec.rb, cosmetics-web/spec/controllers/product_image_upload_controller_spec.rb, cosmetics-web/spec/controllers/responsible_persons/notifications_controller_spec.rb, cosmetics-web/spec/controllers/responsible_persons/trigger_questions_controller_spec.rb
https://regulatorydelivery.atlassian.net/browse/COSBETA-1036
When the user has completed a notification they may subsequently use the browser's history to navigate back to a wizard page for that notification. Rather than throwing an uncaught exception this change redirects the user to the summary page for that notification.
So far we have seen 89 instances of this error in production so this will eliminate future occurrences.
Fixes these issues which can be marked as resolved once deployed:
https://sentry.io/organizations/beis/issues/2123870623/?environment=prod&project=1398436
https://sentry.io/organizations/beis/issues/2124963423/?environment=prod&project=1398436
https://sentry.io/organizations/beis/issues/2124963343/?environment=prod&project=1398436 …
=> Redirect to notification page if already submitted when attempting to access wizard pages

cosmetics-web/app/views/layouts/_footer.html.erb
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-950
Ensure all links in the footer open in new tab.
=> Ensure all links in the footer open in new tab

cosmetics-web/app/controllers/responsible_persons/additional_information_controller.rb, cosmetics-web/spec/controllers/additional_information_controller_spec.rb
https://regulatorydelivery.atlassian.net/browse/COSBETA-1036
When the user creates a manual notification they may navigate through the history back to the additional information pages of the notification wizard. Instead of throwing an uncaught exception this change will redirect the user to the notification's summary page.
This will resolve https://sentry.io/organizations/beis/issues/2135407690/?project=1398436.
=> Redirect on additional info pages when notification complete

cosmetics-web/app/views/responsible_persons/wizard/component_build/_exact_concentration.html.erb, cosmetics-web/app/views/responsible_persons/wizard/component_build/_ranges_concentration.html.erb
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-968
Amending text that references the ‘National Poison Information Service’ needs to be changed to the ‘National Poisons Information Service'. - plural on ‘Poisons’
=> Pluralise poison in National Poisons Information Service

cosmetics-web/app/views/responsible_persons/wizard/component_build/select_frame_formulation.html.erb
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1018
Predefined frame formulation on frame formulation page not working - this commit removes it as per the jira ticket
=> Remove download link to predefined frame formulations

cosmetics-web/app/views/responsible_persons/account_wizard/select_type.html.erb
[Sentry related error](https://sentry.io/organizations/beis/issues/2052277308)
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1047)
When a user belonging to multiple RP reached this page before having selected their current RP, the backlink route was throwing an exception.
Fixed by pointing the backlink to the RP selection when the user has multiple RPs, none of them is defined as their current one.
=> Fix back link from new RP type selection

cosmetics-web/app/views/layouts/_header.html.erb
In [PR 1915](https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/pull/1915) I accidentally made a change that allowed users in the process of signing up to use links in the header to redirect to the home page, but not users that had signed up and confirmed their phone/email. This PR fixes this so that users who are in the sign up flow cannot use the header links but fully signed up users can.
=> Allow logged in and verified users to correctly use header links

cosmetics-web/app/analyzers/master_analyzer.rb
We are already rescuing the `Aws::S3::Errors::NotFound` exception. `Aws::S3::Errors::NoSuchKey` is also analogous to a 404 HTTP response so the same action should be taken.
I have checked a few of the most recent instances in production. In all cases the matching `ActiveStorage::Blob` record does not exist. Clearly it must have existed given it had an ID and the analyzer job was scheduled.
Most likely this occurs as a result of race conditions. There are a few places where we call `purge` on a blob if it fails validation. It is likely these analyzer jobs are trying to download these files.
Therefore I do not think this error is affecting users, but it is the most common exception being reported currently.
I did not modify the spec as it would just be a repeat of the existing one.
=> Rescue 404 errors when downloading file from S3

cosmetics-web/app/models/contact_person.rb, cosmetics-web/app/validators/phone_validator.rb, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/support/feature_helpers.rb, cosmetics-web/spec/validators/phone_validator_spec.rb
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1026
This PR adds validation to the phone number field on the contact details page.
I have made changes to the `phone_validator` class because we need to allow british landlines in this case, not strictly mobile phones (which is necessary validation for 2fa).
=> Validate phone numbers on contact details page

cosmetics-web/app/controllers/responsible_persons/wizard/component_build_controller.rb, cosmetics-web/app/helpers/component_build_helper.rb, cosmetics-web/app/views/notifications/_component_details.html.erb, cosmetics-web/spec/controllers/component_build_controller_spec.rb, cosmetics-web/spec/features/manual_pre_brexit_notifications_spec.rb, cosmetics-web/spec/support/feature_helpers.rb
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-987
After this change:
- users will not have the option to select how they want to give a cosmetic product formulation if they have notified before Jan 1st 2021 - they will go straight to the choose frame formulation page.
- Show poisonous ingredients file in check your answers page if user has uploaded this file.
- Make poisonous ingredients upload file non-mandatory if user notified after jan 1st.
- Link to upload poisonous ingredients file if user selects `yes` to poisonous ingredients but does not upload the file and has notified after jan 1st.
=> Don't allow users to have the option to select how they want to give a cosmetic product formulation

cosmetics-web/Gemfile, cosmetics-web/Gemfile.lock, cosmetics-web/app/models/contact_person.rb, cosmetics-web/app/models/pending_responsible_person_user.rb, cosmetics-web/app/models/user.rb, cosmetics-web/app/validators/email_validator.rb, cosmetics-web/app/views/responsible_persons/contact_persons/_form.html.erb, cosmetics-web/config/initializers/devise.rb, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/forms/sign_in_form_spec.rb, cosmetics-web/spec/models/contact_person_spec.rb, cosmetics-web/spec/validators/email_validator_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1061)
We had multiple occurrences of clearly wrong emails being accepted by our validations and failing when Notify service attempted to use the address.
The validate_email gem was severely deprecated, and its validation was so relaxed that was accepting emails like
`user @example.co,m`, `user @ example . com`...
The gem's only value was to define a custom email validator that checked that the email address could be parsed and that the email address domain is not local (`user@example`).
The approach taken was to remove the gem, create our own custom email validator reproducing the gem behaviour, and extend the validator to check the email against accepted email format REGEXP.
To validate the email format we are using …
=> Introduce stricter email format validation

cosmetics-web/app/views/responsible_persons/contact_persons/new.html.erb
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1024
Fix responsible person bug which causes page 2 of the form to loop
=> Fix responsible person bug which causes page 2 of the form to loop

cosmetics-web/app/models/component.rb, cosmetics-web/app/views/notifications/_component_details.html.erb, cosmetics-web/spec/models/component_spec.rb
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1063
- Submitted notifications (for manual pre-brexit) should not show link to upload poisonous ingredients
- Do not auto populate contains poisonous ingredients to no
=> Bugs related to pre brexit poisonous ingredients flow

cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb, cosmetics-web/app/controllers/responsible_persons/wizard/nanomaterial_build_controller.rb, cosmetics-web/app/controllers/responsible_persons/wizard/notification_build_controller.rb, cosmetics-web/app/controllers/responsible_persons/wizard/trigger_questions_controller.rb, cosmetics-web/app/helpers/component_build_helper.rb, cosmetics-web/app/views/responsible_persons/notification_files/new.html.erb, cosmetics-web/spec/factories/notification.rb, cosmetics-web/spec/features/manual_post_brexit_notifications_spec.rb, cosmetics-web/spec/features/manual_pre_brexit_notifications_spec.rb, cosmetics-web/spec/features/zip_file_upload_notifications_spec.rb, cosmetics-web/spec/requests/check_your_answers_page_spec.rb, cosmetics-web/spec/support/feature_helpers.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-962)
There are many steps in our notification flows where the backlinks are pointing to the wrong place.
This PR does:
- Extend the feature tests covering the notification flows to include assertions over each of steps backlink.
- Fix multiple backlinks to point where they should.
- We recently moved the "upload image". Since that change, none of the pre-EU exit notifications should go through that step, and no backlink in any of the pre-EU exit notification flow should point to "upload image" page. For the flows that have the "upload image" step, it is not the last step anymore. We needed to fix both issues in multiple spots.
- Fixed nanomaterial steps backlinks for both manual and zip flows.
- Backlinks on questions …
=> Fix back links through notification flows

cosmetics-web/deploy.sh, cosmetics-web/manifest.yml
Reverts UKGovernmentBEIS/beis-opss-cosmetics#1956
The maximum configurable timeout for CloudFoundry is 180 seconds. Trying to increase it resulted in a failure.
=> Revert "Increase production deploy timeouts"

.github/workflows/deploy.yml, cosmetics-web/deploy.sh, cosmetics-web/manifest.yml
Staging is having 8 web and 4 worker instances as Production. This is a massive and costly overallocation of resources.
Did set it to 2 instances just to be able to reproduce "having multiple web/worker instances" as production.
=> Reduce Staging app instances in CloudFoundry

cosmetics-web/Gemfile, cosmetics-web/Gemfile.lock, cosmetics-web/deploy.sh
1. Temporally disable Scout gem
Scout start time is being very slow and possibly causing deployment timeout issues.
2. Restore the previous value for the app startup timeout.
This wasn't the issue but individual instances crashing.
=> Deployment issues fix attempts

cosmetics-web/app/services/notification_delete_service.rb, cosmetics-web/db/migrate/20210128101635_add_reference_number_to_notification_delete_logs.rb, cosmetics-web/db/schema.rb, cosmetics-web/spec/services/notification_delete_service_spec.rb
Reference number is used to identify notification.
=> Add reference number to notification delete log

cosmetics-web/app/controllers/responsible_persons/wizard/nanomaterial_build_controller.rb, cosmetics-web/app/helpers/nanomaterial_helper.rb, cosmetics-web/app/models/nano_element.rb, cosmetics-web/app/views/responsible_persons/wizard/nanomaterial_build/confirm_restrictions.html.erb, cosmetics-web/app/views/responsible_persons/wizard/nanomaterial_build/must_be_listed.html.erb, cosmetics-web/app/views/responsible_persons/wizard/nanomaterial_build/must_conform_to_restrictions.html.erb, cosmetics-web/app/views/responsible_persons/wizard/nanomaterial_build/non_standard_nanomaterial_notified.html.erb, cosmetics-web/app/views/responsible_persons/wizard/nanomaterial_build/notify_your_nanomaterial.html.erb, cosmetics-web/app/views/responsible_persons/wizard/nanomaterial_build/when_products_containing_nanomaterial_can_be_placed_on_market.html.erb, cosmetics-web/spec/controllers/nanomaterial_build_controller_spec.rb, cosmetics-web/spec/models/nano_element_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-985)
Product nanomaterials flow got multiple tweaks:
**Original flow**: The steps on the flow asking about regulation listing and conformance with restrictions from the standard purposes Annexes get bypassed.
**New flow**: User goes through both steps instead of landing directly into the question about having submitted a notification about the nanomaterial since the end of the transition period.
- is not listed in the annexes for its standard purposes.
- is not conforming with the restrictions defined in the annexes for its standard purposes.
References to "Brexit" and "GB" have been replaced with the date of the end of the transition period (1 Jan 20201) and "UK" in:
- "When you can place products containing …
=> Update nanomaterials flow

.github/workflows/deploy.yml, cosmetics-web/config/database.yml, cosmetics-web/config/puma.rb
Achieve the same concurrency by reducing puma workers and increasing puma threads.
We're attempting to reduce the app start time since now is timing out while starting up Puma and we suspect may be related by having 8 puma workers.
Our CF instances have 2 CPU cores x 2 Thread per core. It is usually recommended to adjust the number of Puma workers to match the number of CPU cores. Following that "rule" probably we should AIM for 3-4 workers maximum.
=> Tweak Puma production concurrency

.github/workflows/deploy.yml, cosmetics-web/config/database.yml, cosmetics-web/config/environments/production.rb, cosmetics-web/config/puma.rb
By removing Elastic Search indexing on prod application boot.
The production start time of rails has become  slower until the point of reaching the timeout for the health checks
and causing deployments to fail.
After tracing a Rails console start, was discovered that the long boot time (a couple of minutes at this point) was caused by ES indexing over a DB that keeps increasing in size.
Reverting Puma concurrency tweaks as Puma config had nothing to do with the boot time issues.
=> Fix Production Rails booting time issues

cosmetics-web/Gemfile, cosmetics-web/Gemfile.lock
It was disabled as we thought it was causing slow app startup, but we resolved the issue. It became clear that this was unrelated to Scout.
=> Re-enable Scout

cosmetics-web/app/models/component.rb, cosmetics-web/app/services/cpnp_parser.rb, cosmetics-web/spec/models/component_spec.rb
Solves the bug with a looping formulation file. https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-1099
=> Allow imported components to have same name

cosmetics-web/app/models/component.rb
The difference between float numbers had a precision issue that caused
the result failing the comparison when it shouldn't.
Eg: 8.3 - 7.3 => 1.0000000000000009
Rounding the result to avoid this.
=> Fix float precision issue on validation

cosmetics-web/app/helpers/trigger_rules_helper.rb
Fixes the second issue raised on [Jira ticket 1095](https://regulatorydelivery.atlassian.net/browse/COSBETA-1095)
Some CPNP export files contain Trigger Questions with empty elements (no name, no value).
The file import works ok, but then, when trying to display them, the service attempts to format the answers/values and blows up.
=> Fix: Error when Trigger Question has empty elements

cosmetics-web/app/views/users/expired_invitation.html.erb
[Bugtracking issue](https://sentry.io/organizations/beis/issues/2234638125/?project=1398436)
Users being redirected to the "Invitation Expired" page when following an expired link for registering a Search User are landing into a service exception.
The page is meant for Search users, and the constant is defined in the SearchUser model.
It was causing an exception when attempting to access it from the User model where the constant is not defined.
=> Fix undefined constant on invitation expired page

.github/workflows/rubocop.yml, .github/workflows/tests.yml, cosmetics-web/Gemfile.lock, cosmetics-web/manifest.review.yml, cosmetics-web/manifest.yml, cosmetics-web/package.json
- Bundler 2.2.11
- Node 10.24.0
- Rubygems 3.2.11
https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.8.26
=> Upgrade Cloud Foundry Ruby buildpack to v1.8.32

cosmetics-web/app/models/search_user.rb, cosmetics-web/app/models/submit_user.rb
When [testing the deletion of users in staging](https://regulatorydelivery.atlassian.net/browse/COSBETA-1033) found multiple ActiveRecord issues with foreign keys while trying to run the `user.destroy` callbacks.
Errors:
```
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column notification_files.submit_user_id does not exist)
LINE 1: ...fication_files".* FROM "notification_files" WHERE "notificat...
^
: SELECT "notification_files".* FROM "notification_files" WHERE "notification_files"."submit_user_id" = $1
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column pending_responsible_person_users.creator_id does not exist)
LINE 1: ...".* FROM "pending_responsible_person_users" WHERE "pending_r...
^
: SELECT "pending_responsible_person_users".* FROM …
```
=> BugFix: Active Record user associations for User destroy callbacks

cosmetics-web/app/controllers/concerns/manual_notification_concern.rb, cosmetics-web/app/controllers/responsible_persons/additional_information_controller.rb, cosmetics-web/app/controllers/responsible_persons/wizard/component_build_controller.rb, cosmetics-web/app/controllers/responsible_persons/wizard/notification_build_controller.rb, cosmetics-web/app/controllers/responsible_persons/wizard/trigger_questions_controller.rb, cosmetics-web/app/helpers/component_build_helper.rb, cosmetics-web/app/models/component.rb, cosmetics-web/app/models/notification.rb, cosmetics-web/app/views/notifications/_product_details.html.erb, cosmetics-web/spec/controllers/additional_information_controller_spec.rb, cosmetics-web/spec/controllers/component_build_controller_spec.rb, cosmetics-web/spec/controllers/notification_build_controller_spec.rb, cosmetics-web/spec/factories/notification.rb, cosmetics-web/spec/features/zip_file_upload_notifications_spec.rb, cosmetics-web/spec/models/notification_spec.rb, cosmetics-web/spec/requests/check_your_answers_page_spec.rb, cosmetics-web/spec/requests/nanomaterial_within_product_requests_spec.rb, cosmetics-web/spec/requests/trigger_questions_requests_spec.rb, cosmetics-web/spec/services/cpnp_notification_importer_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1117)
This is a following from https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/pull/2037 where we unified the pre-post EU exit manual flows into a single flow with the same steps and removed the pre-post EU exit question.
While the previous ticket removed the question in the manual flow and defaulted all the manual notifications to post EU exit, this PR effectively **removes the logic branching that causes different flows/behaviour for pre and post EU exit notifications**.\
It mainly affects the ZIP notifications flow.
Removes code, makes the codebase simpler and its maintainers happier :)
=> Remove different behaviour for pre/post EU exit notifications

cosmetics-web/app/views/responsible_persons/formulation_upload/new.html.erb, cosmetics-web/app/views/responsible_persons/wizard/component_build/_exact_concentration.html.erb, cosmetics-web/app/views/responsible_persons/wizard/component_build/_ranges_concentration.html.erb, cosmetics-web/app/views/responsible_persons/wizard/component_build/upload_formulation.html.erb
For multicomponent notifications, the page will show the name of the component we're uploading the formulation for.
=> Add Component name to formulations page on multi-component notifications

cosmetics-web/app/controllers/my_account_password_controller.rb, cosmetics-web/spec/jobs/notification_file_processor_job_spec.rb, cosmetics-web/spec/rails_helper.rb
Our RSpec runs output is quite noisy. 
This PR brings some changes to clean it up:
- Suppress Sidekiq log output on specs.
- Upgrade from deprecated Devise option.
- Remove warning on false positives for expectations on errors not being raised.
=> Reduce RSpec output noise

cosmetics-web/app/helpers/analyzer_helper.rb
Related bug: https://sentry.io/organizations/beis/issues/2299104977/
There are some cases where the blob reaches the ActiveStorage analyzer not having an attachment associated.
There is code guarding in further steps for the case where the Notification File hasn't been found. But the issue is being triggered
on the notification file search before this stage, so we need to guard against it.
Seems this situation of "Blob without attachment" occurs when the blob has been removed from DB but is still on memory for ActiveStorage analyzer purposes.
I guess this because I searched some of the ActiveStorage::Blob causing the exceptions and none of them were found in DB.
=> Fix analyzer exception when missing blob attachment

cosmetics-web/Gemfile, cosmetics-web/Gemfile.lock, cosmetics-web/app/models/notification.rb, cosmetics-web/app/views/application/_registered_product.html.erb, cosmetics-web/db/migrate/20210330090803_add_notification_complete_at_to_notifications.rb, cosmetics-web/db/schema.rb, cosmetics-web/spec/controllers/responsible_persons/notifications_controller_spec.rb, cosmetics-web/spec/factories/notification.rb, cosmetics-web/spec/features/notifications_deleting_spec.rb, cosmetics-web/spec/models/notification_spec.rb
Add a timestamp to the "Notification complete" state on the notification state machine.
It does:
- Add a field to DB that matches the state in the state machine.
- Backfills the field for all the already completed notifications.
As the notifications cannot be edited once completed/submitted, the
updated_at timestamp is used for the backfill.
- Sets AASM option to automatically set the timestamp when the
Notification transitions to the "notification_complete" state.
=> Fix 7 day window to delete notification after submission

cosmetics-web/app/services/cpnp_notification_importer.rb, cosmetics-web/spec/services/cpnp_notification_importer_spec.rb
Bug: https://sentry.io/organizations/beis/issues/2306373786/
When the `cpnp_notification_date` is missing in the parser, the importer is raising an exception as it tries to compare a "nil" value against a date.
To resolve this, the comparison will only happen if cpnp_notification_date is present, defaulting to a false value for `Notification#was_notified_before_eu_exit` if not.
Also done some minor refactors on the Importer class.
=> BugFix: CPNP importer with missing parsing date

cosmetics-web/app/controllers/guidance_controller.rb, cosmetics-web/app/views/guidance/how_to_set_up_authenticator_app.html.erb, cosmetics-web/app/views/layouts/_footer.html.erb, cosmetics-web/config/routes.rb, cosmetics-web/spec/requests/guidance_pages_spec.rb
[Jira Ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1118)
Not much to say, we're adding a guidance page for the authenticator app set up.
=> Add "set up of authenticator app" to guidance pages

cosmetics-web/app/views/responsible_persons/account_wizard/create_or_join_existing.html.erb, cosmetics-web/app/views/responsible_persons/account_wizard/overview.html.erb, cosmetics-web/app/views/responsible_persons/contact_persons/_form.html.erb
Minor content changes:
- Regulations link changed.
- Replaced 'Brexit' with EU exit date.
- Couple of acronym wording changes.
=> Updates to account registration pages

cosmetics-web/app/controllers/concerns/secondary_authentication_concern.rb, cosmetics-web/app/controllers/registration/new_accounts_controller.rb, cosmetics-web/app/controllers/secondary_authentication/app_controller.rb, cosmetics-web/app/controllers/secondary_authentication/method_controller.rb, cosmetics-web/app/controllers/secondary_authentication/sms/resend_controller.rb, cosmetics-web/app/controllers/secondary_authentication/sms_controller.rb, cosmetics-web/spec/requests/secondary_authentication/user_requests_new_secondary_authentication_sms_code_spec.rb
[Fixes COSBETA-1128](https://regulatorydelivery.atlassian.net/browse/COSBETA-1128)
**TLDR:** There were two issues causing the previous user 2FA session to take over a new user session. One was the storing of the 2FA method selection into the session (that was unnecessary) and the second was the fact that the user session wasn't being wiped when creating a new user.
- Remove usage of the user session for recording the secondary authentication methods selection when multiple options are available.
- Enforce the secondary authentication to have been triggered as a condition to allow access to "Resend secondary authentication SMS code".
- **Bugfix**: Cleans previous user session when initiating new user registration.
When the user has multiple methods configured for secondary authentication, …
=> Secondary authentication: Remove 2FA method memorisation from session. Fix previous 2FA session polluting Registration

cosmetics-web/app/controllers/my_account/email_controller.rb
[Bug ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1133)
When the user:
- already had a new email confirmation token.
- attempts again to change their email.
The change email address confirmation email sent uses the previous confirmation token stored in DB instead of the one generated for the new request. 
This results in an "Email can not be changed. Confirmation token invalid" error when the user follows the link from the confirmation email.
To avoid that, we're refreshing the user in memory before dispatching the confirmation email.
=> Fix email change confirmation sending old token

cosmetics-web/app/services/invite_search_user.rb, cosmetics-web/app/services/one_off/email.rb, cosmetics-web/spec/services/invite_search_user_spec.rb
This PR does:
1. Fix an issue when parsing emails from the CSV file for the bulk inviter.
2. Logs when trying to invite an email address corresponding to a registered user.
The emails parsed from the CSV file contain "end of line" symbols, like `user@example.org\n`.
This causes issues when attempting to re-invite users: 
- The user inviter attempts to find an existent user by email using `user@example.org\n`. 
- Does not find it because of the end of line difference, as the existent user email is `user@example.org`.
- The service attempts to create a new user with `user@example.org\n` but fails validation.
- Service fails and does not send the invitation.
=> Search user bulk inviter tweaks

cosmetics-web/app/controllers/my_account/email_controller.rb, cosmetics-web/app/models/concerns/new_email_concern.rb, cosmetics-web/spec/models/user/new_email_concern_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1133)
Users are requesting to change their email and receiving confirmation links with invalid tokens.
These tokens seem to be the previous token that was changed with the new email request. So, instead of receiving the newly generated token, users receive the token that was previously set and is no longer valid.
Change of token and mailer sending the new email confirmation link was under the same DB transaction block.
When code is wrapped into an Active Record transaction block, changes are not written in DB until the full transaction block has been run successfully.
This means that when the mailer is called inside the transaction, even when the `#save!` has been called, the DB value has not been updated as the …
=> Bugfix: New email confirmation link using outdated token

README.md, cosmetics-web/app/controllers/active_storage/blobs/proxy_controller.rb, cosmetics-web/app/controllers/active_storage/representations/proxy_controller.rb, cosmetics-web/app/controllers/concerns/active_storage_access_protection_concern.rb, cosmetics-web/app/views/poison_centres/notifications/show_poison_centre.html.erb, cosmetics-web/spec/requests/assets_security_spec.rb
[Ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1154)
Image thumbnails were broken for search users due to the active storage route being disabled (re-routed to "/").
Enabled the route and overwrote the ActiveStorage representations proxy controller to add an access policy to the images.
=> Bugfix: Broken product image thumbnails in notification pages for search users

cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb
The default pagination order based on "created_at" causes notifications that
were created days ago but completed recently not be displayed as the first
pagination results.
We want to order the results by the completion date/time. So the user will
be shown what notifications were notified most recently.
Example of affected results:
=> Paginate registered notifications by completion

cosmetics-web/spec/analyzers/anti_virus_analyzer_spec.rb
This method was triggering deprecation warnings during spec runs.
The new method keeps the same interface but ensures the blob instance to be saved before the upload starts to avoid key collisions on uploads.
[Rails doc reference](https://edgeapi.rubyonrails.org/classes/ActiveStorage/Blob.html#method-c-create_after_upload-21)
=> Upgrade ActiveStorage::Blob deprecated method

cosmetics-web/Gemfile, cosmetics-web/Gemfile.lock, cosmetics-web/app/decorators/notification_decorator.rb, cosmetics-web/app/models/notification.rb, cosmetics-web/db/migrate/20210604114734_add_csv_cache_to_notifications.rb, cosmetics-web/db/schema.rb, cosmetics-web/spec/decorators/notifications_decorator_spec.rb, cosmetics-web/spec/factories/notification.rb, cosmetics-web/spec/models/notification_spec.rb
Cache categories in `Notification` so they are being generated faster. After deployment, `#cache_categories_for_csv!` needs to be called on each completed notification.
=> Faster CSV generation

cosmetics-web/app/controllers/responsible_persons/wizard/notification_build_controller.rb, cosmetics-web/app/models/component.rb
We have a flaky spec caused by the backlink to the last component question pointing to the wrong PH page.
When running the feature specs, the Notification last component is sometimes in an "empty" state, while the completed component is not the last anymore.
Because of that, the wizard page, after adding a component, incorrectly builds the backlink.
To fix this, the backlink on that wizard page uses the last "completed" component.
=> Fix flaky back link test

cosmetics-web/deploy-github-functions.sh
Brought from [PSD](https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/1428)
> "Dependabot PRs no longer have access to GitHub repo secrets, preventing the review application from deploying when Dependabot (or any other third party) opens a PR.
> A user with write access to the repo needs to update the branch to trigger a successful review app deploy.
> 
> This fixes some bugs in the actions script which allowed the action to continue executing after an error had occurred.
> Now the action will fail immediately."
=> Do not attempt deployments for dependabot PRs

cosmetics-web/app/controllers/users/passwords_controller.rb, cosmetics-web/app/forms/registration/new_account_form.rb, cosmetics-web/spec/features/account/forgotten_password_spec.rb, cosmetics-web/spec/features/account/submit_sign_up_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1174)
[Related error tracking](https://sentry.io/organizations/beis/issues/2441301077/)
Invited Submit users have no name until their complete their account security setup. When trying to send them a confirmation email that depends on the name, the mailer throws an exception.
Fixed by re-sending them the invitation email instead.
Some Submit invited users who followed the invitation link but didn't complete their registration were attempting to either:
- create a new account.
- reset their password.
Both situations were triggering the "resend user confirmation email" intended for users who initiated the registration but didn't complete their account security setup to be pointed to complete their registration.
This email …
=> Fix errors when sending confirmation email to invited Submit users who didn't finish their account setup

cosmetics-web/app/controllers/responsible_persons/additional_information_controller.rb, cosmetics-web/app/controllers/responsible_persons/formulation_upload_controller.rb, cosmetics-web/app/controllers/responsible_persons/wizard/nanomaterial_build_controller.rb, cosmetics-web/app/views/notifications/_component_details.html.erb, cosmetics-web/app/views/notifications/_component_details_formulation_ingredients.html.erb, cosmetics-web/app/views/responsible_persons/formulation_upload/_head.html.erb, cosmetics-web/app/views/responsible_persons/formulation_upload/_instructions.html.erb, cosmetics-web/app/views/responsible_persons/formulation_upload/edit.html.erb, cosmetics-web/app/views/responsible_persons/formulation_upload/new.html.erb, cosmetics-web/app/views/responsible_persons/wizard/component_build/upload_formulation.html.erb, cosmetics-web/config/routes.rb, cosmetics-web/spec/controllers/additional_information_controller_spec.rb, cosmetics-web/spec/factories/component.rb, cosmetics-web/spec/features/editing_draft_notifications_before_submission_spec.rb, cosmetics-web/spec/requests/nanomaterial_within_product_requests_spec.rb, cosmetics-web/spec/support/feature_helpers.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1183)
Allow changing the component formulation file before completing the notification.
The notification draft prior to confirmation will have a link in each component formulation file that will point to a page where the current file can be removed and a new file uploaded.
=> Allow to replace formulation files before completing notifications

cosmetics-web/app/controllers/concerns/active_storage_access_protection_concern.rb, cosmetics-web/app/controllers/nanomaterial_notifications_controller.rb, cosmetics-web/app/models/component.rb, cosmetics-web/app/models/image_upload.rb, cosmetics-web/app/views/nanomaterial_notifications/index.html.erb, cosmetics-web/app/views/nanomaterial_notifications/show.html.erb, cosmetics-web/app/views/responsible_persons/account_wizard/select_type.html.erb, cosmetics-web/config/routes.rb, cosmetics-web/spec/factories/nanomaterial_notification.rb, cosmetics-web/spec/features/nanomaterial_notifications_spec.rb, cosmetics-web/spec/requests/nanomaterial_notifications_spec.rb
For the given nanomaterial notification the page will display:
- Name
- Nanomaterial number
- Date when was notified in the UK
- Date when was notified in the EU (if notified in the EU)
- Link to download PDF file.
=> Add nanomaterial notifications pages

cosmetics-web/db/seeds.rb
Instead of sending Search users invitations with every newly seeded Review App, seeds will create completely registered users with the same credentials as the Submit ones.
=> Create fully registered Search users in the seeds

cosmetics-web/Gemfile, cosmetics-web/Gemfile.lock, cosmetics-web/app/views/responsible_persons/account_wizard/enter_details.html.erb, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/forms/responsible_persons/details_form_spec.rb, cosmetics-web/spec/support/feature_helpers.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1227)
Redesign and unify the Responsible Person "enter details" page.
This page now includes a dropdown with information, an alert message and
adds text hints to name and address fields.
=> Redesign RP enter details page

cosmetics-web/app/views/poison_centres/notifications/show_msa.html.erb, cosmetics-web/app/views/poison_centres/notifications/show_poison_centre.html.erb, cosmetics-web/app/views/responsible_persons/notifications/show.html.erb
https://regulatorydelivery.atlassian.net/browse/COSBETA-988
When searching product notifications and selecting one, every page title was the same regardless of the product selected. This PR includes the product name in the page title, so that the title reflects the content of the page. This is particuarly helpful for users who use a screenreader.
=> Make product page titles reflect the product they are showing

cosmetics-web/lib/tasks/elasticsearch.rake, cosmetics-web/manifest.review.yml
Search Cosmetics on Review Apps is failing to load the notifications page (500 error) due to a missing Elastic Search index.
This forces developers to connect to the review app console and manually reindex ES.
We're automating this to happen on deploy by adding a task triggering the reindex job and calling that task on the review app deploys manifest.
=> Reindex Elastic Search for each Review App deploy

cosmetics-web/app/controllers/responsible_persons/wizard/notification_build_controller.rb
When reaching the page for a draft complete notification but not having
available completed components, the backlink generation was causing
an exception.
There is no point in trying to load the last component trigger
question page when there is no "last component".
Sentry related exceptions [1](https://sentry.io/organizations/beis/issues/2602567600/?project=1398436) and [2](https://sentry.io/organizations/beis/issues/2602567571/?project=1398436)
=> Fix add component page back-link raising exceptions

cosmetics-web/db/seeds.rb
The original password would fail validation due to being too common.
=> Fix passwords on seeds for Submit Users

cosmetics-web/app/forms/registration/new_account_form.rb, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/features/account/submit_sign_up_spec.rb
Spammers are using the confirmation emails to send spam to users email addresses. As GOVUK is a trusted address they use the user name to inject spam messages and URLs.
We're blocking certain characters from being used on user names during registration.
=> Avoid spam on registration confirmation emails

cosmetics-web/app/views/responsible_persons/wizard/nanomaterial_build/_cannot_notify.html.erb, cosmetics-web/app/views/responsible_persons/wizard/nanomaterial_build/must_be_listed.html.erb, cosmetics-web/app/views/responsible_persons/wizard/nanomaterial_build/must_conform_to_restrictions.html.erb
[Jira ticket 1288](https://regulatorydelivery.atlassian.net/browse/COSBETA-1288)
Update the guidance content for the pages displayed as dead ends when a nanomaterial does not match a condition to be notified.
Extracted the shared template between both pages as only a paragraph changes between them.
https://cosmetics-pr-2309-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2309-search-web.london.cloudapps.digital/
=> Update "cannot notify nanomaterial" pages

cosmetics-web/app/helpers/responsible_persons/notifications_helper.rb, cosmetics-web/app/views/notifications/_product_details_label_images.html.erb
[Jira ticket 1312](https://regulatorydelivery.atlassian.net/browse/COSBETA-1312)
- When there is an individual image, it won't be wrapped inside a list.
- When having multiple images, they will be listed with bullet points.
- When the image is waiting for antivirus check, don't wrap the text
with a paragraph but within a list element.
- Extracted as a helper the code generating the label image link so
can be re-used in different blocks.
https://cosmetics-pr-2313-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2313-search-web.london.cloudapps.digital/
=> Change image label HTML on notification summary

cosmetics-web/app/controllers/responsible_persons/invitations_controller.rb, cosmetics-web/app/controllers/responsible_persons/team_members_controller.rb, cosmetics-web/app/views/responsible_persons/invitations/cancel.html.erb, cosmetics-web/app/views/responsible_persons/invitations/new.html.erb, cosmetics-web/app/views/responsible_persons/team_members/index.html.erb, cosmetics-web/config/routes.rb, cosmetics-web/spec/controllers/responsible_persons/team_members_controller_spec.rb, cosmetics-web/spec/features/inviting_a_colleague_spec.rb, cosmetics-web/spec/requests/responsible_person_access_spec.rb, cosmetics-web/spec/requests/responsible_persons/invitations_spec.rb, cosmetics-web/spec/requests/responsible_persons/team_members_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1293)
Allowing Responsible Person users to cancel pending invitations to their Responsible Person.
Invitation routes have been refactored, so now we have:
- `/responsible_person/:rp_id/invitations/new` to add a new invitation from the team members page.
- `/responsible_person/:rp_id/invitations/:inv_id/resend` to resend an existing invitation.
- `/responsible_person/:rp_id/invitations/:inv_id/cancel` to cancel an invitation.
Team members controller now is only in charge of:
- listing the team members and pending invitations
- enable people with invitation links to join the team/RP.
The cancel invitation button is now available on the team members page:
Clicking on it takes the user to a confirmation page:
User is …
=> Allow users to cancel invitations to their Responsible Person

cosmetics-web/app/views/nanomaterial_notifications/notified_to_eu.html.erb, cosmetics-web/app/views/responsible_persons/select.html.erb
[Jira 1249](https://regulatorydelivery.atlassian.net/browse/COSBETA-1249)
Fix error display/ error summary messages anchoring in two forms/pages:
1 - Responsible person selection form.
2 - When adding a nanomaterial. The form/page asking about if/date when was notified to the EU.
In 2 pages:
https://cosmetics-pr-2320-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2320-search-web.london.cloudapps.digital/
=> Fix radio buttons error anchoring

cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb, cosmetics-web/spec/requests/notifications_page_spec.rb
[Jira ticket 1171](https://regulatorydelivery.atlassian.net/browse/COSBETA-1171
)
The Notifications CSV export was ordering the notifications ascending by their creation date.
We want to show the most recently submitted notifications first, so the order has been changed to load the notifications from most recently
completed to older ones.
https://cosmetics-pr-2326-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2326-search-web.london.cloudapps.digital/
=> Order Notifications CSV by completion date

cosmetics-web/app/views/poison_centres/notifications/_filters.html.erb
[Jira ticket 1330](https://regulatorydelivery.atlassian.net/browse/COSBETA-1330)
Instead of displaying a blank selection with non-text when the filters
do not include a specific category, we want to display "All".
https://cosmetics-pr-2327-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2327-search-web.london.cloudapps.digital/
=> Rename blank category as "All" in Search filters

cosmetics-web/app/helpers/responsible_persons/notifications_helper.rb, cosmetics-web/app/views/poison_centres/notifications/_results.html.erb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1341)
These terms don't need to have a title as their meaning is common knowledge and the title information can be noisy for screen readers.
https://cosmetics-pr-2343-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2343-search-web.london.cloudapps.digital/
=> Remove obvious UK/EU html abbr tag titles

cosmetics-web/app/helpers/component_build_helper.rb
[Associated error in bug tracking software](https://sentry.io/organizations/beis/issues/2873987414/?project=1398436&query=is%3Aunresolved)
The logic for the backlink path generation was assuming that when a nanomaterial is present in the component, there will be nanoelements associated with the nanomaterial.
This is not the case for some imported notifications.
When these notifications are drafts, the user still can navigate through their flow.
The service was throwing exception for those cases as "last_nanoelement.standard?" was trying to call a method over a "nil" object.
To resolve it, the branch condition asserts over the presence of a nano element.
=> Bugfix: back-link for nanomaterial without nanoelements

cosmetics-web/app/controllers/frame_formulations_controller.rb
When the wrong ID or SubID is given in the URL for the frame formulation page, instead of assuming the formulation/subformulation are found and trying to load the template, will redirect to 404 page, treating it as an ActiveRecord "not found" situation.
Noticed this after an attempt of SQL attack against this controller, passing SQL commands as ID/SUBID parameters.
The attack had no danger (especially as this controller does not query the DB), but caused 500 errors in the service that brought attention to the need to redirect to 404 instead.
Related Sentry issues:
- https://sentry.io/organizations/beis/issues/2908098191/?project=1398436
- https://sentry.io/organizations/beis/issues/2908098178/?project=1398436
https://cosmetics-pr-2347-submit-web.london.cloudapps.digital/ …
=> Guard against missing frame formulations IDs

cosmetics-web/Gemfile, cosmetics-web/Gemfile.lock, cosmetics-web/spec/smoke/search_smoke_test_spec.rb, cosmetics-web/spec/support/capybara.rb
Capybara mechanize has been unmaintained for years and is not compatible with Ruby 3 syntax (unless using a fork).
Selenium web driver is the default for Rails 6 integration testing and allows us to run the smoke test without any change but the driver itself.
=> Migrate smoke tests to Selenium web driver

cosmetics-web/.rubocop.yml, cosmetics-web/spec/controllers/additional_information_controller_spec.rb, cosmetics-web/spec/controllers/component_build_controller_spec.rb, cosmetics-web/spec/controllers/formulation_upload_controller_spec.rb, cosmetics-web/spec/controllers/nanomaterial_build_controller_spec.rb, cosmetics-web/spec/controllers/notification_build_controller_spec.rb, cosmetics-web/spec/controllers/poison_centres/notifications_controller_spec.rb, cosmetics-web/spec/controllers/product_image_upload_controller_spec.rb, cosmetics-web/spec/controllers/responsible_persons/notifications_controller_spec.rb, cosmetics-web/spec/decorators/notifications_decorator_spec.rb, cosmetics-web/spec/features/account/forgotten_password_spec.rb, cosmetics-web/spec/features/creating_an_account_when_having_pending_responsible_person_invitations_spec.rb, cosmetics-web/spec/features/nanomaterial_notifications_spec.rb, cosmetics-web/spec/forms/notification_search_form_spec.rb, cosmetics-web/spec/forms/registration/account_security_form_spec.rb, cosmetics-web/spec/forms/responsible_persons/details_form_spec.rb, cosmetics-web/spec/helpers/application_helper_spec.rb, cosmetics-web/spec/models/component_spec.rb, cosmetics-web/spec/models/secondary_authentication/direct_otp_spec.rb, cosmetics-web/spec/models/user/new_email_concern_spec.rb, cosmetics-web/spec/requests/assets_security_spec.rb, cosmetics-web/spec/requests/nanomaterial_notifications_spec.rb, cosmetics-web/spec/requests/responsible_persons/delete_notification_spec.rb, cosmetics-web/spec/requests/responsible_persons/edit_address_spec.rb, cosmetics-web/spec/requests/responsible_persons/invitations_spec.rb, cosmetics-web/spec/requests/secondary_authentication/sms_spec.rb, cosmetics-web/spec/search/poison_centre_search_spec.rb, cosmetics-web/spec/services/notification_delete_service_spec.rb, cosmetics-web/spec/services/update_responsible_person_address_spec.rb
We have hundreds of violations of it in our codebase and resolving them would
require a lot of work refactoring our specs to break them down into separate
test groups.
The individual comments for disabling it in each case are quite noisy, so we're
disabling the rule.
=> Disable Rubocop RSpec/MultipleMemoizedHelpers rule

cosmetics-web/config/initializers/sentry.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1359)
These errors are meant to block users to access resources they shouldn't be able to. The exceptions are not runtime exceptions that may be caused by bugs or need to be resolved.
Given we have a very tight error quota in our Sentry plan and that Pundit errors give us no value, we will benefit from not sending them to Sentry.
https://cosmetics-pr-2356-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2356-search-web.london.cloudapps.digital/
=> Filter Pundit auth exceptions from Sentry

cosmetics-web/app/mailers/submit_notify_mailer.rb, cosmetics-web/app/services/update_responsible_person_address.rb, cosmetics-web/app/views/confirmation/link_expired.html.erb, cosmetics-web/app/views/help/accessibility_statement.html.erb, cosmetics-web/app/views/help/privacy_notice.html.erb, cosmetics-web/app/views/layouts/_navbar.html.erb, cosmetics-web/app/views/notifications/_responsible_person_details.html.erb, cosmetics-web/app/views/responsible_persons/account_wizard/join_existing.html.erb, cosmetics-web/app/views/responsible_persons/account_wizard/select_type.html.erb, cosmetics-web/app/views/responsible_persons/notifications/_aside_responsible_person_details.html.erb, cosmetics-web/app/views/search/landing_page/index.html.erb, cosmetics-web/spec/features/account/forgotten_password_spec.rb, cosmetics-web/spec/features/account/submit_sign_up_spec.rb, cosmetics-web/spec/features/inviting_a_colleague_spec.rb, cosmetics-web/spec/features/multiple_responsible_person_spec.rb, cosmetics-web/spec/services/update_responsible_person_address_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1222)
Turning any `responsible person` or `Responsible person` text occurrences through the service into `Responsible Person`.
https://cosmetics-pr-2357-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2357-search-web.london.cloudapps.digital/
=> Capitalise responsible person wording

cosmetics-web/app/views/poison_centres/notifications/_registered_product.html.erb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1363)
The construction of this line was causing the `#display_full_month_date` helper method to be called with nil values instead of only being called when the notification completion date is present.
This is causing 500 errors in production when Search users attempt to view the Search notifications index while having notifications that lack completion date in DB (probably ZIP imported).
https://cosmetics-pr-2360-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2360-search-web.london.cloudapps.digital/
=> Bug Fix: date helper called when date is not present

cosmetics-web/app/models/notification.rb, cosmetics-web/spec/models/notification_spec.rb
[Error in production](https://sentry.io/organizations/beis/issues/2927889849/?project=1398436)
The current code blindly trusts that, when attempting to format a notification reference number for display, the reference number is present.
When this is not the case, calling this method causes an exception.
Fixing this by returning an empty string in that case.
=> Cover empty ref. case when formatting ref. numbers

cosmetics-web/Gemfile, cosmetics-web/Gemfile.lock, cosmetics-web/app/controllers/nanomaterial_notifications_controller.rb, cosmetics-web/app/controllers/poison_centres/notifications_controller.rb, cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb, cosmetics-web/app/views/poison_centres/notifications/_results.html.erb, cosmetics-web/app/views/poison_centres/notifications/index.html.erb, cosmetics-web/app/views/responsible_persons/notifications/index.html.erb, cosmetics-web/spec/features/notification_search_spec.rb
- Migrate all the service pagination to `kaminari`.
- Remove `will_paginate`.
- Fix an issue with ElasticSearch pagination recently introduced with the change of where ES results get paginated: https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/pull/2367
- Test pagination so I don't break it again :( 
We recently did some work that delayed the ES search results' pagination to exclude deleted notifications from the results.
An unintended consequence of that change is that we do not pass the pagination limits to the ElasticSearch query anymore, and the ElasticSearch query started defaulting to return the first 10 hits instead of all (or the 20 desired ones per page).
This breaks the Search by limiting the results to 10 per search. Even the default index is limited to 10 results.
Fixing …
=> Fix search pagination

.github/workflows/smoke_test.yml
Docker pull of Opensearch image is failing in Smoke tests. The org prefix is missing.
=> Fix: Add org. to Opensearch image for Smoke tests

.github/workflows/smoke_test.yml
To match the test workflow and the smoke test workflow OS config.
=> Disable OpenSearch security plugin in Smoke Tests

cosmetics-web/app/controllers/responsible_persons/drafts_controller.rb, cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb, cosmetics-web/app/helpers/draft_helper.rb, cosmetics-web/app/views/responsible_persons/drafts/_product.html.erb, cosmetics-web/app/views/responsible_persons/drafts/_product_info.html.erb, cosmetics-web/app/views/responsible_persons/drafts/guides/_product_name_added.html.erb, cosmetics-web/app/views/responsible_persons/notifications/index.html.erb, cosmetics-web/app/views/responsible_persons/notifications/new.html.erb, cosmetics-web/app/views/responsible_persons/wizard/notification_product/_add_product_name_form.html.erb, cosmetics-web/app/views/responsible_persons/wizard/notification_product/add_product_name.html.erb, cosmetics-web/config/routes.rb
This code introduces a little bit duplication:
* draft view is being displayed in 2 different situations: when product is created and not created
* product name form is used in 2 places: in wizad and as typical rails form
To solved this and reduce need for additional controllers in action, I did following changes:
**Added new route: `/responsible_persons/:id/drafts/new`**
above route is using current `ResponsiblePersons::DraftController`, new action `new` is added which renders `show` template.
The `show` template is adjusted to handle non persisted notification.
**Added `new` and `create` action to existing notification controller**
Cleaned up existing actions and added 2 `rails'y` actions `new` and `create`. The `new` template is using `add_product_name` template from wizard.
=> 1412 dont create notification until name

cosmetics-web/spec/controllers/responsible_persons/notifications_controller_spec.rb
Having a hardcoded domain in the specs forces local test environments to
use that particular hostname or the tests will fail.
=> Remove hardcoded hostname from specs

cosmetics-web/app/controllers/responsible_persons_controller.rb, cosmetics-web/app/services/update_responsible_person_details.rb, cosmetics-web/app/views/responsible_persons/edit.html.erb, cosmetics-web/app/views/responsible_persons/show.html.erb, cosmetics-web/spec/features/creating_a_responsible_person_spec.rb, cosmetics-web/spec/features/editing_responsible_person_address_spec.rb, cosmetics-web/spec/features/editing_responsible_person_details_spec.rb, cosmetics-web/spec/features/multiple_responsible_person_spec.rb, cosmetics-web/spec/requests/responsible_persons/edit_details_spec.rb, cosmetics-web/spec/services/update_responsible_person_details_spec.rb, cosmetics-web/spec/support/feature_helpers.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1370)
Users from a Responsible Person will be able to edit the RP account type, choosing between Individual or Business.
This change is accessible from the Responsible Person details page, adding a link to edit the RP type.
This link sends the user to the RP edit page, also used for editing the RP address.
https://cosmetics-pr-2417-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2417-search-web.london.cloudapps.digital/
=> Allow users to edit RP type

cosmetics-web/deploy-review.sh, cosmetics-web/manifest.yml
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1382)
Upgrading Redis service in all our environments to Redis v6 from current Redis v3.2
- From **tiny-3.2** 568MB RAM, single node, no failover, daily backups (for instances created after 21/1/2019). Free for trial orgs. Costs for billable orgs.
- To **micro-6.x** 568MB RAM, single node, no failover, daily backups. Free for trial orgs. Costs for billable orgs.
Micro 6.x offers the same resources as the current Tiny 3.2. Tiny 6.x uses 1.5GB RAM (that we do not need in this environment)
- From **tiny-ha-3.2** 1.5GB RAM, highly-available, daily backups
- To **tiny-ha-6.x** 1.5GB RAM, highly-available, daily backups
https://cosmetics-pr-2434-submit-web.london.cloudapps.digital/ …
=> Upgrade Redis version from 3 to 6

cosmetics-web/app/controllers/responsible_persons/wizard/notification_product_controller.rb, cosmetics-web/app/forms/responsible_persons/wizard/notification_product/contains_nanomaterials_form.rb, cosmetics-web/app/forms/responsible_persons/wizard/notification_product/single_or_multi_component_form.rb, cosmetics-web/app/models/concerns/notification_state_concern.rb, cosmetics-web/app/models/notification.rb, cosmetics-web/app/views/responsible_persons/drafts/show.html.erb, cosmetics-web/app/views/responsible_persons/wizard/notification_product/contains_nanomaterials.html.erb, cosmetics-web/app/views/responsible_persons/wizard/notification_product/single_or_multi_component.html.erb, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/controllers/notification_product_controller_spec.rb, cosmetics-web/spec/factories/notification.rb, cosmetics-web/spec/forms/responsible_persons/wizard/notification_product/contains_nanomaterials_form_spec.rb, cosmetics-web/spec/forms/responsible_persons/wizard/notification_product/single_or_multi_component_form_spec.rb, cosmetics-web/spec/models/notification_spec.rb, cosmetics-web/spec/support/helpers/product_wizard.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1423?atlOrigin=eyJpIjoiYTBlOTY0NmYyYWE4NDAwMjllNzBkYWE1NTczZDFlZWIiLCJwIjoiaiJ9)
Improvements/Changes over the Nanomaterials/Items wizard pages
Both steps got similar refactors:
- Extracted validation errors to the locales YAML file.
- Manage form and its validations with a form object.
- Move logic from the controller into the Notification model.
- Reduce controller branching.
They also share some changes:
- Add numerical format check over the number of nanomaterials input.
- Validation errors wording changes.
On the nanomaterial step we did:
- Rename of input label.
- Add an error on page title when errors are present.
There is a couple of further minor refactors down the …
=> Improvements over nanomaterials and multi-items wizard pages

cosmetics-web/app/views/responsible_persons/notifications/product/contains_nanomaterials.html.erb, cosmetics-web/app/views/responsible_persons/notifications/product/single_or_multi_component.html.erb, cosmetics-web/spec/support/helpers/product_wizard.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1409)
When a notification draft already has nanomaterials or items present and
the user re-runs the product creation task, it will be displayed a page
indicating to add/remove the nano/item from the draft instead of the
original form to introduce a number of nanos/items to be created.
This work re-designs those pages.
-----------------------------
https://cosmetics-pr-2456-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2456-search-web.london.cloudapps.digital/
=> Re-design pages for  nanos/items are present.

cosmetics-web/app/controllers/responsible_persons/delete_notification_controller.rb, cosmetics-web/app/views/responsible_persons/delete_notification/delete.html.erb, cosmetics-web/spec/features/notifications_deleting_spec.rb, cosmetics-web/spec/requests/responsible_persons/delete_notification_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1391)
Users will need to confirm before deleting the draft/notification pages.
A validation error will be displayed if the user submits the deletion without checking the confirmation.
Modifying wording to be correct for both drafts and submitted notifications.
----
----
----
----
https://cosmetics-pr-2473-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2473-search-web.london.cloudapps.digital/
=> Redesign draft/notification deletion page.

cosmetics-web/spec/features/account/sign_in_spec.rb
[Flaky test run example](https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/runs/6211813498?check_suite_focus=true)
We had these tests randomly failing for a while on our automated test runs, forcing us to re-run the specs in order to unblock the Pull Request for merging.
**Cause of the flaky specs:**
In order to calculate a wrong OTP Code, we were reversing the user OTP
Code generated by the service while having 2FA enabled.
This is easy and works well when the generated code is "12345", having
"54321" as the wrong code.
But what happens when the user's OTP code is a palindrome? "12121" turns into... "12121". So the "wrong code" is the same as the right code. And when asserting over entering the wrong code and getting an error... the test fails because it actually managed to sign-in …
=> Fix sign-in flaky feature tests

cosmetics-web/app/models/user.rb
Resetting the user's secondary authentication is a common user support request, and we have been copy&pasting this query for each request.
Adding it into the user model so we can call
- `user.reset_secondary_authentication!`
instead of building the query each time (that may be prone to errors or be lost between different devs).
=> Add a User method to reset 2FA

cosmetics-web/app/controllers/responsible_persons/team_members_controller.rb, cosmetics-web/app/models/concerns/new_email_concern.rb, cosmetics-web/app/models/user.rb, cosmetics-web/spec/features/inviting_a_colleague_spec.rb, cosmetics-web/spec/models/user/new_email_concern_spec.rb, cosmetics-web/spec/support/shared_examples/common_user_tests.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1443)
When a Responsible Person team member invitation was sent to an email address that matches an existing user's "new email" that has not been confirmed, accepting the invitation was causing the creation of a new user.
The new user has the email address of the existing user's new email.
This causes multiple issues:
- Both users become invalid due to sharing email values.
- Both users in our service belong to a single person.
To resolve this, when a user receives a team invitation to their new unconfirmed email and follows the link inside the valid confirmation time period:
1. No new user will be created. Instead, finds the user by new_email and adds this user to the team.
2. Since the user opened this confirmation …
=> Fix RP invitation to new unconfirmed user email

cosmetics-web/app/helpers/responsible_persons/notifications_helper.rb, cosmetics-web/app/views/notifications/_product_details_label_images.html.erb, cosmetics-web/spec/helpers/responsible_persons/notifications_helper_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1510)
[Error tracking issue](https://sentry.io/organizations/beis/issues/3281115279/?project=1398436)
The view for label images is shared between MSA users and Submit users.
When the label image has not passed the antivirus check, it shows a "Refresh" link that reloads the edit page for Submit users.
The same link was being called from Search MSA users, causing a routing error (as MSA users are not associated with a Responsible Person and the route parameter is missing).
MSA users shouldn't even know if the image is processing or not. Just having it displayed when is available and not displayed when it is not.
The fix only shows the link if edits are allowed for the user when loading the page (submit user belonging to …
=> Fix label images display for MSA users

cosmetics-web/app/assets/application/stylesheets/opss/_opss-shared.scss, cosmetics-web/app/controllers/responsible_persons/notifications/components/build_controller.rb, cosmetics-web/app/forms/responsible_persons/notifications/exact_concentration_form.rb, cosmetics-web/app/models/cmr.rb, cosmetics-web/app/models/exact_formula.rb, cosmetics-web/app/validators/cas_number_validator.rb, cosmetics-web/app/views/responsible_persons/notifications/components/build/_poison_tables.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/add_ingredient_exact_concentration.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/want_to_add_another_ingredient.html.erb, cosmetics-web/config/locales/en.yml, cosmetics-web/db/migrate/20220519155041_add_cas_number_and_poisonous_to_exact_formulas.rb, cosmetics-web/db/migrate/20220520183803_change_nullable_attributes_on_exact_formulas.rb, cosmetics-web/db/migrate/20220520184518_validate_change_nullable_attributes_on_exact_formulas.rb, cosmetics-web/db/schema.rb, cosmetics-web/spec/forms/responsible_persons/notifications/exact_concentration_form_spec.rb, cosmetics-web/spec/models/exact_formula_spec.rb, cosmetics-web/spec/support/helpers/item_wizard.rb, cosmetics-web/spec/validators/cas_number_validator_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1500)
Until now, when a user creates a notification and marks the ingredients for the item/product as "exact ingredients", they have been uploading formulation PDFs. 
From now on, we will prompt them to introduce the ingredients information manually. For each ingredient, they will  add:
- The ingredient's name.
- Its exact concentration
- (Optionally) CAS number.
- Flag if the ingredient is poisonous.
Page for adding exact ingredients information:
----
Page displayed after adding an ingredient:
----
Summary pre-notification submission displaying the ingredients exact concentrations:
----
https://cosmetics-pr-2501-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2501-search-web.london.cloudapps.digital/
=> Add ingredients exact concentration new notification

cosmetics-web/app/controllers/responsible_persons/notifications/components/build_controller.rb, cosmetics-web/app/views/responsible_persons/notifications/components/build/_add_ingredient_concentration.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/_ingredient_exact_concentration_fields.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/add_ingredient_exact_concentration.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/add_poisonous_ingredient.html.erb, cosmetics-web/spec/controllers/responsible_persons/notifications/components/build_controller_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1499)
When the user selects to add poisonous ingredients to a frame formulation components will be shown a form to manually add each poisonous ingredient and their exact concentration.
The form and flow will be almost identical to adding exact ingredients to a component, but with slight differences in the wording and with the "Poisonous" check to be pre-selected and enforced (users won't be able to uncheck them).
https://cosmetics-pr-2518-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2518-search-web.london.cloudapps.digital/
=> New frame formulation poisonous ingredient flow

cosmetics-web/app/models/component.rb, cosmetics-web/app/validators/accept_and_submit_validator.rb, cosmetics-web/spec/models/component_spec.rb, cosmetics-web/spec/validators/accept_and_submit_validator_spec.rb
Since now none of the add ingredient flows requires uploading a formulation file.
https://cosmetics-pr-2523-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2523-search-web.london.cloudapps.digital/
=> Remove missing formulation file validation

cosmetics-web/app/controllers/responsible_persons/notifications/components/build_controller.rb, cosmetics-web/app/controllers/responsible_persons/notifications/components/delete_ingredients_controller.rb, cosmetics-web/app/models/component.rb, cosmetics-web/app/validators/accept_and_submit_validator.rb, cosmetics-web/app/views/responsible_persons/notifications/components/build/select_formulation_type.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/delete_ingredients/show.html.erb, cosmetics-web/spec/factories/component.rb, cosmetics-web/spec/features/notification_wizard/ingredients/editing_ingredients_on_components_spec.rb, cosmetics-web/spec/models/component_spec.rb
[Jira ticket 1503](https://regulatorydelivery.atlassian.net/browse/COSBETA-1503)
As done with range/exact formulations, when a user revisits the component details tasks, will find the existing ingredients (in this case the poisonous ingredients) prefilled one by one. The user will be able to edit the details or remove the ingredients.
When changing the formulation type from predefined to exact/range all the existing predefined formulation poisonous ingredients will be wiped.
Same if when revisiting the flow the user answers "No" to the "contains poisonous ingredients?" question.
https://cosmetics-pr-2536-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2536-search-web.london.cloudapps.digital/
=> Allow to edit/delete poisonous ingredients from predefined formulation components

cosmetics-web/app/forms/responsible_persons/notifications/product/contains_nanomaterials_form.rb, cosmetics-web/spec/controllers/responsible_persons/notifications/product_controller_spec.rb, cosmetics-web/spec/forms/responsible_persons/notifications/product/contains_nanomaterials_form_spec.rb
To reproduce:
Select "Yes" on question "Does {notification_name} contains nanomaterials" and enter amount:
Than change your answer to "No":
After submit, there will be 4 nanomaterials created.
This PR contains fix.
=> Bug - don't create nanomaterials if no is selected.

cosmetics-web/app/controllers/concerns/wizard_concern.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1526)
When a user manually introduces a non-existing step in the URL for a WickedWizard controller, the services throws an exception (raised as `Wicked::Wizard::InvalidStepError`).
Instead of raising a production exception, raise a Routing Error that will be mapped to the 404 error page by Rails.
https://cosmetics-pr-2552-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2552-search-web.london.cloudapps.digital/
=> Redirect WickedWizard invalid steps to 404 page

.github/workflows/deploy.yml, .github/workflows/review-apps-delete.yml, .github/workflows/review-apps.yml, README.md
Changes to be done after moving the repository from BEIS to OPSS own repository:
- Change the Readme title to match the service name
- Change GitHub actions authentication token to the one provided by Github for automatic token authentication.
=> Post repo organisation switch fixes

cosmetics-web/app/controllers/responsible_persons/notifications/components/build_controller.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1376)
The check over the component having `nil` as shades value works fine for pre-creating two empty shades when reaching the "add shades" page for the first time.
The problem is that when the user skips the addition of the shades by not introducing any value in the shades fields, the component shades value will become an empty array `[]`.
This is not very consistent from a model data point, and we will probably want to migrate all production data to ensure we go for either `nil` or `[]` as shades attribute value when the component has no shades.
Besides that, there is a user interface issue when not filling any shades and then re-visiting the step and moving back to the same point again.
With the current code, a …
=> Fix missing shades inputs

cosmetics-web/app/views/responsible_persons/notifications/product/add_product_image.html.erb, cosmetics-web/spec/features/notification_wizard/adding_and_removing_label_images_spec.rb, cosmetics-web/spec/support/helpers/product_wizard.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1199)
When browsing without JS enabled, the link to remove an image was triggering a server error.
This is caused by the delete links mapping to an AJAX call that cannot be executed without JavaScript.
Fixed it by replacing the deletion link with a deletion button that triggers a form POST request.
https://cosmetics-pr-2575-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2575-search-web.london.cloudapps.digital/
=> Fix error when removing images without JS-enabled

cosmetics-web/app/controllers/poison_centres/ingredients_controller.rb, cosmetics-web/app/models/ingredient.rb, cosmetics-web/spec/models/ingredient_spec.rb, cosmetics-web/spec/requests/ingredient_list_spec.rb
`Ingredient.for_list(param)` is wrapping both controller and model logic.
This refactor proposal splits this between:
- Model fetching specific sets of data through scopes.
- Controller is in charge of querying the model for different data based on the order parameters.
=> Split for_list logic between model & controller

cosmetics-web/app/views/nanomaterial_notifications/index.html.erb, cosmetics-web/app/views/nanomaterial_notifications/show.html.erb, cosmetics-web/spec/features/nanomaterial_notifications_spec.rb
Jira tickets [1540](https://regulatorydelivery.atlassian.net/browse/COSBETA-1540) and [1541](https://regulatorydelivery.atlassian.net/browse/COSBETA-1541)
Add the "Review period end" date on the Nanomaterial Notification index page and each individual Nanomaterial Notification page.
----
https://cosmetics-pr-2582-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2582-search-web.london.cloudapps.digital/
=> Show review period end in nanomaterial notification pages

cosmetics-web/app/models/notification.rb
Looks like reindexing causes inaccurate search results.  Later we might find a non-invasive way of reindexing. We are still reindexing entire OS cluster at night.
=> Dont run reindexing on delete

cosmetics-web/app/controllers/responsible_persons/notifications/nanomaterials/build_controller.rb, cosmetics-web/app/controllers/responsible_persons/notifications/nanomaterials_controller.rb, cosmetics-web/app/forms/responsible_persons/notifications/nanomaterials/nano_element_purposes_form.rb, cosmetics-web/app/helpers/nanomaterial_helper.rb, cosmetics-web/app/models/nano_element.rb, cosmetics-web/app/models/nano_element_purposes.rb, cosmetics-web/app/views/responsible_persons/notifications/nanomaterials/build/_purposes_form.html.erb, cosmetics-web/app/views/responsible_persons/notifications/nanomaterials/build/add_nanomaterial_name.html.erb, cosmetics-web/app/views/responsible_persons/notifications/nanomaterials/build/confirm_restrictions.html.erb, cosmetics-web/app/views/responsible_persons/notifications/nanomaterials/build/confirm_usage.html.erb, cosmetics-web/app/views/responsible_persons/notifications/nanomaterials/build/select_purposes.html.erb, cosmetics-web/app/views/responsible_persons/notifications/nanomaterials/new.html.erb, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/controllers/responsible_persons/notifications/nanomaterials/build_controller_spec.rb, cosmetics-web/spec/features/notification_wizard/blocked_nano_spec.rb, cosmetics-web/spec/features/notification_wizard/correct_status_spec.rb, cosmetics-web/spec/forms/responsible_persons/notifications/nanomaterials/nano_element_purposes_form_spec.rb, cosmetics-web/spec/models/nano_element_purposes_spec.rb, cosmetics-web/spec/support/helpers/nano_material_wizard.rb
[Jira ticket 1538](https://regulatorydelivery.atlassian.net/browse/COSBETA-1538)
This is the first nanomaterial journey changes ticket, belonging to the ["Improve nanomaterials addition/linking in product notifications" epic](https://regulatorydelivery.atlassian.net/browse/COSBETA-1560).
These changes focus on changing the nanomaterial journey to flip the order of the first two steps (from `add the name` -> `select the purposes` to `select the purposes` -> `add the name`), tweaking the forms and only requiring name for standard purposes nanomaterials.
When completing a nanomaterial from the notification draft, the first question will be about the nanomaterial's purposes.
We have changed from a plain checklist with all the options to a radio button that asks the user to choose between …
=> Change nanomaterial journey

cosmetics-web/app/controllers/responsible_persons/notifications/components/build_controller.rb, cosmetics-web/app/views/responsible_persons/notifications/components/build/add_exposure_routes.html.erb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1590)
Fixing a server error when the user does not select any of the exposure routes options and submits the form.
=> Fix exposure routes empty submission

cosmetics-web/.rubocop.yml, cosmetics-web/lib/tasks/nanomaterials.rake, cosmetics-web/spec/factories/nano_material.rb, cosmetics-web/spec/tasks/nanomaterials_tasks_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1587)
We have identified over 209k nanomaterials in production not associated with any nanoelement (hence not even having a name or being displayed anywhere) and 28k orphan nanomaterials without any association to components or notifications.
We're introducing 2 rake tasks to remove them from our DB.
Any nanomaterial with no associated nanoelement is invalid and should be deleted from our DB.
Even when they belong to a submitted notification, we only display nanoelement names and info in the notification info.
It is safe to delete nanomaterials with no nanoelement and consequently no name.
Between Jan and October 2021 28.5k nanomaterials were created without being associated with any notification or component.
This …
=> Add nanomaterials rake maintenance tasks

cosmetics-web/db/migrate/20220920110832_remove_component_id_from_nano_materials.rb, cosmetics-web/db/schema.rb, cosmetics-web/lib/tasks/draft_notifications.rake, cosmetics-web/lib/tasks/nanomaterials.rake, cosmetics-web/spec/tasks/nanomaterials_tasks_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1593)
Now the relationship between `NanoMaterial` and `Component` is a many-to-many through a `ComponentNanoMaterial` model/table.
=> Remove component id from nanomaterials

cosmetics-web/app/views/layouts/application.html.erb, cosmetics-web/app/views/submit/landing_page/index.html.erb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1582)
Add a banner on the submit service alerting users about the incoming ingredients changes on October 3rd.
Only display when there are no success banners for the page.
https://cosmetics-pr-2596-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2596-search-web.london.cloudapps.digital/
=> Add banner on Submit about oncoming ingredients changes

cosmetics-web/app/views/layouts/application.html.erb, cosmetics-web/app/views/search/landing_page/index.html.erb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1597)
Add a banner across the search landing and service pages alerting users about the incoming feature allowing them to search notifications by their ingredients.
https://cosmetics-pr-2600-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2600-search-web.london.cloudapps.digital/
=> Add banner about new ingredients on Search

cosmetics-web/spec/smoke/search_smoke_test_spec.rb
The wording has been changed. We need to update the smoke test to assert against the new wording.
=> Fix h1 wording in Smoke tests

cosmetics-web/deploy.sh, cosmetics-web/manifest.review.yml, cosmetics-web/manifest.yml
The [CloudFoundry app manifest specification](https://v3-apidocs.cloudfoundry.org/version/3.76.0/index.html#the-app-manifest-specification) shows that there is no `env` section for `processes`, and therefore these were never being set in the applications.
Additionally, in production and staging (but not review apps) there is a user-provided service called `cosmetics-puma-env` which provides the `RAILS_MAX_THREADS`, `RAILS_MIN_THREADS` and `WEB_CONCURRENCY` environment variables. These would override the definition in the manifest which would cause confusion.
In the review apps manifest, the environment variables are overridden in the `command` definition which was overriding the `env` definition, which would similarly cause confusion.
I have also removed the increased `STATEMENT_TIMEOUT` …
=> Fix environment variables incorrectly configured in manifest files

cosmetics-web/app/assets/application/stylesheets/opss/_opss-msa.scss, cosmetics-web/app/assets/application/stylesheets/opss/_opss-shared.scss, cosmetics-web/app/views/poison_centres/ingredients_search/_results.html.erb, cosmetics-web/app/views/poison_centres/ingredients_search/show.html.erb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1612)
Include the date from when notifications with ingredients can be searched by ingredients.
We are adding it in both the subtext of the ingredients search page and the wording for the number of results found.
https://cosmetics-pr-2617-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2617-search-web.london.cloudapps.digital/
=> Move ingredients search date text

cosmetics-web/app/models/secondary_authentication/direct_otp.rb, cosmetics-web/app/models/secondary_authentication/otp_whitelisting.rb, cosmetics-web/app/models/secondary_authentication/time_otp.rb, cosmetics-web/config/application.rb, cosmetics-web/spec/models/secondary_authentication/direct_otp_spec.rb, cosmetics-web/spec/models/secondary_authentication/time_otp_spec.rb, cosmetics-web/spec/support/shared_examples/whitelisted_otp_tests.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1631)
As review apps use an enhanced copy of staging DB, we do not use a fake phone number with SMS 2FA by default for all the review app users anymore.
Now, some users have App Authentication.
And for those users, we do not have an easy way to bypass the 2FA APP Code requests.
This PR resolves that by bringing the possibility of using a whitelisted code from Direct OTP codes into Time OTP codes.
From now on, the whitelisted codes will need to be defined in the environment as:
- `WHITELISTED_DIRECT_OTP_CODE` for the SMS 2FA (5 digits)
-  `WHITELISTED_TIME_OTP_CODE` for the APP 2FA (6 digits)
Note: Tested it in the review app after setting a `WHITELISTED_TIME_OTP_CODE` value in the environment. It did work, …
=> Allow to whitelist App OTP codes in review apps and staging

cosmetics-web/app/views/nanomaterial_notifications/index.html.erb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1551)
When users reach their list of Nanomaterial Notifications for their Responsible Person, they will have a link containing expandable details with guidance on when users can place products containing nanomaterials on the market.
-----
https://cosmetics-pr-2623-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2623-search-web.london.cloudapps.digital/
=> Add details info on nano notifications list page

cosmetics-web/app/jobs/reindex_opensearch_job.rb, cosmetics-web/config/initializers/advisory_lock_constants.rb
Looks like sidekiq cron is being scheduled on each of the nodes, limit search reindexing to only one operation.
=> Allow only one reindexing operation

cosmetics-web/app/jobs/reindex_opensearch_job.rb
We were removing index on every reindexing job. When they were failing, this was causing lack of searchable notifications in the index. Now, index is created only when it does not exists - it will be used mostly by review apps.
=> Dont recreate index

cosmetics-web/app/views/search/landing_page/index.html.erb, cosmetics-web/app/views/submit/landing_page/index.html.erb, cosmetics-web/spec/features/account/creating_a_search_account_from_an_invitation_spec.rb, cosmetics-web/spec/features/account/submit_sign_up_spec.rb, cosmetics-web/spec/features/multiple_responsible_person_spec.rb, cosmetics-web/spec/features/responsible_person_spec.rb, cosmetics-web/spec/requests/submit/landing_page_spec.rb
https://regulatorydelivery.atlassian.net/browse/COSBETA-1238
Updated CSS classes on page headers
https://cosmetics-pr-2645-submit-web.london.cloudapps.digital/
=> Improve colour contrast ratio on main pages for 'Search' and 'Submit'

cosmetics-web/spec/smoke/search_smoke_test_spec.rb
Smoke test broke since we changed the wording on the Search page title.
This aligns the test with the new wording.
=> Fix smoke test title assertions

.github/workflows/smoke_test.yml
Adding this trigger will allow us to manually run the smoke tests (including modified versions from specific branches) from Github actions page.
=> Enable manual smoke test runs

cosmetics-web/app/views/responsible_persons/notifications/index.html.erb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1241)
The Submit cosmetics products notifications list page shows some specific text when the user Responsible Person has no submitted notifications in the service.
We are changing the wording and paragraphing of this message.
https://cosmetics-pr2656-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2656-search-web.london.cloudapps.digital/
=> Changes on "no submitted any notification" text

cosmetics-web/app/forms/responsible_persons/notifications/ingredient_concentration_form.rb, cosmetics-web/app/models/ingredient.rb, cosmetics-web/app/validators/ingredient_name_format_validator.rb, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/forms/responsible_persons/notifications/ingredient_concentration_form_spec.rb, cosmetics-web/spec/models/ingredient_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1533)
We are banning `<\`, `www` and `http` from Ingredient names. Using the same pattern as on previous name validations.
https://cosmetics-pr-2658-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2658-search-web.london.cloudapps.digital/
=> Validate against URLs on Ingredient name

cosmetics-web/app/controllers/responsible_persons/contact_persons_controller.rb, cosmetics-web/app/controllers/responsible_persons_controller.rb, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/features/submit/responsible_person/contact_person_details_edition_spec.rb, cosmetics-web/spec/features/submit/responsible_person/details_edition_spec.rb, cosmetics-web/spec/requests/contact_person_request_spec.rb, cosmetics-web/spec/requests/responsible_persons/edit_details_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1561)
Changing the wording on the success banners that are displayed after updating either Contact Person or Responsible Person details.
https://cosmetics-pr-2660-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2660-search-web.london.cloudapps.digital/
=> Change success banners wording for Responsible Person & Contact Person details change

cosmetics-web/app/views/responsible_persons/delete_items/show.html.erb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1403)
When a user attempts to delete an item from a multi-item notification draft, and the notification has 2 items, there are shown a page with a message about not being able to remove items.
The HTML div column element containing this message wasn't wrapped in an HTML div row, causing some redundant left margin to be applied.
Re-structured the page HTML always to have the same row/column structure, regardless of showing the deletion form or the error message.
Also broke the long paragraphs into more readable lines, and applied rails `link_to` helpers to the plain HTML links.
https://cosmetics-pr-2664-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2664-search-web.london.cloudapps.digital/
=> Fix margins from 'cannot remove an item' page

cosmetics-web/app/forms/responsible_persons/notifications/ingredient_concentration_form.rb, cosmetics-web/spec/forms/responsible_persons/notifications/ingredient_concentration_form_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1661)
We are introducing a form validation to avoid very long text introduced as an ingredient name when creating an ingredient.
Since we moved from PDF formulations to requiring RP users to introduce their product ingredients manually, some users used the lack of length restriction on the name to paste the whole product formulation (sometimes thousands of characters) as an ingredient.
This validation will avoid that for future ingredients. What to do with the current ingredients/products violating this will be decided in the future. At the moment those product notifications should pass validations, hence not introducing a model validation together with the form one. …
=> Do not allow to introduce long ingredient names

cosmetics-web/config/locales/en.yml, cosmetics-web/spec/forms/responsible_persons/notifications/ingredient_concentration_form_spec.rb
Just a rewording, moving away from the default rails length error message to match the [GDS standards](https://design-system.service.gov.uk/components/error-message/)
=> Reword ingredient name validation to GDS standards

cosmetics-web/app/views/responsible_persons/contact_persons/_edit_field.html.erb, cosmetics-web/spec/features/submit/responsible_person/contact_person_details_edition_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1424)
Use "Save and continue" instead of "Continue"
https://cosmetics-pr-2677-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2677-search-web.london.cloudapps.digital/
=> Change wording on Contact Person edit form buttons

cosmetics-web/app/controllers/responsible_persons/team_members_controller.rb, cosmetics-web/app/mailers/submit_notify_mailer.rb, cosmetics-web/config/initializers/session_security.rb, cosmetics-web/spec/features/submit/responsible_person/user_invitation_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1175)
**When:**
1. A team invited a non-registered user email.
2. The user registered themselves without following the link.
3. The user "signs out" from the account security page instead of completing their registration.
4. User follows up on the invitation link to register/join the team.
**Then:**
A sign-in page with a "Your login credentials were used in another browser." error. Instead of displaying the account security page and allowing the user to complete their registration while getting added to the Responsible Person that invited them.
The method used for signing in a user from an invitation link called the `bypass_sign_in` Devise method. That method bypasses Warden callbacks and stores the user straight in …
=> Fix follow team invite link with incomplete user

cosmetics-web/app/models/nano_material.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1438)
The relationship between nanomaterial to component used to be "one component to many nanomaterials". That enabled delegating methods from the component into the nanomaterial.
Since this has been moved to a many-to-many relationship, this delegation is no longer valid, as one nanomaterial will have many components.
=> Remove invalid delegation from nano to component

cosmetics-web/app/assets/application/javascripts/notification_search.js, cosmetics-web/app/controllers/poison_centres/ingredients_search_controller.rb, cosmetics-web/app/controllers/poison_centres/notifications_controller.rb, cosmetics-web/app/controllers/poison_centres/notifications_search_controller.rb, cosmetics-web/app/forms/ingredient_search_form.rb, cosmetics-web/app/helpers/poison_centres_notifications_helper.rb, cosmetics-web/app/models/open_search_query/ingredient.rb, cosmetics-web/app/models/open_search_query/notification.rb, cosmetics-web/app/views/poison_centres/ingredients_search/_filters.html.erb, cosmetics-web/app/views/poison_centres/ingredients_search/_hidden_date_fields.html.erb, cosmetics-web/app/views/poison_centres/ingredients_search/_results.html.erb, cosmetics-web/app/views/poison_centres/ingredients_search/_sort_form.html.erb, cosmetics-web/spec/features/search/ingredient_search_spec.rb, cosmetics-web/spec/models/open_search_query/ingredients_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1615)
Adding a sorting selector next to the ingredients search box, allowing users to sort their search results by relevance/newest/oldest.
This sorting will combine with the existing search filters. So, when grouping the search results by a responsible person and also applying sorting criteria, the results will be grouped by the RP and then sorted by the given criteria.
----
----
----
----
----
https://cosmetics-pr-2689-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2689-search-web.london.cloudapps.digital/
=> Implement sorting by relevance/date on ingredient search results

cosmetics-web/app/controllers/poison_centres/ingredients_search_controller.rb
I noticed that the Ingredients search is triggering n+1 queries to retrieve & display the Responsible Person name for each notification result.
Resolving it by preloading it.
Note: In the example, ActiveRecord/PG is managing to retrieve it from cache memory saving the DB hit as I only have 2 RPs locally, and the query is always the same, but you can get an idea about the volume of DB requests being triggered per search.
```
Notification Load (0.3ms)  SELECT "notifications".* FROM "notifications" WHERE "notifications"."id" IN ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20) AND "notifications"."state" = $21  [["id", 1], ["id", 4], ["id", 7], ["id", 10], ["id", 13], ["id", 16], ["id", 19], ["id", 22], ["id", 25], ["id", 28], ["id", 31], ["id", 34], …
```
=> Fix n+1 query on Ingredients search

cosmetics-web/app/models/concerns/notification_state_concern.rb, cosmetics-web/app/models/notification.rb, cosmetics-web/lib/tasks/deleted_notifications.rake, cosmetics-web/spec/lib/tasks/deleted_notifications_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1709)
Fix of a bug introduced by https://github.com/OfficeForProductSafetyAndStandards/cosmetic-product-notifications/pull/2692
=> Bugfix: Notifications missing deletion timestamps

cosmetics-web/app/views/poison_centres/ingredients_search/_filters.html.erb, cosmetics-web/app/views/poison_centres/notifications_search/_date_filter_input.html.erb, cosmetics-web/app/views/poison_centres/notifications_search/_filters.html.erb, cosmetics-web/app/views/poison_centres/notifications_search/_no_js_date_filters.html.erb, cosmetics-web/app/views/responsible_persons/search_ingredients/_search_form.html.erb, cosmetics-web/app/views/responsible_persons/search_notifications/_search_form.html.erb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1670)
We are bringing changes to the Cosmetic Search portal to improve the search for users browsing without JavaScript:
- When searching for ingredients, the reset filter link will be hidden.
- When searching for notified products, instead of allowing users to filter either by an exact date or a date range, users will default to the date-range filters.
https://cosmetics-pr-2696-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2696-search-web.london.cloudapps.digital/
=> Changes on Cosmetic Search date filters for users navigating without JavaScript

.github/workflows/review-apps-delete.yml
Since Dependabot PRs are not creating review apps, the Github action for deleting the review app when deleting/closing a Dependabot PR is failing. ([Example](https://github.com/OfficeForProductSafetyAndStandards/cosmetic-product-notifications/actions/runs/3693520501/jobs/6253600406))
Resolving it by checking the reviw app existence before attempting to stop/delete it.
=> Check that the review app exists before deletion

cosmetics-web/app/views/poison_centres/ingredients_search/_filters.html.erb, cosmetics-web/app/views/poison_centres/ingredients_search/show.html.erb, cosmetics-web/app/views/poison_centres/notifications_search/show.html.erb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1669)
Resolving the following issues when displaying errors in the Cosmetics Search portal:
https://cosmetics-pr-2723-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2723-search-web.london.cloudapps.digital/
=> Fix error display on search pages

cosmetics-web/app/views/responsible_persons/notifications/components/build/contains_ingredients_npis_needs_to_know.html.erb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1668)
When a frame formulation notification containing poisonous ingredients is cloned, and going through the cloned steps, we want to have pre-selected the original notification answer on whether the notification contains poisonous ingredients or not.
https://cosmetics-pr-2725-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2725-search-web.london.cloudapps.digital/
=> Preselect poisonous info answer on cloned notifications

cosmetics-web/app/controllers/registration/new_accounts_controller.rb, cosmetics-web/app/views/users/check_your_email/show.html.erb, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/features/account/submit_sign_up_spec.rb, cosmetics-web/spec/features/submit/responsible_person/user_account_creation_with_pending_responsible_person_invitations_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-670)
When users initiate their registration, they are redirected to a "check your email" static page.
On that page:
- We included the email address where the registration email has been sent.
- We included a message to check the spam folder if no email arrived in the inbox.
https://cosmetics-pr-2724-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2724-search-web.london.cloudapps.digital/
=> Change wording on check your email page

cosmetics-web/app/services/one_off/notification_bulk_deleter.rb, cosmetics-web/spec/services/one_off/notification_bulk_deleter_spec.rb
Ensuring the notifications are retrieved ordered by reference so the logs will always be presented in the same way.
=> Fix flaky test on notification bulk deletion

cosmetics-web/app/assets/application/javascripts/notification_search.js
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1671)
When there is a validation error on the Cosmetics Product Search date filter inputs, we don't want the "Reset" link to remove the date radio selection.
On these product search filters
https://cosmetics-pr-2729-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2729-search-web.london.cloudapps.digital/
=> Only reset radio selection if field has no errors

cosmetics-web/app/models/component.rb, cosmetics-web/app/models/notification.rb, cosmetics-web/spec/factories/notification.rb, cosmetics-web/spec/models/component_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1686)
This validation was already present on the PH range manual values for single-item or non-mixed multi-item notifications.
Bringing the same validation to the multi-item mixed notifications.
https://cosmetics-pr-2734-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2734-search-web.london.cloudapps.digital/
=> Bring ph range size validation to mixed multi-item

cosmetics-web/app/helpers/component_build_helper.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1688)
When the ingredient range has a fractional value, display it properly. At the moment we are displaying "01", we want to display "0.1".
https://cosmetics-pr-2735-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2735-search-web.london.cloudapps.digital/
=> Fix display of fractional ing. concentration range

cosmetics-web/Gemfile.lock, cosmetics-web/app/controllers/poison_centres/ingredients_search_controller.rb, cosmetics-web/app/controllers/poison_centres/notifications_search_controller.rb, cosmetics-web/app/controllers/responsible_persons/search_ingredients_controller.rb, cosmetics-web/app/controllers/responsible_persons/search_notifications_controller.rb, cosmetics-web/db/migrate/20230125101611_add_sort_by_to_search_histories.rb, cosmetics-web/db/schema.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/COSBETA-1698
Change default notifications search sort order to date descending. Also adds sort order to search history to be able to monitor how often users change the default sort order.
https://cosmetics-pr-2747-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2747-search-web.london.cloudapps.digital/
=> Default to date descending sort for notifications search

cosmetics-web/app/views/notifications/_frame_formulation_details.html.erb, cosmetics-web/app/views/notifications/_ingredient_details.html.erb, cosmetics-web/spec/requests/poison_centre_page_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/COSBETA-1711
Makes two fixes to the list of ingredients on the notifications page:
* Removes the frame formulations section if there are none for any of the components of a product (i.e. only exact or range ingredients have been provided)
* Removes individual components from the ingredients list if they don’t have any ingredients listed (mainly if the product has multiple components which have a mix of frame formulations and exact/range ingredients along with NPIS-notifiable ingredients; in this case, components with frame formulations but no NPIS-notifiable ingredients would show as “no ingredients data”)
https://cosmetics-pr-2754-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2754-search-web.london.cloudapps.digital/ …
=> Fix ingredients list on notification page

cosmetics-web/Gemfile, cosmetics-web/Gemfile.lock, cosmetics-web/config/coverband.rb, cosmetics-web/config/routes.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1746)
Sets Coverband to identify areas of code that don't get called in production.
The review app coverage can be accessed through:
https://cosmetics-pr-2751-submit-web.london.cloudapps.digital/coverage/
We had to[ fork & tweak the Coverband gem](https://github.com/danmayer/coverband/compare/main...OfficeForProductSafetyAndStandards:coverband:main) to be able to use it in our service.
The issue is within the Coverband Rack static middleware which, in its default state, triggers our Rails service Content Security Policies errors, blocking Coverband JS code and Coverband report page from loading.
Fortunately, someone else struggled with the same issue and [opened a PR with a …
=> Add Coverband production code usage tool

cosmetics-web/app/controllers/concerns/responsible_person_query_concern.rb, cosmetics-web/app/controllers/poison_centres/ingredients_controller.rb, cosmetics-web/app/helpers/poison_centres_notifications_helper.rb, cosmetics-web/app/views/poison_centres/ingredients/responsible_person_notifications.html.erb, cosmetics-web/app/views/poison_centres/ingredients/responsible_persons.html.erb, cosmetics-web/app/views/poison_centres/shared/_back_links.html.erb, cosmetics-web/app/views/poison_centres/shared/_secondary_navigation.html.erb, cosmetics-web/config/routes.rb, cosmetics-web/spec/controllers/concerns/responsible_person_query_concern_spec.rb, cosmetics-web/spec/features/search/ingredients_list_spec.rb, cosmetics-web/spec/requests/ingredient_list_spec.rb
JIRA links: https://regulatorydelivery.atlassian.net/browse/COSBETA-1737 and https://regulatorydelivery.atlassian.net/browse/COSBETA-1738
Adds two new pages under the ingredients list page:
* Responsible Persons - list of Responsible Persons who have created notifications of products containing a specified ingredient
* Notifications - list of notifications from a specified Responsible Person with products containing a specified ingredient
https://cosmetics-pr-2760-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2760-search-web.london.cloudapps.digital/
Note, this PR must be rebased and merged after https://github.com/OfficeForProductSafetyAndStandards/cosmetic-product-notifications/pull/2756 since it is based on that branch.
=> Add Responsible Persons and Notifications pages

cosmetics-web/app/controllers/responsible_persons/notifications/nanomaterials/build_controller.rb, cosmetics-web/spec/controllers/responsible_persons/notifications/nanomaterials/build_controller_spec.rb
JIRA link: https://regulatorydelivery.atlassian.net/browse/COSBETA-1787
Allows nanomaterials to be switched from non-standard to standard successfully by deleting the association with a nanomaterial notification in this case.
=> Fix nanomaterial purpose update

.github/workflows/deploy.yml
As done with review apps on #2769, we will push a release notification to Sentry after a successful deployment to Production.
=> Add Sentry release tracking to production deploys

cosmetics-web/config/application.rb
Since Rails 7 automatically uses SHA256 and it raises exceptions when trying to decrypt our current production encrypted data.
=> Fix Act. Support hash digest class to SHA1

README.md, cosmetics-web/app/controllers/declaration_controller.rb, cosmetics-web/app/models/concerns/privileges/abstract_concern.rb, cosmetics-web/app/models/concerns/privileges/search_concern.rb, cosmetics-web/app/models/search_user.rb, cosmetics-web/app/policies/poison_centre_notification_policy.rb, cosmetics-web/app/views/errors/wrong_service_for_search_user.html.erb, cosmetics-web/app/views/notifications/_component_details.html.erb, cosmetics-web/db/migrate/20230208115825_add_opss_general_to_user_roles.rb, cosmetics-web/db/migrate/20230208115835_add_opss_enforcement_to_user_roles.rb, cosmetics-web/db/migrate/20230208115847_add_trading_standards_to_user_roles.rb, cosmetics-web/db/schema.rb, cosmetics-web/docs/glossary.md, cosmetics-web/spec/controllers/poison_centres/notifications_controller_spec.rb, cosmetics-web/spec/controllers/poison_centres/notifications_search_controller_spec.rb, cosmetics-web/spec/controllers/search/dashboard_controller_spec.rb, cosmetics-web/spec/factories/user.rb, cosmetics-web/spec/features/search/notification_search_result_nanomaterial_details_spec.rb, cosmetics-web/spec/login_helpers.rb, cosmetics-web/spec/models/search_user_spec.rb, cosmetics-web/spec/policies/poison_centre_notification_policy_spec.rb, cosmetics-web/spec/requests/declaration_requests_spec.rb, cosmetics-web/spec/requests/ingredient_list_spec.rb, cosmetics-web/spec/requests/poison_centre_page_spec.rb, cosmetics-web/spec/requests/root_path_spec.rb, cosmetics-web/spec/requests/user_account_page_spec.rb, cosmetics-web/spec/services/invite_search_user_spec.rb, cosmetics-web/spec/services/one_off/search_user_bulk_inviter_spec.rb
JIRA link: https://regulatorydelivery.atlassian.net/browse/COSBETA-1776
Creates the following new user roles:
* OPSS General
* OPSS Enforcement
* Trading Standards
Keeps the following roles:
* Poison centre (NPIS)
* OPSS Science
Users with the existing MSA role will be migrated manually to one of the newly-created roles separately.
https://cosmetics-pr-2783-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2783-search-web.london.cloudapps.digital/
=> Create new user roles for search service

cosmetics-web/app/models/concerns/privileges/search_concern.rb, cosmetics-web/app/models/search_user.rb, cosmetics-web/app/views/errors/wrong_service_for_search_user.html.erb
All MSA users have been migrated to other roles, so remove the redundant MSA role.
https://cosmetics-pr-2786-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2786-search-web.london.cloudapps.digital/
=> Remove MSA role

cosmetics-web/app/helpers/privileges_helper.rb, cosmetics-web/app/models/concerns/privileges/abstract_concern.rb, cosmetics-web/app/models/concerns/privileges/search_concern.rb, cosmetics-web/app/models/concerns/privileges/submit_concern.rb, cosmetics-web/app/models/responsible_person_address_log.rb, cosmetics-web/app/views/notifications/_responsible_person_details.html.erb, cosmetics-web/spec/factories/responsible_person.rb, cosmetics-web/spec/factories/responsible_person_address_log.rb, cosmetics-web/spec/models/search_user_spec.rb, cosmetics-web/spec/rails_helper.rb, cosmetics-web/spec/requests/poison_centre_page_spec.rb
JIRA link: https://regulatorydelivery.atlassian.net/browse/COSBETA-1317
Displays the address history for a Responsible Person on notification pages, only for MSA users.
https://cosmetics-pr-2780-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2780-search-web.london.cloudapps.digital/
=> Show Responsible Person address history

cosmetics-web/app/assets/files/frame_formulations/categories.json, cosmetics-web/app/views/responsible_persons/notifications/components/build/select_formulation_type.html.erb, cosmetics-web/spec/controllers/responsible_persons/notifications/components/build_controller_spec.rb, cosmetics-web/spec/factories/component.rb
JIRA link: https://regulatorydelivery.atlassian.net/browse/COSBETA-1824
Hides the option to choose a frame formulation (as opposed to listing ingredients by exact or range concentrations) when the chosen category does not have any frame formulations associated with it.
Also removes some categories where either there were no frame formulations or had no ingredient data to prevent them appearing as options.
https://cosmetics-pr-2785-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2785-search-web.london.cloudapps.digital/
=> Hide frame formulations option when unavailable

cosmetics-web/app/views/submit/landing_page/index.html.erb
This was set up during testing on the review app to be able to monitor the integration with Sentry easily, forgot to remove it before merging to master.
=> Remove Submit landing page from unused view alert

cosmetics-web/app/controllers/responsible_persons/contact_persons_controller.rb, cosmetics-web/spec/features/submit/responsible_person/creation_spec.rb, cosmetics-web/spec/features/submit/responsible_person/multiple_responsible_person_creation_from_the_same_user_spec.rb
JIRA link: https://regulatorydelivery.atlassian.net/browse/COSBETA-1800
Remove the extraneous “success” text in the body of the confirmation banner.
https://cosmetics-pr-2793-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2793-search-web.london.cloudapps.digital/
=> Fix success text for Responsible Person

cosmetics-web/Gemfile, cosmetics-web/Gemfile.lock
This resolves a compatibility issue that forced us to point to a specific commit in the gemfile.
=> Point ActiveHash gem to its latest version

cosmetics-web/app/models/trigger_question.rb, cosmetics-web/app/models/trigger_question_element.rb, cosmetics-web/lib/tasks/trigger_questions.rake, cosmetics-web/spec/factories/trigger_question.rb, cosmetics-web/spec/factories/trigger_question_element.rb, cosmetics-web/spec/lib/tasks/deleted_notifications_spec.rb, cosmetics-web/spec/lib/tasks/trigger_questions_spec.rb
When the service allowed importing/parsing data from the European CPNP service, some TriggerQuestions and TriggerQuestionElements were created without being associated with a component/notification or, in the case of the TQElements,  to any TQ.
As the ERD shows, if a TQElement is not associated with a TQ, or a TQ is not associated with a Component, there is no way they can be related with any notification, so it is orphaned invalid data.
- Orphaned Trigger Questions not associated with any component: 93.580
- Orphaned Trigger Question Elements not associated with any TQ:  12
1. Following up on the `TODO` comment introduced in their model associations, removing the `optional` association parameter.
2. Sending an alert to Sentry anytime any of the orphaned TQ/TQE gets loaded from DB. This …
=> Cleanup orphaned Trigger Question data

cosmetics-web/app/views/responsible_persons/notifications/product/add_product_image.html.erb
"back_to_edit" param is actually being set as true with some flows.
Removing the flag as it is alerting about it being hit.
=> Remove "UnusedCodeAlerting" flag from called code

cosmetics-web/app/models/trigger_question.rb, cosmetics-web/app/models/trigger_question_element.rb
Follow up on: https://github.com/OfficeForProductSafetyAndStandards/cosmetic-product-notifications/pull/2801
Remove the alerts set to identify any case when an orphaned TriggerQuestion or TriggerQuestionElement gets loaded from DB.
It turns out this needs to be removed BEFORE calling the rake task (as I painfully noticed), not after.
After this, I will trigger the task and then open a further PR to remove the one-off rake task code.
=> Remove alerts for loaded orphaned TQ/TQE

cosmetics-web/app/views/responsible_persons/delete_items/show.html.erb, cosmetics-web/app/views/responsible_persons/notifications/product/single_or_multi_component.html.erb, cosmetics-web/spec/support/helpers/product_wizard.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/COSBETA-1807
Adds new and clarifies existing messaging about not being able to switch from a multi-item kit to a single item kit product once the choice has been made.
https://cosmetics-pr-2816-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2816-search-web.london.cloudapps.digital/
=> Add and clarify messages about multi-item kits

cosmetics-web/app/controllers/responsible_persons/notifications/components/build_controller.rb, cosmetics-web/app/forms/responsible_persons/notifications/ingredient_concentration_form.rb, cosmetics-web/app/helpers/concentration_helper.rb, cosmetics-web/app/helpers/ingredient_helper.rb, cosmetics-web/app/models/ingredient.rb, cosmetics-web/app/views/application/_formulation_table.html.erb, cosmetics-web/app/views/responsible_persons/notifications/_ingredients.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/_exact_concentration_input.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/_ingredient_exact_concentration_fields.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/_ingredient_range_concentration_option.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/add_ingredient_exact_concentration.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/add_ingredient_npis_needs_to_know.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/add_ingredient_range_concentration.html.erb, cosmetics-web/config/locales/en.yml, cosmetics-web/db/migrate/20230303111821_add_used_for_multiple_shades_to_ingredients.rb, cosmetics-web/db/schema.rb, cosmetics-web/spec/controllers/responsible_persons/notifications/components/build_controller_spec.rb, cosmetics-web/spec/factories/component.rb, cosmetics-web/spec/features/submit/notification_wizard/ingredients/adding_ingredients_to_components_spec.rb, cosmetics-web/spec/features/submit/notification_wizard/ingredients/editing_ingredients_on_components_spec.rb, cosmetics-web/spec/features/submit/responsible_person/notifications_spec.rb, cosmetics-web/spec/forms/responsible_persons/notifications/ingredient_concentration_form_spec.rb, cosmetics-web/spec/models/component_spec.rb, cosmetics-web/spec/services/notification_cloner/base_spec.rb
JIRA tickets: https://regulatorydelivery.atlassian.net/browse/COSBETA-1745 and https://regulatorydelivery.atlassian.net/browse/COSBETA-1682
Allows users to enter a maximum concentration for an ingredient that is used for multiple shades of a product.
https://cosmetics-pr-2819-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2819-search-web.london.cloudapps.digital/
=> Allow “maximum concentration” for multi shade ingredients

cosmetics-web/app/views/responsible_persons/notifications/components/build/_add_ingredient_concentration.html.erb
Fixes the <abbr> HTML tag to not be rendered in the “skip NPIS tables” link.
https://cosmetics-pr-2831-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2831-search-web.london.cloudapps.digital/
=> Fix HTML tags in “skip NPIS tables” link

cosmetics-web/app/forms/responsible_persons/notifications/ingredient_concentration_form.rb, cosmetics-web/app/models/component.rb, cosmetics-web/app/models/ingredient.rb, cosmetics-web/spec/factories/component.rb, cosmetics-web/spec/forms/responsible_persons/notifications/ingredient_concentration_form_spec.rb, cosmetics-web/spec/models/component_spec.rb, cosmetics-web/spec/models/ingredient_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1858)
For multi-shaded components/products, when selecting ingredient range concentration ingredients, the ingredients cannot be added due to a validation that can only be fulfilled by the exact ingredients.
This blocks the submission of range ingredients on multi-shaded components.
The form does not display the selector for this value when filling a range concentration ingredient.
The validation was blocking the form from being submitted with range concentration ingredients.
In the same way, the model validation blocked cloning notifications with range ingredients, since the
"used_for_multiple_shades" isn't filled for those and fails validation for the new records.
Solution: Make the validation optional, as we do not …
=> Fix ingredient used for multiple shades validation issue

cosmetics-web/app/forms/responsible_persons/notifications/ingredient_concentration_form.rb, cosmetics-web/app/models/component.rb, cosmetics-web/app/models/ingredient.rb, cosmetics-web/spec/features/submit/notification_wizard/ingredients/adding_ingredients_to_components_spec.rb, cosmetics-web/spec/forms/responsible_persons/notifications/ingredient_concentration_form_spec.rb, cosmetics-web/spec/models/component_spec.rb, cosmetics-web/spec/models/ingredient_spec.rb
[Jira ticket](https://regulatorydelivery.atlassian.net/browse/COSBETA-1861)
- Allows poisonous ingredients for a range multi-shaded component not to have a value for the "used for multiple shades" attribute.
- Covers with feature specs the different ingredient flows for multi-shaded notification components.
https://cosmetics-pr-2835-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2835-search-web.london.cloudapps.digital/
=> Bugfix: Allow poisonous range ingredients for multi-shade components without "used for multiple shades" value

cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb, cosmetics-web/app/views/responsible_persons/notifications/_complete_notifications_table.html.erb, cosmetics-web/app/views/responsible_persons/notifications/_notification_nav.html.erb, cosmetics-web/app/views/responsible_persons/notifications/show.html.erb, cosmetics-web/spec/controllers/responsible_persons/notifications_controller_spec.rb
Since the team discovered some unintended behaviours after release, we are disabling the archiving feature until we clarify/fix it.
- Disabled "Archived" page in the RP notifications index.
- Disabled link to archiving each notification from the RP notifications list.
- Disabled the button for archiving notifications in their individual pages.
- Disabled controller actions that archive/unarchive notifications.
https://cosmetics-pr-2843-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2843-search-web.london.cloudapps.digital/
=> Disable notification archiving

cosmetics-web/app/forms/responsible_persons/notifications/product/single_or_multi_component_form.rb, cosmetics-web/app/views/responsible_persons/notifications/product/single_or_multi_component.html.erb, cosmetics-web/spec/features/submit/notification_wizard/single_to_multi_item_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/COSBETA-1857
Changes the default number of components for a multi item kit to “2” when:
* Creating a new multi item kit (current default: empty)
* Changing an existing draft of a single item kit to a multi item kit (current default: 1)
* Cloning an existing single item kit and changing to a multi item kit (current default: 1)
https://cosmetics-pr-2848-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2848-search-web.london.cloudapps.digital/
=> Change default components count for multi item kits

cosmetics-web/app/models/notification.rb, cosmetics-web/app/services/notification_cloner/base.rb, cosmetics-web/spec/features/submit/notification_wizard/notification_cloning_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/COSBETA-1842
Removes the following fields from being cloned:
* Is the product intended to be used on children under 3 years old?
* Does [component] contain category 1A or 1B CMR substances?
Also removes the cloning of CMRs.
https://cosmetics-pr-2856-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2856-search-web.london.cloudapps.digital/
=> Remove some fields from cloned notifications

cosmetics-web/app/services/notification_cloner/base.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/COSBETA-1874
Fixes a bug where a notification that has one or more components with no routing answers defined raises an exception on clone.
https://cosmetics-pr-2857-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2857-search-web.london.cloudapps.digital/
=> Fix notification cloning for components with no routing answers

cosmetics-web/app/models/nanomaterial_notification.rb, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/models/nanomaterial_notification_spec.rb, cosmetics-web/spec/requests/nanomaterial_notifications_spec.rb
https://regulatorydelivery.atlassian.net/browse/COSBETA-1822
Here we update the `NanomaterialNotification#notified_to_eu_on=` method to assign a null date if the EU has **not** been notified. This might happen if the user selects 'Yes', enters a date, then changes their answer to 'No'
Previously, this raised an error and the user would have to go back and manually remove the date.
I can see some issues with the existing code:
- We use a [complex method to assign the date](https://github.com/OfficeForProductSafetyAndStandards/cosmetic-product-notifications/blob/5860e464171ccb314a8bef4bb59d88451efeddb6/cosmetics-web/app/models/nanomaterial_notification.rb#L30). Rails should be able to handle good/bad dates.
- The  ActiveRecord `#notified_to_eu_on=` is overridden to prevent nil values. Yet, …
=> Remove date restriction from nanomaterials journey

cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb, cosmetics-web/app/models/concerns/notification_state_concern.rb, cosmetics-web/app/views/responsible_persons/notifications/_complete_notifications_table.html.erb, cosmetics-web/app/views/responsible_persons/notifications/_notification_nav.html.erb, cosmetics-web/app/views/responsible_persons/notifications/index.html.erb, cosmetics-web/app/views/responsible_persons/notifications/show.html.erb, cosmetics-web/spec/controllers/responsible_persons/notifications_controller_spec.rb, cosmetics-web/spec/factories/notification.rb, cosmetics-web/spec/features/submit/notifications_archiving_spec.rb
Reintroduction of [notification archiving](https://github.com/OfficeForProductSafetyAndStandards/cosmetic-product-notifications/pull/2836) after[ disabling it](https://github.com/OfficeForProductSafetyAndStandards/cosmetic-product-notifications/pull/2843) due to issues with the notification completion date and possible desired further discussions about the flow.
Changes over the original flow:
- Keep the original "UK Notified" (`notification_complete_at) for the notification, even after archiving and unarchiving it. Disables notifications from being deleted after unarchived past 7 days from their original submission/completion.
- Modify confirmation banner width to fit the full page (https://regulatorydelivery.atlassian.net/browse/COSBETA-1865) …
=> Reintroduce notification archiving

.github/workflows/deploy.yml, .github/workflows/review-apps-delete-dangling.yml, .github/workflows/review-apps-delete.yml, .github/workflows/review-apps.yml
There is an issue with Cloudfoundry CDN providing their client binaries download, as it has recently started rejecting the download attempts from CURL client.
To solve it, we are removing CURL user agent from the CF client download requests.
More context: https://github.com/cloudfoundry/cli/issues/2390#issuecomment-1486526928
=> Fix CloundFoundry client download from GH actions

cosmetics-web/app/views/responsible_persons/notifications/product/add_product_image.html.erb, cosmetics-web/spec/features/submit/notification_wizard/adding_and_removing_label_images_spec.rb, cosmetics-web/spec/support/matchers/capybara_matchers.rb
https://regulatorydelivery.atlassian.net/browse/COSBETA-1855
When an image is successfully uploaded and the user wants to add another image (rendering the image upload template again), we display a success notification banner.
https://cosmetics-pr-2863-submit-web.london.cloudapps.digital/
=> Introduce a Success Notification Banner for image uploads

cosmetics-web/app/services/notification_cloner/base.rb, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/features/submit/notification_wizard/notification_cloning_spec.rb, cosmetics-web/spec/forms/responsible_persons/notifications/product/contains_nanomaterials_form_spec.rb
https://regulatorydelivery.atlassian.net/browse/COSBETA-1859
If a notification does *not* contain nano materials, then we remove the
`contains_nanomaterials` question from the notification's `routing_questions_answers`
Here we also fix an incorrect validation error message:
'mulit-item kit' was displayed, instead of 'nanomaterial'
Testing note: You will need to create a notification manually, and clone that.
If you clone a notification that was created with seed data, the 
`new_notification.routing_questions_answers` attribute won't be set properly,
https://cosmetics-pr-2868-submit-web.london.cloudapps.digital/
=> Remove default responses from nanomaterials

cosmetics-web/app/views/responsible_persons/notifications/components/build/_add_ingredient_concentration.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/add_ingredient_exact_concentration.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/add_ingredient_npis_needs_to_know.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/add_ingredient_range_concentration.html.erb, cosmetics-web/spec/controllers/responsible_persons/notifications/components/build_controller_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/COSBETA-1889
Removes the link to upload an ingredients CSV if the ingredient is a range ingredient since these are not yet supported for CSV upload.
https://cosmetics-pr-2881-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2881-search-web.london.cloudapps.digital/
=> Remove CSV upload link for range ingredients

cosmetics-web/app/views/layouts/_footer.html.erb
Removes the “how to create an ingredient CSV” help link from the footer since it is already included on relevant pages.
https://regulatorydelivery.atlassian.net/browse/COSBETA-1884
https://cosmetics-pr-2893-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2893-search-web.london.cloudapps.digital/
No
=> Remove CSV link from footer

cosmetics-web/app/views/poison_centres/notifications_search/_results.html.erb, cosmetics-web/app/views/responsible_persons/search_notifications/_results.html.erb, cosmetics-web/spec/features/search/notification_search_spec.rb, cosmetics-web/spec/features/submit/responsible_person/search_notifications_spec.rb
Fixes remembering the selected notification status when editing a search query.
https://regulatorydelivery.atlassian.net/browse/COSBETA-1924
N/A
https://cosmetics-pr-2894-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2894-search-web.london.cloudapps.digital/
No
=> Remember notification status field when editing search

cosmetics-web/app/controllers/responsible_persons/drafts_controller.rb, cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb
Fixes an issue where a failed antivirus check for an image results in a non-existant method being called.
Removing this path allows the `AcceptAndSubmitValidator` to return error messages in this instance.
https://regulatorydelivery.atlassian.net/browse/COSBETA-1936
N/A
https://cosmetics-pr-2906-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2906-search-web.london.cloudapps.digital/
No
=> Fix failed antivirus check error

cosmetics-web/app/controllers/application_controller.rb, cosmetics-web/app/controllers/concerns/cookies_concern.rb, cosmetics-web/app/controllers/concerns/secondary_authentication_concern.rb, cosmetics-web/config/initializers/devise.rb
Adds the `secure` and `httponly` flags to all cookies to limit how they can be read.
https://regulatorydelivery.atlassian.net/browse/COSBETA-1930
N/A
https://cosmetics-pr-2912-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2912-search-web.london.cloudapps.digital/
No
=> Make all cookies secure and HttpOnly

cosmetics-web/app/assets/stylesheets/component_build.scss
Fixes an alignment issue on the CMRs page where half-width fields have errors.
https://regulatorydelivery.atlassian.net/browse/COSBETA-1979
https://cosmetics-pr-2918-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2918-search-web.london.cloudapps.digital/
No
=> Fix error message alignment on CMRs page

cosmetics-web/config/scout_apm.yml
Disable Scout APM instrumentation of `Net::HTTP` to prevent a conflict with Sentry.
See https://github.com/getsentry/sentry-ruby/issues/1427#issuecomment-932677359 for more information.
https://regulatorydelivery.atlassian.net/browse/COSBETA-1991
N/A
https://cosmetics-pr-2930-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2930-search-web.london.cloudapps.digital/
No
=> Fix Scout APM instrumentation issue

.github/workflows/deploy.yml, .github/workflows/erd.yml, cosmetics-web/docs/deployment.md, cosmetics-web/docs/opensearch.md
Change GitHub workflows to trigger on merges to `main` since the branch name was changed from `master`.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2021
N/A
https://cosmetics-pr-2947-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2947-search-web.london.cloudapps.digital/
No
=> Update master to main for GitHub workflows

cosmetics-web/app/models/ingredient.rb
- Sentry is alerting that the 'greater than 0' validation is preventing users from cloning some notifications
- So we are removing the validation rule
Sentry error: https://beis.sentry.io/issues/3989855730/?project=1398436
https://regulatorydelivery.atlassian.net/browse/COSBETA-2022
=> Allow minimum_concentration equal to zero

cosmetics-web/app/controllers/responsible_persons/notifications/components/build_controller.rb, cosmetics-web/spec/factories/component.rb, cosmetics-web/spec/features/submit/notification_wizard/category_spec.rb
Avoid displaying the sub_sub_categories page when there is only one option to be displayed:
- Instead, we store the default sub_sub_category and the user proceeds to the next step
- We also check the back button action and choose whether to display the sub_category or the sub_sub_category page
https://regulatorydelivery.atlassian.net/browse/COSBETA-1845
https://cosmetics-pr-2955-submit-web.london.cloudapps.digital/
=> Avoid displaying sub_sub_categories when there is only one option

cosmetics-web/app/models/component.rb, cosmetics-web/spec/features/submit/notification_wizard/shades_spec.rb
Before saving a component, we reject any blank shades.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2010
https://cosmetics-pr-2966-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2966-search-web.london.cloudapps.digital/
=> Ensure a components does not have any blank shades

cosmetics-web/app/helpers/responsible_persons/notifications_helper.rb
When the pH is not required, we display:
`pH` = `N/A` on the notification summary page
https://regulatorydelivery.atlassian.net/browse/COSBETA-2030
https://cosmetics-pr-2977-submit-web.london.cloudapps.digital/
https://cosmetics-pr-2977-search-web.london.cloudapps.digital/
=> Prefer N/A on summary page when the pH is not required

cosmetics-web/.env.development.example, cosmetics-web/db/seeds.rb
Remove SearchUser creation from seeds file
- If we try to create a SearchUser and a SubmitUser with the same email address,
we get a validation error
Ensure the suggested SEED_USER is valid
- We now validate that a user#name does not contain underscores
=> Fix database seeds

cosmetics-web/app/controllers/responsible_persons/notifications/components/build_controller.rb, cosmetics-web/spec/features/submit/notification_wizard/ingredients/removing_ingredients_from_components_spec.rb
Scenario:
- A user 'adds' an ingredient, and then changes their mind and tries to 'remove' it, there is a validation error
Solution:
- For an unsaved ingredient, reload the component and re-render the page
Note:
- There was a requirement to implement the ingredients form without javascript. If we had used javascript, we would have useful rails helpers, instead of this params-based approach.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2007
https://cosmetics-pr-3007-submit-web.london.cloudapps.digital/
=> Remove an ingredient when the form fields are blank

cosmetics-web/app/forms/responsible_persons/notifications/components/bulk_ingredient_upload_form.rb, cosmetics-web/spec/fixtures/files/exact_ingredients_long_name.csv, cosmetics-web/spec/forms/responsible_persons/notifications/components/bulk_ingredient_upload_form_spec.rb
This latest deployment has broken other uploads. It may be due to the ASCII character:
```
opts = opts.transform_values { |v| v.to_s.strip.gsub(/[[:^ascii:]]/, "") }
```
https://regulatorydelivery.atlassian.net/browse/COSBETA-2113
=> Revert: CSV Uploads - Remove validations on file upload

cosmetics-web/app/models/ingredient.rb, cosmetics-web/app/views/responsible_persons/notifications/_ingredients.html.erb, cosmetics-web/spec/features/submit/notification_wizard/ingredients/using_csv_file_spec.rb, cosmetics-web/spec/fixtures/files/range_ingredients.csv, cosmetics-web/spec/models/ingredient_spec.rb
Validation for minimum and maximum range for ingredients now only applies if the maximum is set to less than the minimum
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2114
https://cosmetics-pr-3031-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3031-search-web.london.cloudapps.digital/
https://cosmetics-pr-3031-support-web.london.cloudapps.digital/
=> allow minimum and maximum ingredient concentration to be equal

cosmetics-web/app/forms/responsible_persons/notifications/components/bulk_ingredient_upload_form.rb, cosmetics-web/spec/features/submit/notification_wizard/ingredients/using_csv_file_spec.rb
Adds validation for file type on ingredient. bulk upload.
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2036
https://cosmetics-pr-3032-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3032-search-web.london.cloudapps.digital/
https://cosmetics-pr-3032-support-web.london.cloudapps.digital/
=> add validation for file type on bulk upload

cosmetics-web/app/models/support_user.rb, cosmetics-web/app/views/secondary_authentication/sms/resend/new.html.erb, cosmetics-web/spec/models/support_user_spec.rb
Changes the message seen by OPSS support users on the resend. text message screen.
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2121
https://cosmetics-pr-3052-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3052-search-web.london.cloudapps.digital/
https://cosmetics-pr-3052-support-web.london.cloudapps.digital/
=> add alternative wording for opss support users on resend text message screen

cosmetics-web/app/models/responsible_person.rb, cosmetics-web/spec/factories/versions.rb, cosmetics-web/spec/features/support/history_spec.rb, cosmetics-web/support_portal/app/controllers/support_portal/history_controller.rb, cosmetics-web/support_portal/app/helpers/support_portal/history_helper.rb, cosmetics-web/support_portal/app/models/support_portal/history_search.rb, cosmetics-web/support_portal/app/services/support_portal/find_support_user_changes.rb, cosmetics-web/support_portal/app/views/support_portal/dashboard/index.html.erb, cosmetics-web/support_portal/app/views/support_portal/history/index.html.erb, cosmetics-web/support_portal/config/routes.rb
Add history page for SupportUsers to search. through changes to ResponsiblePersons and notifications made by other SupportUsers.
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2150
https://cosmetics-pr-3068-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3068-search-web.london.cloudapps.digital/
https://cosmetics-pr-3068-support-web.london.cloudapps.digital/
=> add history page for support users

cosmetics-web/app/views/my_account/show.html.erb, cosmetics-web/spec/features/account/sign_in_spec.rb
Adds non-functional links to support user account management page
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2110
=> Add change links and user management on account page

cosmetics-web/app/forms/invite_support_user_form.rb, cosmetics-web/app/views/my_account/show.html.erb, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/features/support/invite_support_user_spec.rb, cosmetics-web/spec/forms/invite_support_user_form_spec.rb, cosmetics-web/support_portal/app/controllers/support_portal/invite_support_users_controller.rb, cosmetics-web/support_portal/app/views/support_portal/invite_support_users/new.html.erb, cosmetics-web/support_portal/config/routes.rb
Adds ability for support users to invite new support users
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2142
https://cosmetics-pr-3073-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3073-search-web.london.cloudapps.digital/
https://cosmetics-pr-3073-support-web.london.cloudapps.digital/
=> add invite support user functionality

cosmetics-web/app/views/my_account/show.html.erb
Removes name and mobile number rows for SupportUsers in MyAccount section
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2110
https://cosmetics-pr-3075-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3075-search-web.london.cloudapps.digital/
https://cosmetics-pr-3075-support-web.london.cloudapps.digital/
=> remove name and mobile number rows from my account section

cosmetics-web/app/models/concerns/privileges/abstract_concern.rb, cosmetics-web/app/models/concerns/privileges/search_concern.rb, cosmetics-web/app/models/search_user.rb, cosmetics-web/app/models/support_user.rb, cosmetics-web/app/views/errors/wrong_service_for_search_user.html.erb, cosmetics-web/db/migrate/20230807095619_add_opss_imt_to_user_roles.rb, cosmetics-web/db/schema.rb, cosmetics-web/docs/users_and_roles.md, cosmetics-web/spec/controllers/poison_centres/notifications_controller_spec.rb, cosmetics-web/spec/controllers/poison_centres/notifications_search_controller_spec.rb, cosmetics-web/spec/controllers/search/dashboard_controller_spec.rb, cosmetics-web/spec/factories/user.rb, cosmetics-web/spec/features/search/notification_search_result_nanomaterial_details_spec.rb, cosmetics-web/spec/login_helpers.rb, cosmetics-web/spec/models/search_user_spec.rb, cosmetics-web/spec/models/support_user_spec.rb, cosmetics-web/spec/policies/poison_centre_notification_policy_spec.rb, cosmetics-web/spec/requests/declaration_requests_spec.rb, cosmetics-web/spec/requests/ingredient_list_spec.rb, cosmetics-web/spec/requests/poison_centre_page_spec.rb, cosmetics-web/spec/requests/root_path_spec.rb, cosmetics-web/spec/requests/user_account_page_spec.rb
Adds a new search user role for OPSS IMT, with the same privileges as the OPSS Enforcement role.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2211
N/A
https://cosmetics-pr-3076-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3076-search-web.london.cloudapps.digital/
https://cosmetics-pr-3076-support-web.london.cloudapps.digital/
No
=> Add OPSS IMT role

cosmetics-web/app/forms/invite_support_user_form.rb, cosmetics-web/app/validators/email_validator.rb, cosmetics-web/config/locales/en.yml, cosmetics-web/db/seeds.rb, cosmetics-web/spec/factories/user.rb, cosmetics-web/spec/features/account/change_email_spec.rb, cosmetics-web/spec/features/support/invite_support_user_spec.rb, cosmetics-web/spec/forms/invite_support_user_form_spec.rb, cosmetics-web/spec/models/search_user_spec.rb, cosmetics-web/spec/models/submit_user_spec.rb, cosmetics-web/spec/models/support_user_spec.rb, cosmetics-web/spec/support/shared_examples/common_user_tests.rb
Add validation for gov.uk email addresses and implement for support users
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2136
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2167
https://cosmetics-pr-3078-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3078-search-web.london.cloudapps.digital/
https://cosmetics-pr-3078-support-web.london.cloudapps.digital/
=> add validation for gov.uk email addresses

cosmetics-web/config/locales/en.yml, cosmetics-web/spec/features/submit/notification_wizard/ingredients/adding_ingredients_to_components_spec.rb
Changes the wording when NPIS needs to be notified about an ingredient.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2144
https://cosmetics-pr-3081-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3081-search-web.london.cloudapps.digital/
https://cosmetics-pr-3081-support-web.london.cloudapps.digital/
No
=> Remove poisonous wording

cosmetics-web/app/views/responsible_persons/notifications/_ingredients.html.erb
Prevents ingredients marked as multi-shade from being shown as “maximum concentration” where the product is later changed to non-multi-shade.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2203
N/A
https://cosmetics-pr-3086-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3086-search-web.london.cloudapps.digital/
https://cosmetics-pr-3086-support-web.london.cloudapps.digital/
No
=> Fix display of maximum concentration

cosmetics-web/app/models/notification.rb, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/models/notification_spec.rb
Removes the requirement to choose a unique product name when cloning a notification.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2190
N/A
https://cosmetics-pr-3079-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3079-search-web.london.cloudapps.digital/
https://cosmetics-pr-3079-support-web.london.cloudapps.digital/
No
=> Remove notification clone naming restrictions

cosmetics-web/app/controllers/secondary_authentication/recovery_code_controller.rb
Fixes recovery codes to only allow each one to be used once.
N/A
N/A
https://cosmetics-pr-3105-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3105-search-web.london.cloudapps.digital/
https://cosmetics-pr-3105-support-web.london.cloudapps.digital/
No
=> Fix recovery code one-time usage

cosmetics-web/app/models/responsible_person.rb, cosmetics-web/app/models/search_user.rb, cosmetics-web/config/brakeman.ignore, cosmetics-web/config/locales/en.yml, cosmetics-web/spec/features/support/account_administration_spec.rb, cosmetics-web/spec/features/support/history_spec.rb, cosmetics-web/support_portal/app/controllers/support_portal/account_administration_controller.rb, cosmetics-web/support_portal/app/helpers/support_portal/account_administration_helper.rb, cosmetics-web/support_portal/app/helpers/support_portal/history_helper.rb, cosmetics-web/support_portal/app/views/support_portal/account_administration/edit_role.html.erb, cosmetics-web/support_portal/app/views/support_portal/account_administration/index.html.erb, cosmetics-web/support_portal/app/views/support_portal/account_administration/invite_search_user.html.erb, cosmetics-web/support_portal/app/views/support_portal/account_administration/search.html.erb, cosmetics-web/support_portal/app/views/support_portal/account_administration/search_results.html.erb, cosmetics-web/support_portal/app/views/support_portal/account_administration/show.html.erb, cosmetics-web/support_portal/config/routes.rb
Adds functionality to invite new search users and change the role of existing search users.
https://regulatorydelivery.atlassian.net/browse/COSBETA-2179, https://regulatorydelivery.atlassian.net/browse/COSBETA-2180, https://regulatorydelivery.atlassian.net/browse/COSBETA-2181, https://regulatorydelivery.atlassian.net/browse/COSBETA-2186
https://cosmetics-pr-3103-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3103-search-web.london.cloudapps.digital/
https://cosmetics-pr-3103-support-web.london.cloudapps.digital/
No
=> OSU Support Portal: invite search user and change role

cosmetics-web/app/services/invite_support_user.rb, cosmetics-web/spec/services/invite_support_user_spec.rb
Sets deacvtivated_at to nil for invited support users.
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2260
=> add ability to reinvite deactivated users

cosmetics-web/app/views/responsible_persons/notifications/nanomaterials/build/_purposes_form.html.erb, cosmetics-web/app/views/responsible_persons/notifications/product/contains_nanomaterials.html.erb
Adds links to the nanomaterial guideance in two forms - one for selecting whether or not a product has them, and the other to describe them
https://regulatorydelivery.atlassian.net/browse/COSBETA-2261
https://cosmetics-pr-3155-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3155-search-web.london.cloudapps.digital/
https://cosmetics-pr-3155-support-web.london.cloudapps.digital/
=> Add nanomaterial explainer copy - COSBETA-2261

cosmetics-web/app/views/responsible_persons/notifications/product/for_children_under_three.html.erb
Adds help text drop down for "Children under 3?" question on submit
https://regulatorydelivery.atlassian.net/browse/COSBETA-2125
before
after
Help text expanded 
Form validation failure still works 
https://cosmetics-pr-3179-submit-web.london.cloudapps.digital/
=> Help text for "children under 3" question - COSBETA-2125

cosmetics-web/app/helpers/responsible_persons/notifications_helper.rb, cosmetics-web/app/views/responsible_persons/notifications/_product_details.html.erb, cosmetics-web/spec/helpers/responsible_persons/notifications_helper_spec.rb
Remove editable links from submitted notification summary page
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2287
https://cosmetics-pr-3193-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3193-search-web.london.cloudapps.digital/
https://cosmetics-pr-3193-support-web.london.cloudapps.digital/
=> remove editable links from submitted notifications

cosmetics-web/app/views/secondary_authentication/app/new.html.erb, cosmetics-web/app/views/secondary_authentication/method/new.html.erb, cosmetics-web/app/views/secondary_authentication/recovery_code/new.html.erb, cosmetics-web/app/views/secondary_authentication/sms/new.html.erb
Adds back link to authentication code choice page
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2189
https://cosmetics-pr-3189-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3189-search-web.london.cloudapps.digital/
https://cosmetics-pr-3189-support-web.london.cloudapps.digital/
=> add back link to authentication code page

cosmetics-web/app/helpers/draft_helper.rb, cosmetics-web/app/helpers/responsible_persons/notifications_helper.rb, cosmetics-web/app/validators/accept_and_submit_validator.rb, cosmetics-web/spec/factories/notification.rb, cosmetics-web/spec/helpers/responsible_persons/notifications_helper_spec.rb
When a notification is cloned, one of the attributes that is not cloned is whether the product is suitable for under threes. This question needs to be answered for every notification. This is now enforced on cloned notifications.
https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-2295
https://cosmetics-pr-3197-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3197-search-web.london.cloudapps.digital/
https://cosmetics-pr-3197-support-web.london.cloudapps.digital/
=> enforce under three question on cloned notifications

cosmetics-web/app/views/responsible_persons/notifications/components/build/add_cmrs.html.erb, cosmetics-web/app/views/responsible_persons/notifications/components/build/add_shades.html.erb, cosmetics-web/spec/features/submit/notification_wizard/ingredients/adding_ingredients_to_components_spec.rb, cosmetics-web/spec/features/submit/notification_wizard/ingredients/using_csv_file_spec.rb, cosmetics-web/spec/features/submit/notification_wizard/shades_spec.rb
Fixes the error message shown when no shades are entered to correctly link to the first shade text box.
https://regulatorydelivery.atlassian.net/browse/PSD-2109
https://cosmetics-pr-3214-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3214-search-web.london.cloudapps.digital/
https://cosmetics-pr-3214-support-web.london.cloudapps.digital/
=> Fix shades error link

cosmetics-web/app/mailers/search_notify_mailer.rb, cosmetics-web/app/models/user.rb, cosmetics-web/support_portal/app/controllers/support_portal/account_administration_controller.rb
Sends an email when a search user account is reactivated via the Support Portal.
https://regulatorydelivery.atlassian.net/browse/PSD-2106
N/A
https://cosmetics-pr-3222-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3222-search-web.london.cloudapps.digital/
https://cosmetics-pr-3222-support-web.london.cloudapps.digital/
=> Send email on account reactivation

cosmetics-web/support_portal/app/helpers/support_portal/history_helper.rb
Changes the Support Portal change history log to display address changes in a logical order rather than randomly.
https://regulatorydelivery.atlassian.net/browse/PSD-2107
N/A
https://cosmetics-pr-3223-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3223-search-web.london.cloudapps.digital/
https://cosmetics-pr-3223-support-web.london.cloudapps.digital/
=> OSU Support Portal: display address changes in logical order

.github/workflows/deploy-production.yml, cosmetics-web/spec/smoke/search_smoke_test_spec.rb
* Fixes the name of the link clicked for the smoke test
* Updates the Sentry organisation used for release creation
https://regulatorydelivery.atlassian.net/browse/PSD-2424
N/A
https://cosmetics-pr-3264-submit-web.london.cloudapps.digital/
https://cosmetics-pr-3264-search-web.london.cloudapps.digital/
https://cosmetics-pr-3264-support-web.london.cloudapps.digital/
=> Fix smoke test and Sentry notification

cosmetics-web/app/views/layouts/_navbar.html.erb, cosmetics-web/spec/features/submit/notifications_dashboard_spec.rb
the responsible person Name shown in the Nav bar of the Project screen was throwing Nil class error, which i have fixed using the Nil check
=> [PSD-2553] - fixed the Nil class error on the object responsible_person 

cosmetics-web/app/views/responsible_persons/drafts/_product_details.html.erb
Responsible persons notification product details link causes error when in draft mode due to component being nil.
[](https://regulatorydelivery.atlassian.net/browse/PSD-3603)
=> SCPN: ResponsiblePersons Drafts Controller Show error

cosmetics-web/spec/helpers/support_portal/history_helper_spec.rb, cosmetics-web/support_portal/app/helpers/support_portal/history_helper.rb
A `NoMethodError` occurs when displaying ResponsiblePerson history changes because we try to access array indices on nil values when address fields are missing or partially updated.
* Added proper nil handling in `display_responsible_person_action_details`
* Introduced `BUSINESS_TYPES` constant for consistent business type display
* Added `responsible_person_business_type` helper method
* Improved handling of address changes to maintain order and skip nil values
* Added comprehensive test coverage for all edge cases
This change prevents errors when viewing history for ResponsiblePerson records with:
* Partial address updates
* Empty address fields
* Missing address components
* Business type changes
* Added specs covering complete, partial, and empty address changes
* Added specs for …
=> PSD-3621-SCPN-Template_Error

cosmetics-web/lib/tasks/map_legacy_roles_to_rolify.rake
We are now looking at populating the roles table for each user. 
For this we will need to run the following command. This will populate the roles table based on the `legacy_type` and `legacy_role` fields in the table. 
```ruby
rails map_legacy_roles_to_rolify:migrate
```
Once we have run this we will need to go onto the server to make sure the user has the right roles. 
So we would check a random user, and then see the roles they have. Then check using the `has_role?(:role_name)` query.
These should match up.
=> PSD-4522 - create type and role migration to roles task

.github/workflows/deploy-production.yml
Fix the failing `sed` command in the production deployment workflow by removing BSD-style empty string argument that's incompatible with GNU sed in the deployment environment.
```bash
sed -i 's/      - cosmetics-puma-env/      - cosmetics-puma-env\n      - antivirus-auth-env/g' ./cosmetics-web/manifest.yml
```
```
=> fix-sed-command
